### ISSUE TITLE
Fatal Error - I dont know why 

### ISSUE THREAD

**Issue by abdipriyangga** [prisma/studio#1000]
1. Prisma version (`prisma -v` or `npx prisma -v`):
    4.1.1
2. Logs from Developer Tools Console or Command line, if any:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model UserAgent {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  idRefrence        String?
  fullname          String?
  email             String       @unique
  password          String
  phoneNumber       String?
  gender            String?
  placeBirth        String?
  dateBirth         DateTime?
  address           String?
  lengthStay        String?
  marriage          String?
  nik               String?
  kkNumber          String?
  ktpImage          String?
  profileImage      String?
  skck              String?
  npwpImage         String?
  information       String?
  achivement        String?
  reason            String?
  goInternational   String?
  salaryExpectation String?
  role              String?
  orders            OrderAgent[]

  @@map("users_agent")
}

model UserCustomer {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  fullname          String?
  email             String    @unique
  password          String
  phoneNumber       String?
  gender            String?
  fatherName        String?
  placeBirth        String?
  dateBirth         DateTime?
  kkNumber          String?
  address           String?
  lengthStay        String?
  marriage          String?
  nik               String?
  ktpImage          String?
  profileImage      String?
  firstVaccineImage String?
  secVaccineImage   String?
  boostVaccineImage String?
  officeImigration  String?
  passporNumber     String?
  activePasspor     DateTime?
  expiredPasspor    DateTime?
  passporImage      String?
  role              String

  @@map("users_customer")
}

model ProductsUmrah {
  id        Int      @unique @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  productName      String?
  picture          String[]
  price            String?
  description      String?
  termCondition    String?
  schedulePlan     schedulePlan[]
  roomTypes        RoomType[]
  hotels           Hotel[]
  foods            Food[]
  ittenaries       Ittenary[]
  arrivals         Arrival[]
  manasikSchedules ManasikSchedule[]
  Order            OrderAgent?       @relation(fields: [orderId], references: [id])
  orderId          Int?

  @@map("product_umrah")
}

model Food {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  restaurantName String?
  servingType    String?

  ProductsUmrah   ProductsUmrah? @relation(fields: [productsUmrahId], references: [id])
  productsUmrahId Int?
}

model Ittenary {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  day             String?
  description     String?
  kategori        String?
  ProductsUmrah   ProductsUmrah? @relation(fields: [productsUmrahId], references: [id])
  productsUmrahId Int?
}

model Hotel {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  mekkah          String?
  madinah         String?
  detailPrice     String[]
  ProductsUmrah   ProductsUmrah? @relation(fields: [productsUmrahId], references: [id])
  productsUmrahId Int?
}

model RoomType {
  id              Int            @id @default(autoincrement())
  createdAt       DateTime       @default(now())
  updatedAt       DateTime       @updatedAt
  nameRoom        String[]
  price           String[]
  ProductsUmrah   ProductsUmrah? @relation(fields: [productsUmrahId], references: [id])
  productsUmrahId Int?
}

model schedulePlan {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  airwaysDeparture      String?
  dateDeparture         String?
  seat                  String?
  ruteDeparture         String?
  flightNumberDeparture String?
  airwaysArrival        String?
  dateArrival           String?
  ruteArrival           String?
  flightNumberArrival   String?
  timeManasik           String?
  dateManasik           String?
  ProductsUmrah         ProductsUmrah? @relation(fields: [productsUmrahId], references: [id])
  productsUmrahId       Int?
}

model Arrival {
  id              Int            @id @default(autoincrement())
  createdAt       DateTime       @default(now())
  updatedAt       DateTime       @updatedAt
  date            String?
  rute            String?
  noPenerbangan   String?
  ProductsUmrah   ProductsUmrah? @relation(fields: [productsUmrahId], references: [id])
  productsUmrahId Int?
}

model ManasikSchedule {
  id              Int            @id @default(autoincrement())
  createdAt       DateTime       @default(now())
  updatedAt       DateTime       @updatedAt
  time            String?
  date            String?
  ProductsUmrah   ProductsUmrah? @relation(fields: [productsUmrahId], references: [id])
  productsUmrahId Int?
}

model PromoProducts {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  promoCode String?
  discounts String?
}

model SuperAdmin {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  fullname String?
  email    String  @unique
  password String
  picture  String?
  role     String

  @@map("super_admin")
}

model OrderAgent {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  orderRefrence String?         @db.VarChar(255)
  products      ProductsUmrah[]
  quantity      Int
  orderBy       UserAgent[]
}
![fatalerror](https://user-images.githubusercontent.com/60294028/182289737-92c088c9-c8e4-4519-9240-0825525600de.png)

```

**Comment by abdipriyangga** [comment]
I solved this error with follow this documentation #895
