### ISSUE TITLE
A non-recoverable error has occurred and studio has to be restarted. 

### ISSUE THREAD

**Issue by Mirz4** [prisma/studio#1005]
### Bug description

Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at xt.serialize (http://localhost:5555/assets/index.js:1:49091)
    at xt.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at xt.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by petradonka** [comment]
Have you made any recent changes to your code or schema that you think might be relevant? Which Prisma version are you using? Could you share your schema file?

If you can't think of any recent changes, does this workaround solve the issue: https://github.com/prisma/studio/issues/895#issuecomment-1083051249?
