### ISSUE TITLE
Prisma studio appimage application not working on ubuntu

### ISSUE THREAD

**Issue by code-withAshish** [prisma/studio#1007]
1. Prisma version (`prisma -v` or `npx prisma -v`): 4.2.1

2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "message": "Get config: Schema Parsing P1012\n\nerror: Datasource provider not known: \"cockroachdb\".\n  -->  schema.prisma:9\n   | \n 8 | datasource db {\n 9 |   provider = \"cockroachdb\"\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Get config: Schema Parsing P1012\n\nerror: Datasource provider not known: \"cockroachdb\".\n  -->  schema.prisma:9\n   | \n 8 | datasource db {\n 9 |   provider = \"cockroachdb\"\n   | \n\nValidation Error Count: 1\n\n    at getConfigNodeAPI (/tmp/.mount_Prismax4Y99T/resources/app.asar/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:103:11)\n    at async getConfig (/tmp/.mount_Prismax4Y99T/resources/app.asar/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:57:12)\n    at async Object.getGenerators (/tmp/.mount_Prismax4Y99T/resources/app.asar/node_modules/@prisma/sdk/dist/get-generators/getGenerators.js:97:18)\n    at async $ddc29f131ce7f392$export$569332143708bf93 (/tmp/.mount_Prismax4Y99T/resources/app.asar/node_modules/@prisma/studio-pcw/dist/index.js:237:30)\n    at async $3615da8794764d66$var$PCW.getDMMF (/tmp/.mount_Prismax4Y99T/resources/app.asar/node_modules/@prisma/studio-pcw/dist/index.js:324:47)\n    at async IpcMainImpl.$5291d6b59ade0cdb$var$prisma (/tmp/.mount_Prismax4Y99T/resources/app.asar/dist/main/index.js:159:45)"
}
Error: Error starting Prisma Client: {
  "message": "Get config: Schema Parsing P1012\n\nerror: Datasource provider not known: \"cockroachdb\".\n  -->  schema.prisma:9\n   | \n 8 | datasource db {\n 9 |   provider = \"cockroachdb\"\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Get config: Schema Parsing P1012\n\nerror: Datasource provider not known: \"cockroachdb\".\n  -->  schema.prisma:9\n   | \n 8 | datasource db {\n 9 |   provider = \"cockroachdb\"\n   | \n\nValidation Error Count: 1\n\n    at getConfigNodeAPI (/tmp/.mount_Prismax4Y99T/resources/app.asar/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:103:11)\n    at async getConfig (/tmp/.mount_Prismax4Y99T/resources/app.asar/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:57:12)\n    at async Object.getGenerators (/tmp/.mount_Prismax4Y99T/resources/app.asar/node_modules/@prisma/sdk/dist/get-generators/getGenerators.js:97:18)\n    at async $ddc29f131ce7f392$export$569332143708bf93 (/tmp/.mount_Prismax4Y99T/resources/app.asar/node_modules/@prisma/studio-pcw/dist/index.js:237:30)\n    at async $3615da8794764d66$var$PCW.getDMMF (/tmp/.mount_Prismax4Y99T/resources/app.asar/node_modules/@prisma/studio-pcw/dist/index.js:324:47)\n    at async IpcMainImpl.$5291d6b59ade0cdb$var$prisma (/tmp/.mount_Prismax4Y99T/resources/app.asar/dist/main/index.js:159:45)"
}
    at Zs.init (file:///tmp/.mount_Prismax4Y99T/resources/app.asar/dist/renderer/assets/index.js:1:81284)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by janpio** [comment]
Hey @code-withAshish, are you using the Electron version of Prisma Studio? Then the version of that is visible on the bottom left when you start the app. It should be `0.4xx.0` or similar.

**Comment by code-withAshish** [comment]
yeah seems like it i downloaded it from the prisma/studio github repo from the releases as i wanted to use prisma studio as a standalone app, i should mention that in the projects the browser version is working fine for the same schema.prisma file

and finally yes there is a version number mentioned in the bottom left corner and it reads ` 0.458.0 `

**Comment by janpio** [comment]
0.458.0 is from [v3.9.1](https://github.com/prisma/prisma/releases/tag/3.9.1), so from February 2022. We did release CockroachDB support in preview in 3.9.0 - so I would guess your schema of your project does not actually specify the preview feature flag that was required to enable that.

I suggest you update the Studio Electron version to the version your project normally is using (which is most probably newer as you write that the CLI Studio works fine).

Or better even, don't even use the Electron app any more: https://github.com/prisma/studio/issues/845

**Comment by code-withAshish** [comment]
i see
thanks for the help!!!
