### ISSUE TITLE
Don't know how to stop an error

### ISSUE THREAD

**Issue by msgggg** [prisma/studio#1009]
### Bug description

``
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at xt.serialize (http://localhost:5555/assets/index.js:1:49091)
    at xt.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at xt.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)
``
This thing continuously pops up and doesn't let me. open prisma studio. What do I have to do? And even if I click "discard all unsaved changes and studio" and close my db and open it again, the error persists. plz help me out. thanks

### How to reproduce

Every time I just open prisma studio, the error shows up and I cant access.

### Prisma information

4.2.1

### Environment & setup

- OS: 
- Browser: 
- Database: 

Mac Os, Postgres, Chrome

**Comment by petradonka** [comment]
Could you try if this solution works for you? https://github.com/prisma/studio/issues/895#issuecomment-1083051249

Did you recently upgrade your Prisma version?
