### ISSUE TITLE
bug arised

### ISSUE THREAD

**Issue by kane1997** [prisma/studio#1031]
### Bug description

Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at xt.serialize (http://localhost:5555/assets/index.js:1:49974)
    at xt.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at xt.update (http://localhost:5555/assets/index.js:1:49831)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:83936
    at Array.forEach (<anonymous>)

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by petradonka** [comment]
It looks like you're running into an issue that we're aware of. Does [this workaround](https://github.com/prisma/studio/issues/895#issuecomment-1083051249) (https://github.com/prisma/studio/issues/895#issuecomment-1083051249) resolve the problem for you?
