### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by thirasak-t** [prisma/studio#1032]
Report error

Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)

**Comment by petradonka** [comment]
It looks like you're running into an issue that we're aware of. Were there some specific steps that lead you to this error? Does [this workaround](https://github.com/prisma/studio/issues/895#issuecomment-1083051249) (https://github.com/prisma/studio/issues/895#issuecomment-1083051249) resolve the problem for you?
