### ISSUE TITLE
Fatal Error on Launch of Prisma Studio from cmd

### ISSUE THREAD

**Issue by Dunsin-cyber** [prisma/studio#1037]
1. Prisma version (`prisma -v ^4.4.0` 
![Prisma Studio - Google Chrome 10_12_2022 11_32_37 AM](https://user-images.githubusercontent.com/85681801/195320455-6338db7d-fd9a-49b5-8ed2-0dfd943bf961.png)
):

2. Logs from Developer Tools Console or Command line, if any:
```
`Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)`
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
Yes It does

5. Prisma schema (if relevant):

```

```

**Comment by Dunsin-cyber** [comment]
So I found a solution to this, 
Open your Browser Developer's tool , navigate to Application and then IndexedDB 
Delete the cached data there. 

works like butter, [got this insight from here ](https://github.com/prisma/studio/issues/895#issuecomment-1083051249)
