### ISSUE TITLE
cannot open studio

### ISSUE THREAD

**Issue by kane1997** [prisma/studio#1042]
### Bug description

AFTER I push to db then npx prisma studio

### Environment & setup

- Browser: 
- Database: 

### Prisma logs

Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at xt.serialize (http://localhost:5555/assets/index.js:1:49974)
    at xt.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at xt.update (http://localhost:5555/assets/index.js:1:49831)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:83936
    at Array.forEach (<anonymous>)

**Comment by petradonka** [comment]
Which Prisma version are you using?
