### ISSUE TITLE
prisma studio: fatal error 

### ISSUE THREAD

**Issue by amgoun** [prisma/studio#1048]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update 
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by petradonka** [comment]
@amgoun, what Prisma version are you using?

**Comment by amgoun** [comment]
v ^3.13.0",   but i have figured out  the the issue only in google chrome, it  work fine with Microsoft edge
