### ISSUE TITLE
could not determine executable to run

### ISSUE THREAD

**Issue by davidalejandroaguilar** [prisma/studio#1049]
### Bug description

Running `npx prima studio` results in:

> npm ERR! could not determine executable to run

### Expected behavior

Prisma Studio opened.

### Prisma information

```
npx prisma -v
Environment variables loaded from .env
prisma                  : 4.5.0
@prisma/client          : 4.5.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.5.0-43.0362da9eebca54d94c8ef5edd3b2e90af99ba452
Default Engines Hash    : 0362da9eebca54d94c8ef5edd3b2e90af99ba452
Studio                  : 0.476.0
```

### Environment & setup

- OS: Mac OS Monterrey 12.6
- Database: PostgreSQL 14.5

### Prisma logs

```
0 verbose cli /Users/david/.asdf/installs/nodejs/16.13.2/bin/node /Users/david/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.19.2
2 info using node@v16.13.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/david/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/david/src/repos/my_repo/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/david/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/david/.asdf/installs/nodejs/16.13.2/.npm/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 timing npm:load:configload Completed in 6ms
20 timing npm:load:mkdirpcache Completed in 0ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm exec prima studio
23 verbose argv "exec" "--" "prima" "studio"
24 timing npm:load:setTitle Completed in 5ms
25 timing config:load:flatten Completed in 1ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:/Users/david/.npm/_logs
28 verbose logfile /Users/david/.npm/_logs/2022-10-30T07_11_01_404Z-debug-0.log
29 timing npm:load:logFile Completed in 2ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 16ms
33 silly logfile start cleaning logs, removing 1 files
34 timing arborist:ctor Completed in 1ms
35 silly logfile done cleaning log files
36 http fetch GET 200 https://registry.npmjs.org/prima 75ms (cache revalidated)
37 timing command:exec Completed in 197ms
38 verbose stack Error: could not determine executable to run
38 verbose stack     at getBinFromManifest (/Users/david/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
38 verbose stack     at exec (/Users/david/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:173:15)
38 verbose stack     at async module.exports (/Users/david/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/npm/lib/cli.js:78:5)
39 verbose pkgid prima@0.0.1
40 verbose cwd /Users/david/src/repos/my_repo
41 verbose Darwin 21.6.0
42 verbose node v16.13.2
43 verbose npm  v8.19.2
44 error could not determine executable to run
45 verbose exit 1
46 timing npm Completed in 270ms
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     /Users/david/.npm/_logs/2022-10-30T07_11_01_404Z-debug-0.log
```

**Comment by davidalejandroaguilar** [comment]
Fixed by running:

```
rm -rf .git/hooks
yarn install
```
