### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Mateusnasciment** [prisma/studio#1065]
### Bug description

```
Error starting Prisma Client: {
  "code": "ENOENT",
  "message": "ENOENT: no such file or directory, copyfile '/home/codespace/.cache/prisma/master/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-1.1.x/libquery-engine' -> '/workspaces/sim-api/node_modules/prisma/engines/694eea289a8462c80264df36757e4fdc129b1b32/libquery_engine-debian-openssl-1.1.x.so.node'",
  "stack": "ENOENT: no such file or directory, copyfile '/home/codespace/.cache/prisma/master/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-1.1.x/libquery-engine' -> '/workspaces/sim-api/node_modules/prisma/engines/694eea289a8462c80264df36757e4fdc129b1b32/libquery_engine-debian-openssl-1.1.x.so.node'"
}
Error: Error starting Prisma Client: {
  "code": "ENOENT",
  "message": "ENOENT: no such file or directory, copyfile '/home/codespace/.cache/prisma/master/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-1.1.x/libquery-engine' -> '/workspaces/sim-api/node_modules/prisma/engines/694eea289a8462c80264df36757e4fdc129b1b32/libquery_engine-debian-openssl-1.1.x.so.node'",
  "stack": "ENOENT: no such file or directory, copyfile '/home/codespace/.cache/prisma/master/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-1.1.x/libquery-engine' -> '/workspaces/sim-api/node_modules/prisma/engines/694eea289a8462c80264df36757e4fdc129b1b32/libquery_engine-debian-openssl-1.1.x.so.node'"
}
    at qs.init (https://mateusnasciment-glowing-space-rotary-wp7vjq6jp54fgrwr-5555.preview.app.github.dev/assets/index.js:1:82942)
```

### Environment & setup

- Link to Data Browser instance: 
- OS: 
- Browser: 
- Database: 

### Prisma logs

```
Error starting Prisma Client: {
  "code": "ENOENT",
  "message": "ENOENT: no such file or directory, copyfile '/home/codespace/.cache/prisma/master/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-1.1.x/libquery-engine' -> '/workspaces/sim-api/node_modules/prisma/engines/694eea289a8462c80264df36757e4fdc129b1b32/libquery_engine-debian-openssl-1.1.x.so.node'",
  "stack": "ENOENT: no such file or directory, copyfile '/home/codespace/.cache/prisma/master/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-1.1.x/libquery-engine' -> '/workspaces/sim-api/node_modules/prisma/engines/694eea289a8462c80264df36757e4fdc129b1b32/libquery_engine-debian-openssl-1.1.x.so.node'"
}
Error: Error starting Prisma Client: {
  "code": "ENOENT",
  "message": "ENOENT: no such file or directory, copyfile '/home/codespace/.cache/prisma/master/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-1.1.x/libquery-engine' -> '/workspaces/sim-api/node_modules/prisma/engines/694eea289a8462c80264df36757e4fdc129b1b32/libquery_engine-debian-openssl-1.1.x.so.node'",
  "stack": "ENOENT: no such file or directory, copyfile '/home/codespace/.cache/prisma/master/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-1.1.x/libquery-engine' -> '/workspaces/sim-api/node_modules/prisma/engines/694eea289a8462c80264df36757e4fdc129b1b32/libquery_engine-debian-openssl-1.1.x.so.node'"
}
    at qs.init (https://mateusnasciment-glowing-space-rotary-wp7vjq6jp54fgrwr-5555.preview.app.github.dev/assets/index.js:1:82942)
```

**Comment by janpio** [comment]
Hey @Mateusnasciment, what command did you run when that happened?
From the error message it seems you were running it on Codescpaces?

**Comment by yaaamin** [comment]
This issue still happens on 4.15.0, when i run `npx prisma studio`
