### ISSUE TITLE
Prisma Studio not running

### ISSUE THREAD

**Issue by developersaintt** [prisma/studio#1078]
### Bug description

```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at xt.serialize (http://localhost:5555/assets/index.js:1:49974)
    at xt.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at xt.update (http://localhost:5555/assets/index.js:1:49831)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:83936
    at Array.forEach (<anonymous>)
```

### How to reproduce

run the following command `npx prisma db push`

### Prisma information

Last changings that I did in the schema.

```
model Task {
  id           String     @id @default(cuid())
  title        String
  notes        String?
  assignedTo   String?
  projectId    String?
  lastActivity DateTime   @default(now())
  createdAt    DateTime   @default(now())
  status       TaskStatus @default(PENDING)
  type         TaskType   @default(OPEN)
  timeLogs     TimeLog[]
  manualTime   Int?
  workers      User[]     @relation("taskWorkers")       //added this line

  user    User?    @relation(fields: [assignedTo], references: [id], onDelete: Cascade)
  project Project? @relation(fields: [projectId], references: [id])
}


model User {
  id                        String    @id @default(cuid())
  userCode                  String    @unique @default(cuid())
  name                      String?
  password                  String
  email                     String?   @unique
  emailVerified             DateTime?
  passwordResetToken        String?
  passwordResetTokenExpires DateTime?
  image                     String?
  createdAt                 DateTime? @default(now())
  deletedAt                 DateTime?
  updatedAt                 DateTime? @updatedAt

  accounts         Account[]
  sessions         Session[]
  membership       Member[]         @relation("membership")
  invitedMembers   Member[]         @relation("inviter")
  createdWorkspace Workspace[]
  customerPayment  CustomerPayment?
  domains          Domain[]
  tasks            Task[]
  screenshots      Screenshot[]
  projectsWorker   Project[]        @relation("workingProjects")
  projectsManaging Project[]        @relation("managingProjects")
  projectsCreated  Project[]        @relation("createdProjects")
  tasksWorker      Task[]           @relation("taskWorkers") // added this line

  TimeLog TimeLog[]

  @@unique([userCode, email])
  @@map("users")
}
```

### Environment & setup

- OS: Windows
- Browser: Edge
- Database: PostgreSQL

**Comment by developersaintt** [comment]
this solved it https://github.com/prisma/studio/issues/895#issuecomment-1083051249
