### ISSUE TITLE
WebStorm prisma studio comand falls

### ISSUE THREAD

**Issue by xnagaev** [prisma/studio#1117]
### Bug description

prisma studio command falls in the WebStorm IDE console since works in the terminal

### How to reproduce

run `prisma studio` command in Webstorm IDE

### Prisma information

"prisma": "^4.13.0", // in package.json

prisma -v or npx prisma -v // fall to the same error as in the bug description

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id Int @id @default(autoincrement())
}

### Environment & setup

- OS: Fedora Workstation 38
- Browser: Firefox
- Database: MySQL in docker // with docker desktop

### Prisma logs

 prisma studio                                  
.../node_modules/prisma/build/index.js:92872
if (typeof process !== "undefined" && typeof process.stderr?.write !== "function") {
                                                            ^

SyntaxError: Unexpected token '.'
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1048:15)
    at Module._compile (internal/modules/cjs/loader.js:1082:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by sercinci** [comment]
I would check if Webstorm is running your npm commands with the correct version of Node.js. Look for `Languages & Frameworks -> Node.js -> Node interpreter`
