### ISSUE TITLE
non recoverable, please clear out your indexesDb and try again

### ISSUE THREAD

**Issue by fadliRafidan** [prisma/studio#1147]
### Bug description

non recoverable, please clear out your indexesDb and try again

### How to reproduce

2. Change '....'
3. Run '....'
4. See errors

### Prisma information

4.3.1

### Environment & setup

- OS: 
- Browser: 
- Database: 

### Prisma logs

Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at xt.serialize (http://localhost:5555/assets/index.js:1:49974)
    at xt.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at xt.update (http://localhost:5555/assets/index.js:1:49831)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:83936
    at Array.forEach (<anonymous>)

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895
