### ISSUE TITLE
Connection to Prism Studio for a vercel DB via prisma accelerate started failing all of a sudden

### ISSUE THREAD

**Issue by saurabhgaur** [prisma/studio#1150]
### Bug description

trying to connect to a postgres vercel db via prisma proxy started failing . 
POSTGRES_PRISMA_URL="prisma://accelerate.prisma-data.net/?api_key=xxxxx"

I am able to connect directly via pgadmin, and this was working till couple of hours ago

### How to reproduce

setup nextjs project to connect to vercel db via prisma accelerate..
unable to connect

getting errors like this 

Unknown server error: {"type":"UnknownTextError","body":"<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n"} (The request id was: 7fdee4261f78860e)
    at async getApiLimitCount (./lib/api-limit.ts:56:26)
    at async DashboardLayout (layout.tsx:19:27)
digest: "2404839002"
- error PrismaClientKnownRequestError: 
Invalid `prisma.userApiLimit.findUnique()` invocation:

Unknown server error: {"type":"UnknownTextError","body":"<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n"} (The request id was: 7fdee4269e08f421)
    at async getApiLimitCount (./lib/api-limit.ts:56:26)
    at async DashboardLayout (layout.tsx:19:27)
digest: "2327800538"
- error PrismaClientKnownRequestError: 
Invalid `prisma.userApiLimit.findUnique()` invocation:

Unknown server error: {"type":"UnknownTextError","body":"<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n"} (The request id was: 7fdee4261f78860e)
    at async getApiLimitCount (./lib/api-limit.ts:56:26)
    at async DashboardLayout (layout.tsx:19:27)
digest: "2404839002"

### Prisma information

prisma                  : 5.2.0
@prisma/client          : 5.2.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.2.0-25.2804dc98259d2ea960602aca6b8e7fdc03c1758f
Default Engines Hash    : 2804dc98259d2ea960602aca6b8e7fdc03c1758f
Studio                  : 0.494.0

### Environment & setup

macos as well as vercel deployment

**Comment by saurabhgaur** [comment]
seems to be working again now
