### ISSUE TITLE
Primsa studio not displaying the models I created.

### ISSUE THREAD

**Issue by Visinho** [prisma/studio#1151]
### Bug description

I have created some models but the prisma studio is not displaying them. 

I see this error in my terminal: 
```
Downloading Prisma engines for Node-API for windows [] 0%Unable to get DMMF from Prisma Client:  FetchError: request to https://binaries.prisma.sh/all_commits/2804dc98259d2ea960602aca6b8e7fdc03c1758f/windows/query_engine.dll.node.sha256 failed, reason: connect ETIMEDOUT 104.22.23.109:443
    at ClientRequest.<anonymous> (C:\Users\pc\Desktop\nestjs_rabbit-mq\node_modules\prisma\build\index.js:35929:15)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)      
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)       
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  attemptNumber: 3,
  retriesLeft: 0
}
```

### Environment & setup

- OS: 
- Browser: 
- Database: 

### Prisma logs

```
Downloading Prisma engines for Node-API for windows [] 0%Unable to get DMMF from Prisma Client:  FetchError: request to https://binaries.prisma.sh/all_commits/2804dc98259d2ea960602aca6b8e7fdc03c1758f/windows/query_engine.dll.node.sha256 failed, reason: connect ETIMEDOUT 104.22.23.109:443
    at ClientRequest.<anonymous> (C:\Users\pc\Desktop\nestjs_rabbit-mq\node_modules\prisma\build\index.js:35929:15)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)      
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)       
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  attemptNumber: 3,
  retriesLeft: 0
}
```

**Comment by janpio** [comment]
Something on your side is blocking the download.
Can you click the link and download it manually?
