### ISSUE TITLE
prisma studio error, not open schema

### ISSUE THREAD

**Issue by mayunxuan** [prisma/studio#1185]
1. Prisma version (`prisma -v` or `npx prisma -v`):
prisma                  : 5.6.0
@prisma/client          : 5.6.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.9.0
Query Engine (Node-API) : libquery-engine e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules\.pnpm\registry.npmmirror.com+@prisma+engines@5.6.0\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules\.pnpm\registry.npmmirror.com+@prisma+engines@5.6.0\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.6.0-32.e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Default Engines Hash    : e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Studio                  : 0.495.0
Preview Features        : fullTextSearch
2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "message": "Schema parsing\nerror: Error parsing attribute \"@default\": Cannot set a default value on list field.\n  -->  schema.prisma:25\n   | \n24 |   dynamicFields Json?\n25 |   tag           String[]            @default([])\n   | \n\nValidation Error Count: 1",
  "stack": "Error: Schema parsing\nerror: Error parsing attribute \"@default\": Cannot set a default value on list field.\n  -->  schema.prisma:25\n   | \n24 |   dynamicFields Json?\n25 |   tag           String[]            @default([])\n   | \n\nValidation Error Count: 1\n    at getDmmfNodeAPI (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\sdk\\dist\\engine-commands\\getDmmf.js:70:11)\n    at async getDMMF (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\sdk\\dist\\engine-commands\\getDmmf.js:49:12)\n    at async Object.getGenerators (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\sdk\\dist\\get-generators\\getGenerators.js:108:16)\n    at async $ddc29f131ce7f392$export$569332143708bf93 (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\studio-pcw\\dist\\index.js:237:30)\n    at async $3615da8794764d66$var$PCW.getDMMF (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\studio-pcw\\dist\\index.js:324:47)\n    at async IpcMainImpl.$5291d6b59ade0cdb$var$prisma (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\dist\\main\\index.js:159:45)"
}
Error: Error starting Prisma Client: {
  "message": "Schema parsing\nerror: Error parsing attribute \"@default\": Cannot set a default value on list field.\n  -->  schema.prisma:25\n   | \n24 |   dynamicFields Json?\n25 |   tag           String[]            @default([])\n   | \n\nValidation Error Count: 1",
  "stack": "Error: Schema parsing\nerror: Error parsing attribute \"@default\": Cannot set a default value on list field.\n  -->  schema.prisma:25\n   | \n24 |   dynamicFields Json?\n25 |   tag           String[]            @default([])\n   | \n\nValidation Error Count: 1\n    at getDmmfNodeAPI (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\sdk\\dist\\engine-commands\\getDmmf.js:70:11)\n    at async getDMMF (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\sdk\\dist\\engine-commands\\getDmmf.js:49:12)\n    at async Object.getGenerators (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\sdk\\dist\\get-generators\\getGenerators.js:108:16)\n    at async $ddc29f131ce7f392$export$569332143708bf93 (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\studio-pcw\\dist\\index.js:237:30)\n    at async $3615da8794764d66$var$PCW.getDMMF (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\studio-pcw\\dist\\index.js:324:47)\n    at async IpcMainImpl.$5291d6b59ade0cdb$var$prisma (C:\\Users\\mayunxuan\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\dist\\main\\index.js:159:45)"
}
    at Zs.init (file:///C:/Users/mayunxuan/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/dist/renderer/assets/index.js:1:81284)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```
model Post {
  id            Int                 @id @default(autoincrement())
  title         String
  categories    CategoriesOnPosts[]
  User          User?               @relation(fields: [userId], references: [id])
  userId        Int?
  dynamicFields Json?
  tag           String[]            @default([])
}
```

add model field tag has error

**Comment by janpio** [comment]
Yes, and the error message tells you what the problem is:
```
Error parsing attribute \"@default\": Cannot set a default value on list field.
```
You get the same error message when running `prisma format` or `prisma validate`.

You have to fix your schema first before Studio can work.
