### ISSUE TITLE
Error: Invalid `prisma.pricings.findMany()` invocation: Value not found in enum

### ISSUE THREAD

**Issue by chidindu-ogbonna** [prisma/studio#1220]
1. Prisma version (`prisma -v` or `npx prisma -v`): 5.11.0

2. Logs from Developer Tools Console or Command line, if any:
```
PrismaClientUnknownRequestError: 
Invalid `prisma.pricings.findMany()` invocation:


Value 'EVERYWHERE' not found in enum 'PricingsCurrency'
    at In.handleRequestError (/Users/6ones/Projects/fela/fela.ai/node_modules/@prisma/client/runtime/library.js:122:7044)
    at In.handleAndLogRequestError (/Users/6ones/Projects/fela/fela.ai/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/Users/6ones/Projects/fela/fela.ai/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/Users/6ones/Projects/fela/fela.ai/node_modules/@prisma/client/runtime/library.js:127:10871)
   ....{
  clientVersion: '5.11.0'
}
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
Yes
4. Prisma schema (if relevant):
```
enum PricingsType {
    TRIAL
    DAILY
    WEEKLY
}

enum PricingsCurrency {
    NGN
    KSH
    EVERYWHERE
}

model Billings {
    id        Int      @id @default(autoincrement())
    userId    String // Supabase Auth User ID
    pricing   Pricings @relation(fields: [pricingId], references: [id])
    pricingId Int
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
}

model Pricings {
    id           Int              @id @default(autoincrement())
    type         PricingsType
    amount       Float
    currency     PricingsCurrency
    numberOfDays Int
    isActive     Boolean          @default(true)
    billings     Billings[]
    createdAt    DateTime         @default(now())
    updatedAt    DateTime         @updatedAt
}

```

**Comment by chidindu-ogbonna** [comment]
I noticed this error happens when I include a new value to the Enum.

**Comment by janpio** [comment]
Did you restart Prisma Studio after doing so? It seems to still be using the old `enum` definition, and then getting data it does not know what to do about.

**Comment by igalklebanov** [comment]
Hey :wave:

Prisma ORM 7 introduces a brand new standalone [Studio](https://www.prisma.io/docs/orm/tools/prisma-studio), built from the ground up to work everywhere, with or without Prisma ORM. Consequently, all "old Studio" issues are being closed as there won't be any further work on it. :mega:

The new Studio is also available in the Prisma VS Code extension and in the Prisma Console application. :electric_plug:

Help shape, improve and fix the new Studio with us in this repository by submitting bug reports and feature requests. :construction_worker:
