### ISSUE TITLE
Error starting Prisma Client: {   "code": "ENOSPC",   "message": "ENOSPC: no space left on device, copyfile 

### ISSUE THREAD

**Issue by celestino12c** [prisma/studio#1231]
### Bug description

Error starting Prisma Client: {
  "code": "ENOSPC",
  "message": "ENOSPC: no space left on device, copyfile '/home/celestino/.cache/prisma/master/473ed3124229e22d881cb7addf559799debae1ab/debian-openssl-3.0.x/libquery-engine' -> '/home/celestino/www/server-node/node_modules/prisma/engines/473ed3124229e22d881cb7addf559799debae1ab/libquery_engine-debian-openssl-3.0.x.so.node'",
  "stack": "ENOSPC: no space left on device, copyfile '/home/celestino/.cache/prisma/master/473ed3124229e22d881cb7addf559799debae1ab/debian-openssl-3.0.x/libquery-engine' -> '/home/celestino/www/server-node/node_modules/prisma/engines/473ed3124229e22d881cb7addf559799debae1ab/libquery_engine-debian-openssl-3.0.x.so.node'"
}
Error: Error starting Prisma Client: {
  "code": "ENOSPC",
  "message": "ENOSPC: no space left on device, copyfile '/home/celestino/.cache/prisma/master/473ed3124229e22d881cb7addf559799debae1ab/debian-openssl-3.0.x/libquery-engine' -> '/home/celestino/www/server-node/node_modules/prisma/engines/473ed3124229e22d881cb7addf559799debae1ab/libquery_engine-debian-openssl-3.0.x.so.node'",
  "stack": "ENOSPC: no space left on device, copyfile '/home/celestino/.cache/prisma/master/473ed3124229e22d881cb7addf559799debae1ab/debian-openssl-3.0.x/libquery-engine' -> '/home/celestino/www/server-node/node_modules/prisma/engines/473ed3124229e22d881cb7addf559799debae1ab/libquery_engine-debian-openssl-3.0.x.so.node'"
}
    at qs.init (http://localhost:5555/assets/index.js:1:82961)

### Environment & setup

- OS: 
- Browser: 
- Database: 

### Prisma logs

Error starting Prisma Client: {
  "code": "ENOSPC",
  "message": "ENOSPC: no space left on device, copyfile '/home/celestino/.cache/prisma/master/473ed3124229e22d881cb7addf559799debae1ab/debian-openssl-3.0.x/libquery-engine' -> '/home/celestino/www/server-node/node_modules/prisma/engines/473ed3124229e22d881cb7addf559799debae1ab/libquery_engine-debian-openssl-3.0.x.so.node'",
  "stack": "ENOSPC: no space left on device, copyfile '/home/celestino/.cache/prisma/master/473ed3124229e22d881cb7addf559799debae1ab/debian-openssl-3.0.x/libquery-engine' -> '/home/celestino/www/server-node/node_modules/prisma/engines/473ed3124229e22d881cb7addf559799debae1ab/libquery_engine-debian-openssl-3.0.x.so.node'"
}
Error: Error starting Prisma Client: {
  "code": "ENOSPC",
  "message": "ENOSPC: no space left on device, copyfile '/home/celestino/.cache/prisma/master/473ed3124229e22d881cb7addf559799debae1ab/debian-openssl-3.0.x/libquery-engine' -> '/home/celestino/www/server-node/node_modules/prisma/engines/473ed3124229e22d881cb7addf559799debae1ab/libquery_engine-debian-openssl-3.0.x.so.node'",
  "stack": "ENOSPC: no space left on device, copyfile '/home/celestino/.cache/prisma/master/473ed3124229e22d881cb7addf559799debae1ab/debian-openssl-3.0.x/libquery-engine' -> '/home/celestino/www/server-node/node_modules/prisma/engines/473ed3124229e22d881cb7addf559799debae1ab/libquery_engine-debian-openssl-3.0.x.so.node'"
}
    at qs.init (http://localhost:5555/assets/index.js:1:82961)

**Comment by janpio** [comment]
Your hard disk did not have enough space to run Studio: `ENOSPC: no space left on device,`
