### ISSUE TITLE
Error when change prop in table (in prisma studio)

### ISSUE THREAD

**Issue by gnvcor** [prisma/studio#1241]
### Bug description

TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at St.serialize (http://localhost:5555/assets/index.js:1:50152)
    at St.update (http://localhost:5555/assets/index.js:1:11860)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at St.n (http://localhost:5555/assets/vendor.js:50:6688)
    at St.update (http://localhost:5555/assets/index.js:1:50009)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at St.n (http://localhost:5555/assets/vendor.js:50:6688)
    at Yr.handleCellValueChanged (http://localhost:5555/assets/index.js:1:212591)
    at valueSetter (http://localhost:5555/assets/index.js:1:208303)

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by janpio** [comment]
What version of Prisma are you using? Do you have a `BigInt` field in your Prisma Schema?

**Comment by gnvcor** [comment]
Now, i used prisma@5.15.0 and i catch error Message: Do not know how to serialize a BigInt

Yep, i have BigInt in my Prisma Schema.
But, early, my schema don't have type BigInt, i used simple Int type.

May be i have problem, because part data in my table have type Int and rest data have type BigInt?

**Comment by igalklebanov** [comment]
Hey :wave:

Prisma ORM 7 introduces a brand new standalone [Studio](https://www.prisma.io/docs/orm/tools/prisma-studio), built from the ground up to work everywhere, with or without Prisma ORM. Consequently, all "old Studio" issues are being closed as there won't be any further work on it. :mega:

The new Studio is also available in the Prisma VS Code extension and in the Prisma Console application. :electric_plug:

Help shape, improve and fix the new Studio with us in this repository by submitting bug reports and feature requests. :construction_worker:
