### ISSUE TITLE
Error in prisma studio

### ISSUE THREAD

**Issue by oio3** [prisma/studio#1272]
### Bug description

Error starting Prisma Client: {
  "message": "\n    GeneratorError: Generator \"/data/data/com.termux/files/home/hello-prisma/node_modules/prisma/prisma-client/generator-build/index.js\" failed:\n    error: expected absolute path: \"--max-old-space-size=8096\"\n        at ChildProcess.<anonymous> (/data/data/com.termux/files/home/hello-prisma/node_modules/prisma/build/index.js:314:1731)\n        at ChildProcess.emit (node:events:520:28)\n        at ChildProcess._handle.onexit (node:internal/child_process:294:12)",
  "stack": "\n    GeneratorError: Generator \"/data/data/com.termux/files/home/hello-prisma/node_modules/prisma/prisma-client/generator-build/index.js\" failed:\n    error: expected absolute path: \"--max-old-space-size=8096\"\n        at ChildProcess.<anonymous> (/data/data/com.termux/files/home/hello-prisma/node_modules/prisma/build/index.js:314:1731)\n        at ChildProcess.emit (node:events:520:28)\n        at ChildProcess._handle.onexit (node:internal/child_process:294:12)"
}
Error: Error starting Prisma Client: {
  "message": "\n    GeneratorError: Generator \"/data/data/com.termux/files/home/hello-prisma/node_modules/prisma/prisma-client/generator-build/index.js\" failed:\n    error: expected absolute path: \"--max-old-space-size=8096\"\n        at ChildProcess.<anonymous> (/data/data/com.termux/files/home/hello-prisma/node_modules/prisma/build/index.js:314:1731)\n        at ChildProcess.emit (node:events:520:28)\n        at ChildProcess._handle.onexit (node:internal/child_process:294:12)",
  "stack": "\n    GeneratorError: Generator \"/data/data/com.termux/files/home/hello-prisma/node_modules/prisma/prisma-client/generator-build/index.js\" failed:\n    error: expected absolute path: \"--max-old-space-size=8096\"\n        at ChildProcess.<anonymous> (/data/data/com.termux/files/home/hello-prisma/node_modules/prisma/build/index.js:314:1731)\n        at ChildProcess.emit (node:events:520:28)\n        at ChildProcess._handle.onexit (node:internal/child_process:294:12)"
}
    at qs.init (http://localhost:5555/assets/index.js:1:82961)

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by igalklebanov** [comment]
Hey :wave:

Prisma ORM 7 introduces a brand new standalone [Studio](https://www.prisma.io/docs/orm/tools/prisma-studio), built from the ground up to work everywhere, with or without Prisma ORM. Consequently, all "old Studio" issues are being closed as there won't be any further work on it. :mega:

The new Studio is also available in the Prisma VS Code extension and in the Prisma Console application. :electric_plug:

Help shape, improve and fix the new Studio with us in this repository by submitting bug reports and feature requests. :construction_worker:
