### ISSUE TITLE
clausecraft

### ISSUE THREAD

**Issue by rabbittrix** [prisma/studio#1302]
### Bug description

    at nc (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:419:1543)
    at async AAt (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:5377)
    at async Hj.getDMMF (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:6729)
    at async Vj.respond (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:10827)
    at async I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:13419
Unable to get DMMF from Prisma Client:  Error: 
You don't have any models defined in your schema.prisma, so nothing will be generated.
You can define a model like this:

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}

More information in our documentation:
https://pris.ly/d/prisma-schema

    at nc (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:419:1543)
    at async AAt (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:5377)
    at async Hj.getDMMF (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:6729)
    at async Vj.respond (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:10827)
    at async I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:13419

### Environment & setup

- OS: 
- Browser: 
- Database: 

### Prisma logs

    at nc (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:419:1543)
    at async AAt (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:5377)
    at async Hj.getDMMF (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:6729)
    at async Vj.respond (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:10827)
    at async I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:13419
Unable to get DMMF from Prisma Client:  Error: 
You don't have any models defined in your schema.prisma, so nothing will be generated.
You can define a model like this:

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}

More information in our documentation:
https://pris.ly/d/prisma-schema

    at nc (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:419:1543)
    at async AAt (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:5377)
    at async Hj.getDMMF (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:6729)
    at async Vj.respond (I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:10827)
    at async I:\Cursor_test\CETP\node_modules\prisma\build\index.js:1935:13419

**Comment by igalklebanov** [comment]
Hey :wave:

Prisma ORM 7 introduces a brand new standalone [Studio](https://www.prisma.io/docs/orm/tools/prisma-studio), built from the ground up to work everywhere, with or without Prisma ORM. Consequently, all "old Studio" issues are being closed as there won't be any further work on it. :mega:

The new Studio is also available in the Prisma VS Code extension and in the Prisma Console application. :electric_plug:

Help shape, improve and fix the new Studio with us in this repository by submitting bug reports and feature requests. :construction_worker:
