### ISSUE TITLE
Reloading the browser crashes Studio

### ISSUE THREAD

**Issue by timsuchanek** [prisma/studio#165]
The whole dev command crashes with this stack trace
```
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/usr/local/lib/node_modules/prisma2/build/index.js:165450:19)
    at ChildProcess.photonWorker.on.msg (/usr/local/lib/node_modules/prisma2/build/index.js:652:60)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by madebysid** [comment]
https://github.com/prisma/studio/issues/151 is where I'm tracking this :D
