### ISSUE TITLE
Page error

### ISSUE THREAD

**Issue by AcerFeng** [prisma/studio#280]
<Anything that helps us reproduce the error goes here>

In Chrome 78.0.3904.97

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"

**Error dump**
Cannot read property 'id' of null

**Stacktrace**

    in u
    in div
    in u
    in div
    in Ec
    in div
    in u

console:

```
Websocket not open. Queueing this event: {"action":"get","data":{}}
studioBundle.js:88 Studio version 0.146.0
studioBundle.js:88 Socket connection established
studioBundle.js:88 Replaying queued events
studioBundle.js:88 Sending photon request:  photon.users.findMany({
  select: {
    id: true,
    email: true,
    password: true,
    name: true,
    posts: true,
  },
  orderBy: {
    id: "asc",
  },
  first: 100,
})
studioBundle.js:88 TypeError: Cannot read property 'id' of null
    at studioBundle.js:102
    at Array.map (<anonymous>)
    at studioBundle.js:102
    at studioBundle.js:102
    at studioBundle.js:102
    at ge (studioBundle.js:16)
    at e.track (studioBundle.js:16)
    at Fe (studioBundle.js:102)
    at studioBundle.js:102
    at Xo (studioBundle.js:65)
    at xr (studioBundle.js:65)
    at Nr (studioBundle.js:65)
    at Er (studioBundle.js:65)
    at Gs (studioBundle.js:65)
    at Qs (studioBundle.js:65)
    at ka (studioBundle.js:65)
    at Oa (studioBundle.js:65)
    at Pa (studioBundle.js:65)
    at Ae (studioBundle.js:16)
    at Pe (studioBundle.js:16)
    at je (studioBundle.js:16)
    at ee (studioBundle.js:16)
    at $ (studioBundle.js:16)
    at ji.i (studioBundle.js:16)
    at wn.init (studioBundle.js:102)
```

but it's work fine in Firefox

"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"

**Comment by madebysid** [comment]
Hey @AcerFeng, I'm unable to see this. I did just push out alpha.309 with a bunch of fixes. Could you try installing it with `npm i -g prisma2@alpha` and let me know if you're still seeing this? Thanks!

**Comment by madebysid** [comment]
Hey @AcerFeng, I'm unable to see this. I did just push out alpha.337 with a bunch of fixes. Could you try installing it with npm i -g prisma2@alpha and let me know if you're still seeing this? Thanks!

**Comment by AcerFeng** [comment]
@madebysid 

```
Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server (prisma2)
$ yarn global add prisma2@alpha
yarn global v1.13.0


[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@vue/cli > @vue/cli-ui > graphql-tag@2.10.1" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "@vue/cli > @vue/cli-ui > graphql-type-json@0.2.1" has unmet peer dependency "graphql@>=0.8.0".
[4/4] Building fresh packages...
success Installed "prisma2@2.0.0-alpha.351" with binaries:
      - prisma2
Done in 7.77s.

Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server (prisma2)
$ yarn
yarn install v1.13.0


[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > nexus-prisma@0.6.1" has unmet peer dependency "@prisma/photon@^2.0.0-alpha.351".
[4/4] Building fresh packages...
success Saved lockfile.
$ npm -s run generate
> Downloading windows binary for query-engine [====================] 100%



Generating Photon.js to C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\@generated\photon
Done in 3.10s

Error: Failed to import photon package at @prisma/photon. The following error occured while trying:

        Error: Cannot find module '@prisma/photon'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.exports.get (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus-prisma\src\dmmf\utils.ts:12:27)
    at new SchemaBuilder (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus-prisma\src\builder.ts:164:38)
    at Object.build (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus-prisma\src\builder.ts:91:19)
    at Object.onInstall (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus-prisma\src\index.ts:43:16)
    at plugins.forEach (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus\src\builder.ts:700:44)
    at Array.forEach (<anonymous>)
    at Object.exports.get (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus-prisma\src\dmmf\utils.ts:14:11)
    at new SchemaBuilder (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus-prisma\src\builder.ts:164:38)
    at Object.build (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus-prisma\src\builder.ts:91:19)
    at Object.onInstall (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus-prisma\src\index.ts:43:16)
    at plugins.forEach (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus\src\builder.ts:700:44)
    at Array.forEach (<anonymous>)
    at SchemaBuilder.beforeWalkTypes (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus\src\builder.ts:694:18)
    at SchemaBuilder.getFinalTypeMap (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus\src\builder.ts:784:10)
    at makeSchemaInternal (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus\src\builder.ts:1571:15)
    at Object.makeSchema (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus\src\builder.ts:1616:49)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server (prisma2)
$ prisma2 -v
prisma2@2.0.0-alpha.351, binary version: b8d90fea39d266b128b4d748db5aca8505bb1026


Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server (prisma2)
$ which prisma2
/c/Users/Administrator/AppData/Local/Yarn/bin/prisma2
```

install error.

**Comment by madebysid** [comment]
Hey @AcerFeng, there was a tiny breaking change with the latest preview (which I'm fairly certain was alpha when you tried it out), here's details: https://github.com/prisma/prisma2/releases/tag/2.0.0-preview017

If you go over and make these changes, clear IndexedDB (to make sure), does this still happen?

**Comment by AcerFeng** [comment]
@madebysid 

```
Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples (prisma2)
$ git pull
Already up to date.

Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples (prisma2)
$ git status
On branch prisma2
Your branch is up to date with 'origin/prisma2'.

nothing to commit, working tree clean

Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples (prisma2)
$ cd typescript/graphql-apollo-server/

Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server (prisma2)
$ ls
package.json  prisma  README.md  src  tsconfig.json

Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server (prisma2)
$ prisma2 -v
prisma2@2.0.0-preview017, binary version: 6159bf3a263921c3c28ee68e2c9e130b5a69c293

Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server (prisma2)
$ yarn
yarn install v1.13.0
warning package.json: No license field
info No lockfile found.
warning typescript-graphql: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ npm -s run generate
Error: Problem while parsing the query engine response at C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\query-engine-windows.exe. Please wait unti
l the 'prisma query-engine' download completes!
SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\build\index.js:109803:25)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\build\index.js:109753:58)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by madebysid** [comment]
Okay I've only just seen you're using the Apollo Server example. So I tried out the same example from [prisma-examples](https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-apollo-server), and after installing dependencies with `yarn`, ran `npx prisma2 dev` in that directory, opened up `localhost:5555` and can't see this. :(

In your specific case, it also looks like the binary download failed for some reason. Drastic, but try deleting `node_modules` and try again?

Once you get the binary downloaded correctly (read: stop seeing that error), instead of generating photon yourself (you don't need to do that to use Studio), if you run `npx prisma2 dev` yourself, does that work?
Also try clearing IndexedDB either manually or by clicking on `Clear cache and reload` button on the error modal you're seeing in Studio

**Comment by AcerFeng** [comment]
Obstructed by [#985](https://github.com/prisma/prisma2/issues/985)

**Comment by AcerFeng** [comment]
I pulled `prisma-examples` , remove `node_modules` and `yarn.lock`,  run `yarn`, and then run `npx prisma2 dev`:

```
Administrator@DESKTOP-DMSGKOE MINGW64 ~/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server (prisma2)
$ npx prisma2 dev

   Watching for changes in prisma\schema.prisma
   Last changed at 16:23:59


   Migrations
   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ✓ Database successfully migrated
   To save changes into a migration file, run prisma2 lift save


   Generators
   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

   Watching for changes in prisma\schema.prisma

   Watching for changes in prisma\schema.prisma
   Last changed at 16:23:59


   Migrations
   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

   Watching for changes in prisma\schema.prisma

   Watching for changes in prisma\schema.prisma

   Watching for changes in prisma\schema.prisma
   Last changed at 16:23:59


   Migrations
   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ✓ Database successfully migrated
   To save changes into a migration file, run prisma2 lift save


   Generators
   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ✓ Photon.js    Generated in 4.74s







   Studio endpoint: http://localhost:5555/
   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   d: diff
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Failed to generate Photon client: { AggregateError:
    Error: Generator at C:/Users/Administrator/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server/node_modules/prisma2/photon/generator-build/index.js could not start:
    'C:/Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
    ���������ļ���
        at Timeout.setTimeout [as _onTimeout] (C:/Users/Administrator/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server/node_modules/prisma2/build/index.js:37594:28)
    at next (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\build\index.js:17684:14)
    at C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\build\index.js:17708:7 name: 'AggregateError' }
Error starting Photon: TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
    at Photon.start (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\build\index.js:237561:43)
Error connecting to Photon TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
    at connect (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\build\photon-worker.js:39:31)
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Failed to generate Photon client: { AggregateError:
    Error: Generator at C:/Users/Administrator/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server/node_modules/prisma2/photon/generator-build/index.js could not start:
    'C:/Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
    ���������ļ���
        at Timeout.setTimeout [as _onTimeout] (C:/Users/Administrator/Documents/GitHub/prisma-examples/typescript/graphql-apollo-server/node_modules/prisma2/build/index.js:37594:28)
    at next (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\build\index.js:17684:14)
    at C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\build\index.js:17708:7 name: 'AggregateError' }
Error starting Photon: TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
    at Photon.start (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\build\index.js:237561:43)
Error connecting to Photon TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
    at connect (C:\Users\Administrator\Documents\GitHub\prisma-examples\typescript\graphql-apollo-server\node_modules\prisma2\build\photon-worker.js:39:31)
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```

In Chrome `localhost:5555`:

```
Websocket not open. Queueing this event: {"action":"get","data":{}}
studioBundle.js:73 Studio version 0.155.0
studioBundle.js:73 Socket connection established
studioBundle.js:73 Replaying queued events
studioBundle.js:73 ------Starting IndexedDB migration------
studioBundle.js:73 ---Running migration for v1---
studioBundle.js:73 Created projects table
studioBundle.js:73 Created openTabs table
studioBundle.js:73 Created sessions table
studioBundle.js:73 Created scripts table
studioBundle.js:73 ---Migrated to v1---
studioBundle.js:73 ---Running migration for v2---
studioBundle.js:73 Created models table
studioBundle.js:73 Created fields table
studioBundle.js:73 Created enums table
studioBundle.js:73 ---Migrated to v2---
studioBundle.js:73 ---Running migration for v3---
(index):1 Site cannot be installed: Page has no manifest <link> URL
studioBundle.js:73 Found all sessions []
studioBundle.js:73 Found all scripts []
studioBundle.js:73 ---Migrated to v3---
studioBundle.js:73 ---Running migration for v4---
studioBundle.js:73 Created tabs table
studioBundle.js:73 Found all openTabs []
studioBundle.js:73 Deleted openTabs table
studioBundle.js:73 ---Migrated to v4---
studioBundle.js:73 ---Running migration for v5---
studioBundle.js:73 Found all tabs []
studioBundle.js:73 Found all projects []
studioBundle.js:73 ---Migrated to v5---
studioBundle.js:73 ---Running migration for v6---
studioBundle.js:73 Added projectId to tabs table keyPath
studioBundle.js:73 Repopulating tabs with:  []
studioBundle.js:73 Added projectId to sessions table keyPath
studioBundle.js:73 Repopulating sessions with:  []
studioBundle.js:73 Added projectId to scripts table keyPath
studioBundle.js:73 Repopulating scripts with:  []
studioBundle.js:73 Added projectId to models table keyPath
studioBundle.js:73 Repopulating models with:  []
studioBundle.js:73 Added projectId to fields table keyPath
studioBundle.js:73 Repopulating fields with:  []
studioBundle.js:73 Added projectId to enums table keyPath
studioBundle.js:73 Repopulating enums with:  []
studioBundle.js:73 Created actions table
studioBundle.js:73 ---Migrated to v6---
studioBundle.js:73 ------IndexedDB migration complete------
studioBundle.js:73 Project load failed:  {message: "Cannot destructure property `dmmf` of 'undefined' or 'null'.", stack: "TypeError: Cannot destructure property `dmmf` of '…ode_modules\prisma2\build\photon-worker.js:39:31)"}
```

**Comment by madebysid** [comment]
@AcerFeng Okay this is actually good, this is an issue we know happens on Windows and was fixed yesterday. The next release (which will happen soon) will address this. Will let you know when it is out so you can retry. Thanks for the detailed stacktraces!

**Comment by madebysid** [comment]
@AcerFeng The release is out. `prisma2@preview017.2` should fix this error, can you try again?

**Comment by AcerFeng** [comment]
@madebysid That appears to have fixed it. Thank you!
