### ISSUE TITLE
Invalid provider for `prisma2 studio` leads to error message with "Photon"

### ISSUE THREAD

**Issue by janpio** [prisma/studio#340]
2.0.0-alpha.762, when you have an invalid `provider` in you schema:

```
C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood>npx prisma2 studio --experimental
Failed to generate Photon client: Error: Schema parsing
error: Datasource provider not known: "redwood".
  -->  schema.prisma:9
   | 
 8 | datasource db {
 9 |   provider = "redwood"
   | 

Validation Error Count: 1
    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood\node_modules\prisma2\build\index.js:2:2166778)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Jan\Documents\throwaway\prisma2-provider-redwood\node_modules\prisma2\build\index.js:2:2163038)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

```

Problem is that it mentions Photon, not Prisma Client.

**Comment by madebysid** [comment]
Fixed! Will be out with the next alpha.
