### ISSUE TITLE
Update data : Expected object to have exactly 1 key-value pairs, got: 2

### ISSUE THREAD

**Issue by guillaumeLamanda** [prisma/studio#388]
1. Prisma2 version (`prisma2 -v`): `preview024`

2. Logs from Developer Tools Console, if any:
```
Sending request to prisma client:  prisma.user.update(
{
  "where": {
    "id": "ck0k6qzf4043d07123nkvkl6r",
    "email": "guillaume.lamanda@gmail.com"
  },
  "data": {
    "grade": "GOLD"
  },
  "select": {
    "id": true,
    "email": true,
    "grade": true
  }
}
)
```
```
Error: 
Invalid `prisma.user.update()` invocation:

Failed to validate the query `Error occurred during query validation & transformation:
Assertion error: Expected object to have exactly 1 key-value pairs, got: 2 (email, id).` at ``
```

```
Error in Prisma Client request:

Error:
Invalid `prisma.user.update()` invocation:

Failed to validate the query `Error occurred during query validation & transformation:
Assertion error: Expected object to have exactly 1 key-value pairs, got: 2 (email, id).` at ``
at PrismaClientFetcher.request (/Users/guillaumelamanda/.cache/prisma/studio/Users-project/runtime/index.js:1:47358)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes

4. Prisma2 schema (if relevant):
```
model User {
  id           String   @default(cuid()) @id
  email        String   @unique
  name         String
  phone        String?
  verified     Boolean
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}
```

I, I think I am facing a bug in the studio.  

It seem the studio is using all unique fields for the `where` input of the client update request.  
I have **not**  created an unique filed like `@@unique([firstName, lastName])` so only the id should be present.  

Thank's for your work here 😊

**Comment by guillaumeLamanda** [comment]
Ok, it seem I have duplicate #386 . I'm closing this one.
