### ISSUE TITLE
Studio fails to launch (Get Config Error)

### ISSUE THREAD

**Issue by sachaw** [prisma/studio#391]
Both prisma2@2.0.0-preview024 and prisma2@2.0.0-alpha.942
```
Failed to generate Prisma Client: Error: Get config error: Found argument '/home/sachaw/api/prisma/schema.prisma' which wasn't expected, or isn't valid in this context

USAGE:
    query-engine-debian-openssl-1.1.x cli get-config

For more information try --help
    at Object.<anonymous> (/home/sachaw/.config/yarn/global/node_modules/prisma2/build/index.js:2:2407632)
    at Generator.throw (<anonymous>)
    at rejected (/home/sachaw/.config/yarn/global/node_modules/prisma2/build/index.js:2:2402100)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by madebysid** [comment]
Hey @sachaw, there was a tiny breaking change internally, you happened to catch it at the right (wrong) time! :D
I've just pushed out 2.0.0-alpha.959 that should fix for this!
