### ISSUE TITLE
One to many relation, relation field is shown as data column

### ISSUE THREAD

**Issue by unlight** [prisma/studio#398]
Example from the docs about One-to-many relations
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#one-to-many-relations

When I'm trying to add record for `Post` I see two columns `author` and `authorId`

When I selecting author from modal popup (and filling author id) I got error (see details)

I'm expecting that `authorId` should not shown or be readonly and filled automatically when I selects author.

![image](https://user-images.githubusercontent.com/301732/78452876-26bcb380-769f-11ea-8079-6a4acd51ad47.png)

Details (in my case tables named differently User and Article):
<details>
```
Error in request:  {
  telemetry: true,
  message: '\n' +
    '\u001b[31mInvalid \u001b[1m`prisma.article.create()`\u001b[22m invocation:\u001b[39m\n' +
    '\n' +
    '\n' +
    '\u001b[31mInvalid \u001b[1m`prisma.article.create()`\u001b[22m invocation:\u001b[39m\n' +
    '\n' +
    '{\n' +
    '  data: {\n' +
    "    slug: \u001b[2m'xxx'\u001b[22m\u001b[2m,\u001b[22m\n" +
    "\u001b[2m\u001b[22m    title: \u001b[2m'xxx'\u001b[22m\u001b[2m,\u001b[22m\n" +
    "\u001b[2m\u001b[22m    description: \u001b[2m''\u001b[22m\u001b[2m,\u001b[22m\n" +
    "\u001b[2m\u001b[22m    body: \u001b[2m''\u001b[22m\u001b[2m,\u001b[22m\n" +
    "\u001b[2m\u001b[22m    updatedAt: \u001b[2m'1970-01-01T00:00:00.000Z'\u001b[22m\u001b[2m,\u001b[22m\n" +
    '\u001b[2m\u001b[22m    favoritesCount: \u001b[2m0\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    author: {\n' +
    '      connect: {\n' +
    "        id: \u001b[2m'ck8loq20700001wwz2iw3j4bf'\u001b[22m\u001b[2m\u001b[22m\n" +
    '\u001b[2m\u001b[22m      }\u001b[2m\u001b[22m\n' +
    '\u001b[2m\u001b[22m    }\u001b[2m,\u001b[22m\n' +
    "\u001b[2m\u001b[22m    \u001b[91mauthorId\u001b[39m: \u001b[2m''\u001b[22m\u001b[2m\u001b[22m\n" +
    '    \u001b[91m~~~~~~~~\u001b[39m\n' +
    '\u001b[2m\u001b[22m  }\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m  select: {\n' +
    '    id: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    slug: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    title: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    description: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    body: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    tags: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    createdAt: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    updatedAt: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    favoritesCount: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    author: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    authorId: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    favoritedBy: \u001b[2mtrue\u001b[22m\u001b[2m\u001b[22m\n' +
    '\u001b[2m\u001b[22m  }\u001b[2m\u001b[22m\n' +
    '\u001b[2m\u001b[22m}\n' +
    '\n' +
    'Unknown arg \u001b[91m`authorId`\u001b[39m in \u001b[1mdata.authorId\u001b[22m for type \u001b[1mArticleCreateInput\u001b[22m. Did you mean `\u001b[92mauthor\u001b[39m`? \u001b[2mAvailable args:\u001b[22m\n' +
    '\u001b[2mtype\u001b[22m \u001b[1m\u001b[2mArticleCreateInput\u001b[22m\u001b[22m \u001b[2m{\u001b[22m\n' +
    '  \u001b[2m\u001b[32mid\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m\n' +
    '  \u001b[32mslug\u001b[39m: \u001b[37mString\u001b[39m\n' +
    '  \u001b[32mtitle\u001b[39m: \u001b[37mString\u001b[39m\n' +
    '  \u001b[32mdescription\u001b[39m: \u001b[37mString\u001b[39m\n' +
    '  \u001b[32mbody\u001b[39m: \u001b[37mString\u001b[39m\n' +
    '  \u001b[2m\u001b[32mcreatedAt\u001b[39m?: \u001b[37mDateTime\u001b[39m\u001b[22m\n' +
    '  \u001b[2m\u001b[32mupdatedAt\u001b[39m?: \u001b[37mDateTime\u001b[39m\u001b[22m\n' +
    '  \u001b[2m\u001b[32mfavoritesCount\u001b[39m?: \u001b[37mInt\u001b[39m\u001b[22m\n' +
    '  \u001b[2m\u001b[32mtags\u001b[39m?: \u001b[37mTagCreateManyWithoutArticlesInput\u001b[39m\u001b[22m\n' +
    '  \u001b[32mauthor\u001b[39m: \u001b[37mUserCreateOneWithoutArticlesInput\u001b[39m\n' +
    '  \u001b[2m\u001b[32mfavoritedBy\u001b[39m?: \u001b[37mUserCreateManyWithoutFavoriteArticlesInput\u001b[39m\u001b[22m\n' +
    '\u001b[2m}\u001b[22m\n' +
    '\n',
  stack: 'Error: \n' +
    '\u001b[31mInvalid \u001b[1m`prisma.article.create()`\u001b[22m invocation:\u001b[39m\n' +
    '\n' +
    '\n' +
    '\u001b[31mInvalid \u001b[1m`prisma.article.create()`\u001b[22m invocation:\u001b[39m\n' +
    '\n' +
    '{\n' +
    '  data: {\n' +
    "    slug: \u001b[2m'xxx'\u001b[22m\u001b[2m,\u001b[22m\n" +
    "\u001b[2m\u001b[22m    title: \u001b[2m'xxx'\u001b[22m\u001b[2m,\u001b[22m\n" +
    "\u001b[2m\u001b[22m    description: \u001b[2m''\u001b[22m\u001b[2m,\u001b[22m\n" +
    "\u001b[2m\u001b[22m    body: \u001b[2m''\u001b[22m\u001b[2m,\u001b[22m\n" +
    "\u001b[2m\u001b[22m    updatedAt: \u001b[2m'1970-01-01T00:00:00.000Z'\u001b[22m\u001b[2m,\u001b[22m\n" +
    '\u001b[2m\u001b[22m    favoritesCount: \u001b[2m0\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    author: {\n' +
    '      connect: {\n' +
    "        id: \u001b[2m'ck8loq20700001wwz2iw3j4bf'\u001b[22m\u001b[2m\u001b[22m\n" +
    '\u001b[2m\u001b[22m      }\u001b[2m\u001b[22m\n' +
    '\u001b[2m\u001b[22m    }\u001b[2m,\u001b[22m\n' +
    "\u001b[2m\u001b[22m    \u001b[91mauthorId\u001b[39m: \u001b[2m''\u001b[22m\u001b[2m\u001b[22m\n" +
    '    \u001b[91m~~~~~~~~\u001b[39m\n' +
    '\u001b[2m\u001b[22m  }\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m  select: {\n' +
    '    id: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    slug: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    title: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    description: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    body: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    tags: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    createdAt: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    updatedAt: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    favoritesCount: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    author: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    authorId: \u001b[2mtrue\u001b[22m\u001b[2m,\u001b[22m\n' +
    '\u001b[2m\u001b[22m    favoritedBy: \u001b[2mtrue\u001b[22m\u001b[2m\u001b[22m\n' +
    '\u001b[2m\u001b[22m  }\u001b[2m\u001b[22m\n' +
    '\u001b[2m\u001b[22m}\n' +
    '\n' +
    'Unknown arg \u001b[91m`authorId`\u001b[39m in \u001b[1mdata.authorId\u001b[22m for type \u001b[1mArticleCreateInput\u001b[22m. Did you mean `\u001b[92mauthor\u001b[39m`? \u001b[2mAvailable args:\u001b[22m\n' +
    '\u001b[2mtype\u001b[22m \u001b[1m\u001b[2mArticleCreateInput\u001b[22m\u001b[22m \u001b[2m{\u001b[22m\n' +
    '  \u001b[2m\u001b[32mid\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m\n' +
    '  \u001b[32mslug\u001b[39m: \u001b[37mString\u001b[39m\n' +
    '  \u001b[32mtitle\u001b[39m: \u001b[37mString\u001b[39m\n' +
    '  \u001b[32mdescription\u001b[39m: \u001b[37mString\u001b[39m\n' +
    '  \u001b[32mbody\u001b[39m: \u001b[37mString\u001b[39m\n' +
    '  \u001b[2m\u001b[32mcreatedAt\u001b[39m?: \u001b[37mDateTime\u001b[39m\u001b[22m\n' +
    '  \u001b[2m\u001b[32mupdatedAt\u001b[39m?: \u001b[37mDateTime\u001b[39m\u001b[22m\n' +
    '  \u001b[2m\u001b[32mfavoritesCount\u001b[39m?: \u001b[37mInt\u001b[39m\u001b[22m\n' +
    '  \u001b[2m\u001b[32mtags\u001b[39m?: \u001b[37mTagCreateManyWithoutArticlesInput\u001b[39m\u001b[22m\n' +
    '  \u001b[32mauthor\u001b[39m: \u001b[37mUserCreateOneWithoutArticlesInput\u001b[39m\n' +
    '  \u001b[2m\u001b[32mfavoritedBy\u001b[39m?: \u001b[37mUserCreateManyWithoutFavoriteArticlesInput\u001b[39m\u001b[22m\n' +
    '\u001b[2m}\u001b[22m\n' +
    '\n' +
    '\n' +
    '    at Object.stack [as Article] (c:\\Users\\s9163\\AppData\\Roaming\\Prisma\\Studio\\-Dev-nestjs-graphql-prisma-realworld-example-app\\src\\runtime\\getPrismaClient.ts:377:40)\n' +
    '    at Object.name [as create] (c:\\Users\\s9163\\AppData\\Roaming\\Prisma\\Studio\\-Dev-nestjs-graphql-prisma-realworld-example-app\\src\\runtime\\getPrismaClient.ts:501:19)\n' +
    '    at eval (eval at Photon.request (c:\\Dev\\nestjs-graphql-prisma-realworld-example-app\\node_modules\\@prisma\\cli\\build\\index.js:2:729562), <anonymous>:3:53)\n' +
    '    at Photon.request (c:\\Dev\\nestjs-graphql-prisma-realworld-example-app\\node_modules\\@prisma\\cli\\build\\index.js:2:729751)\n' +
    '    at PhotonService.respond (c:\\Dev\\nestjs-graphql-prisma-realworld-example-app\\node_modules\\@prisma\\cli\\build\\index.js:2:2746654)\n' +
    '    at WebSocket.StudioServer.onWSMessage (c:\\Dev\\nestjs-graphql-prisma-realworld-example-app\\node_modules\\@prisma\\cli\\build\\index.js:2:1666064)\n' +
    '    at WebSocket.emit (events.js:315:20)\n' +
    '    at WebSocket.EventEmitter.emit (domain.js:485:12)\n' +
    '    at Receiver.receiverOnMessage (c:\\Dev\\nestjs-graphql-prisma-realworld-example-app\\node_modules\\@prisma\\cli\\build\\index.js:2:2432056)\n' +
    '    at Receiver.emit (events.js:315:20)',
  isPanic: undefined,
  code: undefined
} {
  query: 'prisma.article.create(\n' +
    '{\n' +
    '  "data": {\n' +
    '    "slug": "xxx",\n' +
    '    "title": "xxx",\n' +
    '    "description": "",\n' +
    '    "body": "",\n' +
    '    "updatedAt": "1970-01-01T00:00:00.000Z",\n' +
    '    "favoritesCount": 0,\n' +
    '    "author": {\n' +
    '      "connect": {\n' +
    '        "id": "ck8loq20700001wwz2iw3j4bf"\n' +
    '      }\n' +
    '    },\n' +
    '    "authorId": ""\n' +
    '  },\n' +
    '  "select": {\n' +
    '    "id": true,\n' +
    '    "slug": true,\n' +
    '    "title": true,\n' +
    '    "description": true,\n' +
    '    "body": true,\n' +
    '    "tags": true,\n' +
    '    "createdAt": true,\n' +
    '    "updatedAt": true,\n' +
    '    "favoritesCount": true,\n' +
    '    "author": true,\n' +
    '    "authorId": true,\n' +
    '    "favoritedBy": true\n' +
    '  }\n' +
    '}\n' +
    ')'
}
```
</details>

1. Prisma2 version (`prisma2 -v`):
```
@prisma/cli          : 2.0.0-beta.1
Current platform     : windows
Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at c:\Dev\nestjs-graphql-prisma-realworld-example-app\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at c:\Dev\nestjs-graphql-prisma-realworld-example-app\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at c:\Dev\nestjs-graphql-prisma-realworld-example-app\node_modules\@prisma\cli\introspection-engine-windows.exe)
```
2. Logs from Developer Tools Console, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?

4. Prisma2 schema (if relevant):
```
model User {
   id  String  @id  @default(cuid())
}

model Article {
   id  String  @id  @default(cuid())
    author    User  @relation(name: "ArticleAuthor", fields: [authorId], references: [id])
    authorId  String
}
```

**Comment by unlight** [comment]
No errors in prisma@beta.2
