### ISSUE TITLE
Studio failing with provided model

### ISSUE THREAD

**Issue by sachaw** [prisma/studio#400]
prisma 2.0.0-alpha.1031 windows

When creating a user with the provided schema the following error appears for all models sharing a relationship with the user model

```
Invalid `prisma.user.findMany()` invocation:

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "syntax error at or near \")\"", detail: None, hint: None, position: Some(Original(187)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("scan.l"), line: Some(1150), routine: Some("scanner_yyerror") }) }) })
    at PrismaClientFetcher.request (C:\Users\sacha\AppData\Roaming\Prisma\Studio\-Users-sacha-api\runtime\index.js:1:52176)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Obviously `syntax error at or near \")\` isn't very helpful, so let me know what else you need. My only guess is that it's failing to parse the db connection part.

The user only has `name` and `username` fields set on creation

schema:
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id                    String   @default(cuid()) @id
  activated             Boolean  @default(false)
  activationClaim       String   @default(cuid()) @unique
  username              String   @unique
  name                  String
  avatar                String   @default("data:image/png;base64,iVBORw0KGgAASUVORK5CYII=")
  password              String?
  createdAt             DateTime @default(now())
	updatedAt             DateTime @updatedAt
  groups                Group[]
  tokens                Token[]
  actions               UserAction[]
  linkedAccounts        LinkedAccount[]
  credentials           UserCredential[]
}

model UserCredential {
  id                    String   @id
  revoked               Boolean  @default(false)
  publicKey             String
  lastUsed              DateTime?
  fidoAAGUID            String
  createdAt             DateTime @default(now())
	updatedAt             DateTime @updatedAt
  associatedTokens      Token[]
  user                  User
}

model authChallenge {
  id                    String   @default(cuid()) @id
  challenge             String   @unique
  expires               DateTime
}

model Group {
  id                    String   @default(cuid()) @id
  name                  String   @unique
  createdAt             DateTime @default(now())
	updatedAt             DateTime @updatedAt
  users                 User[]
}

model Token {
  id                    String   @id
  revoked               Boolean  @default(false)
  lastIp                String?
  lastUserAgent         String?
  createdAt             DateTime @default(now())
	updatedAt             DateTime @updatedAt
  UserActions           UserAction[]
  userCredential        UserCredential?
  user                  User?
}

model Weather {
  id                    String   @default(autoincrement()) @id
  indoorTemperature     Float
  indoorHumidity        Int
  outdoorTemperature    Float
  outdoorHumidity       Int
  windDirection         Int
  windSpeed             Float
  windGustSpeed         Float
  rain                  Float
  solarRadiation        Float
  barometricPressure    Float
  time                  DateTime
  createdAt             DateTime @default(now())
	updatedAt             DateTime @updatedAt
}

model RssFeed {
  id                    String   @default(cuid()) @id
  name                  String
  url                   String
  matchRegex            String
  createdAt             DateTime @default(now())
	updatedAt             DateTime @updatedAt
  subscriptions         SeasonalAnimeSubscription[]

}

model SeasonalAnimeSubscription {
  id                    String   @default(cuid()) @id
  anilistId             Int      @unique
  latestEpisode         Int      @default(0)
  episodeOffset         Int      @default(0)
  matchTitle            String
  createdAt             DateTime @default(now())
	updatedAt             DateTime @updatedAt
  feed                  RssFeed
}

enum LinkableService {
  ANILIST
  PLEX
}

model LinkedAccount {
  id                    String          @default(cuid()) @id
  service               LinkableService
  accountId             String          @unique
  accessToken           String
  accessTokenExpires    DateTime?
  refreshToken          String?
  createdAt             DateTime        @default(now())
	updatedAt             DateTime        @updatedAt
  user                  User
}

model UserAction {
  id                    String   @default(cuid()) @id
  action                String
  ip                    String
  createdAt             DateTime @default(now())
	updatedAt             DateTime @updatedAt
  associatedToken       Token
  user                  User
}
```

**Comment by madebysid** [comment]
@sachaw Could you perhaps elaborate what fixed this? At first glance, this looks like a script generation error from Studio, so I'm curious as to how ithis was resolved :D

**Comment by sachaw** [comment]
I believe that I had accidentally updated to prisma beta from preview 25 which meant my schema was invalid, I rewrote it with the required fixes and it worked, this may not have been the cause of the issue but is what fixed for me.

**Comment by madebysid** [comment]
Ah understood!
