### ISSUE TITLE
Cannot read property 'padEnd' of undefined

### ISSUE THREAD

**Issue by abhishiv** [prisma/studio#425]
1. Prisma2 version (`prisma -v`):
2.0.0
2. Logs from Developer Tools Console, if any:
```
Error in request:  {
  telemetry: true,
  message: "Cannot read property 'padEnd' of undefined",
  stack: "TypeError: Cannot read property 'padEnd' of undefined\n" +
    '    at Object.getErrorMessageWithLink (/Users/abhishiv/.cache/prisma/studio/Users-abhishiv-work-gratico-grati.co/runtime/index.js:1:64301)\n' +
    '    at NodeEngine.handleRequestError (/Users/abhishiv/.cache/prisma/studio/Users-abhishiv-work-gratico-grati.co/runtime/index.js:1:80549)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
    '    at async PrismaClientFetcher.request (/Users/abhishiv/.cache/prisma/studio/Users-abhishiv-work-gratico-grati.co/runtime/index.js:1:148638)\n' +
    '    at async Promise.all (index 60)\n' +
    '    at async eval (eval at Photon.request (/Users/abhishiv/work/gratico/grati.co/node_modules/@prisma/cli/build/index.js:2:778638), <anonymous>:5:32)\n' +
    '    at async Photon.request (/Users/abhishiv/work/gratico/grati.co/node_modules/@prisma/cli/build/index.js:2:778632)\n' +
    '    at async PhotonService.respond (/Users/abhishiv/work/gratico/grati.co/node_modules/@prisma/cli/build/index.js:2:2402575)\n' +
    '    at async WebSocket.StudioServer.onWSMessage (/Users/abhishiv/work/gratico/grati.co/node_modules/@prisma/cli/build/index.js:2:1733647)',
  isPanic: undefined,
  code: undefined
} {
  query: 'Promise.all([\n' +
    '    prisma.access.count(),\n' +
    '    prisma.access_token.count(),\n' +
    '    prisma.action.count(),\n' +
    '    prisma.attachment.count(),\n' +
    '    prisma.collaboration.count(),\n' +
    '    prisma.comment.count(),\n' +
    '    prisma.commit_status.count(),\n' +
    '    prisma.deleted_branch.count(),\n' +
    '    prisma.deploy_key.count(),\n' +
    '    prisma.email_address.count(),\n' +
    '    prisma.external_login_user.count(),\n' +
    '    prisma.follow.count(),\n' +
    '    prisma.gpg_key.count(),\n' +
    '    prisma.gpg_key_import.count(),\n' +
    '    prisma.hook_task.count(),\n' +
    '    prisma.issue.count(),\n' +
    '    prisma.issue_assignees.count(),\n' +
    '    prisma.issue_dependency.count(),\n' +
    '    prisma.issue_label.count(),\n' +
    '    prisma.issue_user.count(),\n' +
    '    prisma.issue_watch.count(),\n' +
    '    prisma.label.count(),\n' +
    '    prisma.lfs_lock.count(),\n' +
    '    prisma.lfs_meta_object.count(),\n' +
    '    prisma.login_source.count(),\n' +
    '    prisma.milestone.count(),\n' +
    '    prisma.mirror.count(),\n' +
    '    prisma.notice.count(),\n' +
    '    prisma.notification.count(),\n' +
    '    prisma.oauth2_application.count(),\n' +
    '    prisma.oauth2_authorization_code.count(),\n' +
    '    prisma.oauth2_grant.count(),\n' +
    '    prisma.oauth2_session.count(),\n' +
    '    prisma.org_user.count(),\n' +
    '    prisma.protected_branch.count(),\n' +
    '    prisma.public_key.count(),\n' +
    '    prisma.pull_request.count(),\n' +
    '    prisma.reaction.count(),\n' +
    '    prisma.release.count(),\n' +
    '    prisma.repo_indexer_status.count(),\n' +
    '    prisma.repo_redirect.count(),\n' +
    '    prisma.repository.count(),\n' +
    '    prisma.repo_topic.count(),\n' +
    '    prisma.repo_unit.count(),\n' +
    '    prisma.review.count(),\n' +
    '    prisma.star.count(),\n' +
    '    prisma.stopwatch.count(),\n' +
    '    prisma.team.count(),\n' +
    '    prisma.team_repo.count(),\n' +
    '    prisma.team_unit.count(),\n' +
    '    prisma.team_user.count(),\n' +
    '    prisma.topic.count(),\n' +
    '    prisma.tracked_time.count(),\n' +
    '    prisma.two_factor.count(),\n' +
    '    prisma.u2f_registration.count(),\n' +
    '    prisma.upload.count(),\n' +
    '    prisma.user.count(),\n' +
    '    prisma.user_open_id.count(),\n' +
    '    prisma.version.count(),\n' +
    '    prisma.watch.count(),\n' +
    '    prisma.webhook.count(),\n' +
    '])'
}
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@alpha`)

4. Prisma2 schema (if relevant):
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

RDS db btw

**Comment by madebysid** [comment]
Hey @abhishiv, thanksfor reporting! Did this happen right as you open Studio, or did something you do trigger it?

**Comment by madebysid** [comment]
Hey @abhishiv! I've been unable to reproduce this still.
The error seems to be originating from Prisma Client, so could you do me a favor and try running the failing query in a standalone script?

In your case, this is what that script might look like:

```

**Comment by Ruixel** [comment]
Hello, I've also had this error show up when trying to access one of my tables in Prisma Studio. Turns out it was because I had invalid data in my table. I was using MySQL 5.7 and my table had invalid DateTime values of 0000-00-00 00:00:00, so to recreate it you can force these values into a table, though you may need to enable zero in dates in the mysql config.

When trying to use the client and invoke a findMany() it would return a sensible error of "PANIC: invalid or out-of-range date", however Prisma Studio would just state "Cannot read property 'padEnd' of undefined". Hope this helps.

**Comment by madebysid** [comment]
Hey @Ruixel , thanks for the repro! I’ll give this a shot and see if I can improve Studio’s error message!
