### ISSUE TITLE
[feature request] display relation target in Studio

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#469]
## Use case

Once we’ll use Prisma Studio in production, we’ll be needing to skim through lots of records on our end to manually modify data, using Studio.

In doing so, we’ll often need to verify which record is related to another. **Would it be possible to have some kind of indicator in the relations field to see (without needing to click through) which other record a record is connected to?**

## Concept

For example:
<img width="1059" alt="idea" src="https://user-images.githubusercontent.com/11673745/87214360-92d33700-c2e0-11ea-938a-5c2681ddea90.png">

**Comment by madebysid** [comment]
@heymartinadams Interesting. Currently, there's kinda a way: Since relations are built using scalar fields, you should be able to see the ID of that scalar somewhere on your table.

For example, for this schema:
```
model Post {
  authorId  Int
  author  Post  @relation(fields: [authorId], references: [id])
}
```

you'll be able to see which `author` you are connected to by looking at the `authorId` field in the Post table.

Let me know if that doesn't make sense 😅

**Comment by heymartinadams** [comment]
Great! Tried it just now, though, but ran into an error in Studio:

```js
Error in request:  {
  telemetry: true,
  message: "Cannot read property 'padEnd' of undefined",
  stack: "TypeError: Cannot read property 'padEnd' of undefined\n" +
    '    at Object.getErrorMessageWithLink (/Users/__USER__/.cache/prisma/studio/.../runtime/index.js:1:95985)\n' +
    '    at NodeEngine.handleRequestError (/Users/__USER__/.cache/prisma/studio/.../runtime/index.js:1:116883)\n' +
    '    at async PrismaClientFetcher._request (/Users/__USER__/.cache/prisma/studio/.../runtime/index.js:1:212706)',
  isPanic: undefined,
  code: undefined
} {
  query: 'prisma.eventImage.findMany({\n' +
    '  take: 100,\n' +
    '  skip: 0,\n' +
    '  select: {\n' +
    '    id: true,\n' +
    '    createdAt: true,\n' +
    '    updatedAt: true,\n' +
    '    eventProgram: true,\n' +
    '    name: true,\n' +
    '    description: true,\n' +
    '    sortOrder: true,\n' +
    '    url: true,\n' +
    '    refEventProgram: true,\n' +
    '  }\n' +
    '})'
}
```

Changed it from this:
```prisma
model EventImage {
...
  // Relations
  eventProgram    EventProgram @relation("REventImagesToREventProgram", fields: [refEventProgram])
  // Fields
...
  // Refs
  refEventProgram String
}
```

to this:
```prisma
model EventImage {
...
  // Relations
  eventProgram    EventProgram @relation("REventImagesToREventProgram", fields: [refEventProgram], references: [eventProgramId])
  // Fields
...
  // Refs
  refEventProgram String
}
```

## EventProgram model for reference
```prisma
model EventProgram {
...
  // Relations
...
  eventImages            EventImage[] @relation("REventImagesToREventProgram")
  // Fields
...
  eventProgramId         String       @unique
...
}
```

**Comment by heymartinadams** [comment]
Figured out how to do it, but it involved me deleting the development database and creating a new one, since I couldn’t figure out how to change an existing relation reference from `id` to another unique field such as `eventProgramId` (since `id` doesn’t provide any visual clues).

This is how it looks now:
![image](https://user-images.githubusercontent.com/11673745/87231861-75997980-c36f-11ea-8be2-5b1dc7218413.png)

**Comment by heymartinadams** [comment]
Reopening in case you find value in addressing how users might be able to change the relation reference field, @madebysid. Feel free to close if not critical, on future roadmap, etc.

**Comment by madebysid** [comment]
@heymartinadams Ah yeah, let's keep this open for now, the workflow isn't ideal IMO.

About the issue you saw:

> Cannot read property 'padEnd' of undefined"

This was reported a while ago, it seems to originate from Prisma Client. As far as I know, that should be fixed on the latest `dev` release, so if you see it again, please do let me know!

**Comment by mc-spieczynski** [comment]
Would it be possible to have a configuration setting for Prisma Studio either in external config file or in schema (not a good idea IMO) to set a `displayValue` param for a field? Ex. for a relationshipt with `displayValue` could be computed or set to [relatedTable.name/title/etc.] ?

**Comment by petradonka** [comment]
That sounds like an approach we could take when we pick up this improvement. The schema might be a good place to specify this, e.g. something along the lines of:

```
model Book {
   ...
   author User @relation(fields: [authorId], references: [id], display: [name])
}
```

We have this on our long-term roadmap.

**Comment by igalklebanov** [comment]
Hey :wave:

Prisma ORM 7 introduces a brand new standalone [Studio](https://www.prisma.io/docs/orm/tools/prisma-studio), built from the ground up to work everywhere, with or without Prisma ORM. Consequently, all "old Studio" issues are being closed as there won't be any further work on it. :mega:

The new Studio is also available in the Prisma VS Code extension and in the Prisma Console application. :electric_plug:

Help shape, improve and fix the new Studio with us in this repository by submitting bug reports and feature requests. :construction_worker:
