### ISSUE TITLE
Wrong database url leads to error

### ISSUE THREAD

**Issue by janpio** [prisma/studio#493]
![image](https://user-images.githubusercontent.com/183673/90341053-87b8a880-dffc-11ea-8bcc-8dc2eb690fd3.png)

```
λ prisma studio --experimental                                                                                                                                      
Generating Prisma Client ... done                                                                                                                                   
Studio started at http://localhost:5555                                                                                                                             
Error in request:  PrismaClientKnownRequestError: Database `benchmark` does not exist on the database server at `localhost:3306`.                                   
    at PrismaClientFetcher.request (C:\Users\Jan\AppData\Roaming\Prisma\Studio\-Users-Jan-Documents-throwaway-prisma-client-js-benchmarks\runtime\index.js:1:222904)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {                                                                                           
  code: 'P1003',                                                                                                                                                    
  meta: {                                                                                                                                                           
    database_name: 'benchmark',                                                                                                                                     
    database_host: 'localhost',                                                                                                                                     
    database_port: 3306                                                                                                                                             
  }                                                                                                                                                                 
} {                                                                                                                                                                 
  query: 'Promise.all([\n' +                                                                                                                                        
    '    prisma.comment.count(),\n' +                                                                                                                               
    '    prisma.like.count(),\n' +                                                                                                                                  
    '    prisma.post.count(),\n' +                                                                                                                                  
    '    prisma.user.count(),\n' +                                                                                                                                  
    '    prisma.friendShip.count(),\n' +                                                                                                                            
    '])'                                                                                                                                                            
}                                                                                                                                                                   
```

Should probably be handled as a known error.

**Comment by madebysid** [comment]
This sounds like a better thing to do instead: #533
It'll get rid of a few other possible issues like this, so I'm closing in favour of #533
