### ISSUE TITLE
Client generation error message differs from normal `generate`

### ISSUE THREAD

**Issue by janpio** [prisma/studio#501]
```
C:\Users\Jan\Documents\throwaway
λ prisma studio --experimental
Generating Prisma Client ... Failed to generate Prisma Client: Error: Get config {"is_panic":false,"message":"error: Error validating: You defined no datasource. You must define exactly one datasource.\n
-->  schema.prisma:1\n   | \n   | \n 1 | model model {\r\n   | \n\nValidation Error Count: 1","meta":{"full_error":"error: Error validating: You defined no datasource. You must define exactly one datasource.\n  -->  schema.prisma:1\n   | \n   | \n 1 | model model {\r\n   | \n\nValidation Error Count: 1"},"error_code":"P1012"}
    at Object.<anonymous> (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\build\index.js:2:1365941)
    at Generator.throw (<anonymous>)
    at rejected (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\build\index.js:2:1361665)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
Error: Cannot destructure property `dmmf` of 'undefined' or 'null'.

C:\Users\Jan\Documents\throwaway
λ prisma generate
Error: P1012

Get config
error: Error validating: You defined no datasource. You must define exactly one datasource.
  -->  schema.prisma:1
   |
   |
 1 | model model {
   |

Validation Error Count: 1


C:\Users\Jan\Documents\throwaway
λ cat schema.prisma
model model {
  col Int? @id
}
C:\Users\Jan\Documents\throwaway
λ prisma -v
@prisma/cli          : 2.5.0
Current platform     : windows
Query Engine         : query-engine 9a670138b1db276001d785a2adcba1584c869d24 (at ..\..\..\..\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 9a670138b1db276001d785a2adcba1584c869d24 (at ..\..\..\..\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 9a670138b1db276001d785a2adcba1584c869d24 (at ..\..\..\..\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 9a670138b1db276001d785a2adcba1584c869d24 (at ..\..\..\..\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\prisma-fmt-windows.exe)
Studio               : 0.259.0
```

![image](https://user-images.githubusercontent.com/183673/90793128-a3c58e00-e30b-11ea-8f3c-d869b9efb1ad.png)

**Comment by madebysid** [comment]
@janpio This should also be addressed with `2.7.0-dev.60`.
1. You should not see the error JSON
2. You should see the prettified Prisma Client error
3. You should not see `cannot destructure ...`

Try it?

**Comment by janpio** [comment]
Can not confirm unfortunately:

```
C:\Users\Jan\Documents\throwaway\studio_501>npm install @prisma/cli@dev

> @prisma/cli@2.7.0-dev.60 preinstall C:\Users\Jan\Documents\node_modules\@prisma\cli
> node preinstall/index.js


> @prisma/cli@2.7.0-dev.60 install C:\Users\Jan\Documents\node_modules\@prisma\cli
> node download-build/index.js

npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Jan\Documents\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Jan\Documents\package.json'
npm WARN Documents No description
npm WARN Documents No repository field.
npm WARN Documents No README data
npm WARN Documents No license field.

+ @prisma/cli@2.7.0-dev.60
updated 1 package and audited 546 packages in 2.797s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Jan\Documents\throwaway\studio_501>npx prisma studio --experimental
Environment variables loaded from prisma\.env
Generating Prisma Client ...   engineCommands getDMMF failed Error: Command failed with exit code 1: C:\Users\Jan\Documents\node_modules\@prisma\cli\query-engine-windows.exe --enable-raw-queries cli dmmf
{"is_panic":false,"message":"\u001b[1;91merror\u001b[0m: \u001b[1mError validating model \"foo\": Each model must have at least one unique criteria that has only required fields. Either mark a single field with `@id`, `@unique` or add a multi field criterion with `@@id([])` or `@@unique([])` to 
the model.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:9\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m 8 | \u001b[0m\n\u001b[1;94m 9 | \u001b[0m\u001b[1;91mmodel foo {\u001b[0m\n\u001b[1;94m10 | \u001b[0m  \n\u001b[1;94m11 | \u001b[0m}\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1","meta":{"full_error":"\u001b[1;91merror\u001b[0m: \u001b[1mError validating model \"foo\": Each model must have at least one unique criteria that has only required fields. Either mark a single field with `@id`, `@unique` or add a multi field criterion with `@@id([])` or `@@unique([])` to the model.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:9\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m 8 | \u001b[0m\n\u001b[1;94m 9 | \u001b[0m\u001b[1;91mmodel foo {\u001b[0m\n\u001b[1;94m10 | \u001b[0m  \n\u001b[1;94m11 | \u001b[0m}\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1"},"error_code":"P1012"}
    at o (C:\Users\Jan\Documents\node_modules\@prisma\cli\build\index.js:2:1355421)
    at C (C:\Users\Jan\Documents\node_modules\@prisma\cli\build\index.js:2:823406)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  shortMessage: 'Command failed with exit code 1: C:\\Users\\Jan\\Documents\\node_modules\\@prisma\\cli\\query-engine-windows.exe --enable-raw-queries cli dmmf',
  command: 'C:\\Users\\Jan\\Documents\\node_modules\\@prisma\\cli\\query-engine-windows.exe --enable-raw-queries cli dmmf',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '{"is_panic":false,"message":"\\u001b[1;91merror\\u001b[0m: \\u001b[1mError validating model \\"foo\\": Each model must have at least one unique criteria that has only required fields. Either mark a single field with `@id`, `@unique` or add a multi field criterion with `@@id([])` or `@@unique([])` to the model.\\u001b[0m\\n  \\u001b[1;94m-->\\u001b[0m  \\u001b[4mschema.prisma:9\\u001b[0m\\n\\u001b[1;94m   | \\u001b[0m\\n\\u001b[1;94m 8 | \\u001b[0m\\n\\u001b[1;94m 9 | \\u001b[0m\\u001b[1;91mmodel foo {\\u001b[0m\\n\\u001b[1;94m10 | \\u001b[0m  \\n\\u001b[1;94m11 | \\u001b[0m}\\n\\u001b[1;94m   | \\u001b[0m\\n\\nValidation Error Count: 1","meta":{"full_error":"\\u001b[1;91merror\\u001b[0m: \\u001b[1mError validating model \\"foo\\": Each model must have at least one unique criteria that has only required fields. Either mark a single field with `@id`, `@unique` or add a multi field criterion with `@@id([])` or `@@unique([])` to the model.\\u001b[0m\\n  \\u001b[1;94m-->\\u001b[0m  \\u001b[4mschema.prisma:9\\u001b[0m\\n\\u001b[1;94m   | \\u001b[0m\\n\\u001b[1;94m 8 | \\u001b[0m\\n\\u001b[1;94m 9 | \\u001b[0m\\u001b[1;91mmodel foo {\\u001b[0m\\n\\u001b[1;94m10 
| \\u001b[0m  \\n\\u001b[1;94m11 | \\u001b[0m}\\n\\u001b[1;94m   | \\u001b[0m\\n\\nValidation Error Count: 1"},"error_code":"P1012"}',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +0ms
failed
An error occured while starting Studio:  Error: Schema parsing
error: Error validating model "foo": Each model must have at least one unique criteria that has only required fields. Either mark a single field with `@id`, `@unique` or add a multi field criterion with `@@id([])` or `@@unique([])` to the model.
  -->  schema.prisma:9
   | 
 8 | 
 9 | model foo {
10 | 
11 | }
   | 

Validation Error Count: 1
    at Object.<anonymous> (C:\Users\Jan\Documents\node_modules\@prisma\cli\build\index.js:2:931824)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Jan\Documents\node_modules\@prisma\cli\build\index.js:2:928399)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

```

**Comment by janpio** [comment]
In the case of no `datasource` being provided (which is what I was testing before I think), the error is now different, but does not show the validation error:

```
C:\Users\Jan\Documents\throwaway\studio_501>npx prisma studio --experimental
Environment variables loaded from prisma\.env
Generating Prisma Client ... done
An error occured while starting Studio:  TypeError: Cannot read property 'activeProvider' of undefined
    at PhotonService.init (C:\Users\Jan\Documents\node_modules\@prisma\cli\build\index.js:2:1406110)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async StudioServer.start (C:\Users\Jan\Documents\node_modules\@prisma\cli\build\index.js:2:1433205)
    at async Studio.parse (C:\Users\Jan\Documents\node_modules\@prisma\cli\build\index.js:2:1487647)
    at async main (C:\Users\Jan\Documents\node_modules\@prisma\cli\build\index.js:2:1439637)
```

Schema is:
```
generator client {
  provider = "prisma-client-js"
}

model foo {
  id Int @id
}
```

**Comment by madebysid** [comment]
Okay the `activeProvider` thing is addressed. For now, I'm handling it manually. If a `datasource` is missing, I show an error: `Could not find a `datasource` in your Prisma Schema. Please declare one, then try again. Read more about the Prisma Schema: https://pris.ly/prisma-schema`

When (if) we fail Prisma Client generation when a `datasource` is missing, that error will override mine.

About the JSON error (`{"is_panic":false,"message":"\u001b[1;91merror\u001b[0m: \u001b[1mError vali ....`), I cannot see this :/

I tried to recreate using this schema:

```
model foo {
  id     Int
}
```

But I see:

```
Error: Schema parsing
error: Error validating model "your_log": Each model must have at least one unique criteria that has only required fields. Either mark a single field with `@id`, `@unique` or add a multi field criterion with `@@id([])` or `@@unique([])` to the model.
  -->  schema.prisma:11
   |
10 |
11 | model your_log {
12 |   click_id     Int      @default(autoincrement())
13 |   click_time   DateTime
14 |   shorturl     String
15 |   referrer     String
16 |   user_agent   String
17 |   ip_address   String
18 |   country_code String
19 | }
   |
error: Error parsing attribute "@default": The `autoincrement()` default value is used on a non-indexed field even though the datasource does not support this.
  -->  schema.prisma:12
   |
11 | model your_log {
12 |   click_id     Int      @default(autoincrement())
13 |   click_time   DateTime
   |

Validation Error Count: 2
    at Object.<anonymous> (/Users/siddhant/Code/studio/packages/transports/node_modules/@prisma/sdk/dist/engineCommands.js:124:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/siddhant/Code/studio/packages/transports/node_modules/@prisma/sdk/dist/engineCommands.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

which is correct, right?

Do you happen to have the `DEBUG` flag set by any chance? That `engineCommands` thing kinda looks like a DEBUG thing.

All this is pending release BTW, it'll go out as soon as Buildkite is up again

**Comment by janpio** [comment]
`DEBUG` is not set.

**Comment by madebysid** [comment]
IIRC the DEBUG log was indeed a thing, and was fixed by Tim. The other issues in this thread were fixed by me. Can I close this now?

**Comment by janpio** [comment]
Looks good now.
