### ISSUE TITLE
Error when opening certain relations

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#530]
![error-opening-relation](https://user-images.githubusercontent.com/7689783/92369997-fff52400-f0f9-11ea-9f64-0e199ccb90e9.gif)

```
Error in request:  PrismaClientValidationError: Unknown arg `none` in where.AND.0.author.none for type UserWhereInput. Did you mean `name`?

    at Document.validate (/Users/kuldar/.cache/prisma/studio/Users-kuldar-Code-starter/runtime/index.js:1:41298)
    at NewPrismaClient._executeRequest (/Users/kuldar/.cache/prisma/studio/Users-kuldar-Code-starter/runtime/index.js:1:223986)
    at NewPrismaClient._requestWithMiddlewares (/Users/kuldar/.cache/prisma/studio/Users-kuldar-Code-starter/runtime/index.js:1:223060)
    at /Users/kuldar/.cache/prisma/studio/Users-kuldar-Code-starter/runtime/index.js:1:222972
    at /Users/kuldar/Code/starter/node_modules/@prisma/cli/build/index.js:2:1520420
    at NewPrismaClient._requestWithMiddlewares (/Users/kuldar/.cache/prisma/studio/Users-kuldar-Code-starter/runtime/index.js:1:222960)
    at /Users/kuldar/.cache/prisma/studio/Users-kuldar-Code-starter/runtime/index.js:1:222750
    at AsyncResource.runInAsyncScope (async_hooks.js:189:9)
    at NewPrismaClient._request (/Users/kuldar/.cache/prisma/studio/Users-kuldar-Code-starter/runtime/index.js:1:222725)
    at Object.then (/Users/kuldar/.cache/prisma/studio/Users-kuldar-Code-starter/runtime/index.js:1:224911) {
  query: 'prisma.post.findMany({\n' +
    '  where: {\n' +
    '    AND: [\n' +
    '      {\n' +
    '        author: { none: {"id":1} },\n' +
    '      },\n' +
    '    ]\n' +
    '  },\n' +
    '  take: 100,\n' +
    '  skip: 0,\n' +
    '  select: {\n' +
    '    id: true,\n' +
    '    title: true,\n' +
    '    content: true,\n' +
    '    published: true,\n' +
    '    author: true,\n' +
    '    authorId: true,\n' +
    '  }\n' +
    '})'
}
```

- Based on the default Quickstart javascript project's sqlite database
- [https://github.com/prisma/quickstart/tree/master/javascript/starter](https://github.com/prisma/quickstart/tree/master/javascript/starter)

**Comment by madebysid** [comment]
Was happening because the generated query was incorrect when the relation was 1-1. Fixed now.
