### ISSUE TITLE
Prisma studio crashes when trying to fill or edit a field of type enum

### ISSUE THREAD

**Issue by ahrbil** [prisma/studio#555]
1. Prisma version (`prisma -v` or `npx prisma -v`):
v2.8.0
2. Logs from Developer Tools Console or Command line, if any:
```
TypeError: t.toUpperCase is not a function
    at http://localhost:4466/studioBundle.js:395:233946
    at Array.filter (<anonymous>)
    at Proxy.forEach.fn.<computed> (http://localhost:4466/studioBundle.js:16:38493)
    at vu.getMatches (http://localhost:4466/studioBundle.js:395:233934)
    at vu.render (http://localhost:4466/studioBundle.js:395:234621)
    at _e (http://localhost:4466/studioBundle.js:16:9807)
    at http://localhost:4466/studioBundle.js:395:74880
    at le (http://localhost:4466/studioBundle.js:16:7913)
    at e.track (http://localhost:4466/studioBundle.js:16:19256)
    at vu.l [as render] (http://localhost:4466/studioBundle.js:395:74828)
    at vu.pt (http://localhost:4466/studioBundle.js:395:74976)
    at vu.t.render (http://localhost:4466/studioBundle.js:395:74214)
    at Gs (http://localhost:4466/studioBundle.js:379:69874)
    at ks (http://localhost:4466/studioBundle.js:379:69669)
    at va (http://localhost:4466/studioBundle.js:379:105468)
    at ul (http://localhost:4466/studioBundle.js:379:96715)
    at al (http://localhost:4466/studioBundle.js:379:96640)
    at Za (http://localhost:4466/studioBundle.js:379:93670)
    at http://localhost:4466/studioBundle.js:379:45312
    at t.unstable_runWithPriority (http://localhost:4466/studioBundle.js:387:3844)
    at Br (http://localhost:4466/studioBundle.js:379:45021)
    at Yr (http://localhost:4466/studioBundle.js:379:45257)
    at qr (http://localhost:4466/studioBundle.js:379:45192)
    at Ka (http://localhost:4466/studioBundle.js:379:90455)
    at Object.enqueueForceUpdate (http://localhost:4466/studioBundle.js:379:49294)
    at t.w.forceUpdate (http://localhost:4466/studioBundle.js:371:1383)
    at http://localhost:4466/studioBundle.js:387:11590
    at o (http://localhost:4466/studioBundle.js:395:56313)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
yes
4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @ahrbil, I did some investigating and turns out this is the same thing as https://github.com/prisma/studio/issues/556 so I'm closing this one, hope that's okay!
