### ISSUE TITLE
TypeError: t.toUpperCase is not a function

### ISSUE THREAD

**Issue by nickreynke** [prisma/studio#558]
1. Prisma version (`prisma -v` or `npx prisma -v`):

```
Environment variables loaded from prisma/.env
@prisma/cli          : 2.8.0
Current platform     : darwin
Query Engine         : query-engine e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.294.0
```

2. Logs from Developer Tools Console or Command line, if any:

```
TypeError: t.toUpperCase is not a function
    at http://localhost:7890/studioBundle.js:395:233946
    at Array.filter (<anonymous>)
    at Proxy.forEach.fn.<computed> (http://localhost:7890/studioBundle.js:16:38493)
    at vu.getMatches (http://localhost:7890/studioBundle.js:395:233934)
    at vu.render (http://localhost:7890/studioBundle.js:395:234621)
    at _e (http://localhost:7890/studioBundle.js:16:9807)
    at http://localhost:7890/studioBundle.js:395:74880
    at le (http://localhost:7890/studioBundle.js:16:7913)
    at e.track (http://localhost:7890/studioBundle.js:16:19256)
    at vu.l [as render] (http://localhost:7890/studioBundle.js:395:74828)
    at vu.pt (http://localhost:7890/studioBundle.js:395:74976)
    at vu.t.render (http://localhost:7890/studioBundle.js:395:74214)
    at Gs (http://localhost:7890/studioBundle.js:379:69874)
    at ks (http://localhost:7890/studioBundle.js:379:69669)
    at va (http://localhost:7890/studioBundle.js:379:105468)
    at ul (http://localhost:7890/studioBundle.js:379:96715)
    at al (http://localhost:7890/studioBundle.js:379:96640)
    at Za (http://localhost:7890/studioBundle.js:379:93670)
    at http://localhost:7890/studioBundle.js:379:45312
    at t.unstable_runWithPriority (http://localhost:7890/studioBundle.js:387:3844)
    at Br (http://localhost:7890/studioBundle.js:379:45021)
    at Yr (http://localhost:7890/studioBundle.js:379:45257)
    at qr (http://localhost:7890/studioBundle.js:379:45192)
    at Ka (http://localhost:7890/studioBundle.js:379:90455)
    at Object.enqueueForceUpdate (http://localhost:7890/studioBundle.js:379:49294)
    at t.w.forceUpdate (http://localhost:7890/studioBundle.js:371:1383)
    at http://localhost:7890/studioBundle.js:387:11590
    at o (http://localhost:7890/studioBundle.js:395:56313)
```

3. Does the issue persist even after updating to the latest `prisma` alpha?

Did `npm i @prisma/cli@dev @prisma/client@dev`. Resulted in versions `2.9.0-dev.35`.

Error still occurs.

4. Prisma schema (if relevant):

Ask if needed.

5. Context

I have an enumerator on my model which is marked red in Studio. When double-click it I get the error mentioned above.

**Comment by nickreynke** [comment]
Ay sorry, didn't see the other issues. Is a possible duplicate of #556, #557 and #555.
