### ISSUE TITLE
Prisma studio crashes on trying to update an enum field type

### ISSUE THREAD

**Issue by Oliver-ke** [prisma/studio#570]
1. Prisma version (`prisma -v` or `npx prisma -v`):
@prisma/cli          : 2.9.0-dev.36
@prisma/client       : 2.9.0-dev.36

2. Logs from Developer Tools Console or Command line, if any:
```
TypeError: t.toUpperCase is not a function
    at http://localhost:5555/studioBundle.js:395:233946
    at Array.filter (<anonymous>)
    at Proxy.forEach.fn.<computed> (http://localhost:5555/studioBundle.js:16:38493)
    at vu.getMatches (http://localhost:5555/studioBundle.js:395:233934)
    at vu.render (http://localhost:5555/studioBundle.js:395:234621)
    at _e (http://localhost:5555/studioBundle.js:16:9807)
    at http://localhost:5555/studioBundle.js:395:74880
    at le (http://localhost:5555/studioBundle.js:16:7913)
    at e.track (http://localhost:5555/studioBundle.js:16:19256)
    at vu.l [as render] (http://localhost:5555/studioBundle.js:395:74828)
    at vu.pt (http://localhost:5555/studioBundle.js:395:74976)
    at vu.t.render (http://localhost:5555/studioBundle.js:395:74214)
    at Gs (http://localhost:5555/studioBundle.js:379:69874)
    at ks (http://localhost:5555/studioBundle.js:379:69669)
    at va (http://localhost:5555/studioBundle.js:379:105468)
    at ul (http://localhost:5555/studioBundle.js:379:96715)
    at al (http://localhost:5555/studioBundle.js:379:96640)
    at Za (http://localhost:5555/studioBundle.js:379:93670)
    at http://localhost:5555/studioBundle.js:379:45312
    at t.unstable_runWithPriority (http://localhost:5555/studioBundle.js:387:3844)
    at Br (http://localhost:5555/studioBundle.js:379:45021)
    at Yr (http://localhost:5555/studioBundle.js:379:45257)
    at qr (http://localhost:5555/studioBundle.js:379:45192)
    at Ka (http://localhost:5555/studioBundle.js:379:90455)
    at Object.enqueueForceUpdate (http://localhost:5555/studioBundle.js:379:49294)
    at t.w.forceUpdate (http://localhost:5555/studioBundle.js:371:1383)
    at http://localhost:5555/studioBundle.js:387:11590
    at o (http://localhost:5555/studioBundle.js:395:56313)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
- Could not try that due to other related dependency issues (type-graphql-prisma)  which arises when I upgrade to the latest

4. Prisma schema (if relevant):
relevant scham snippet
```
enum Role {
  ADMIN
  USER
}

model User {
  id String @default(uuid()) @id
  email String @unique
  uid String @unique // user ID from firebase
  firstName String
  lastName String
  phoneNumber String?
  imgUrl String?
  role Role @default(USER)
  accountType AccountType @default(NONE)
  investeeProfile InvesteeProfile?
  investorProfile InvestorProfile?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```
Issues happen when I try to update any filed of an enum type

**Comment by madebysid** [comment]
Hey @Oliver-ke, this used to be an issue on 2.9.0-dev* releases, but was fixed with the 2.9.0 release. Could you try updating? 2.10.0 is also scheduled to be released today, so depending on when you read this, you might even want to update to 2.10.0. Let me know if you still see this on 2.9.0/2.10.0

**Comment by Oliver-ke** [comment]
Hi @madebysid , I've just upgraded both `@prisma/cli` and `@prisma/client` to `2.9.0`. as at the time of doing so, that was the latest version. thanks, doing that fixes my issue

**Comment by madebysid** [comment]
Awesome, closing this then!
