### ISSUE TITLE
Opened a non-existing project from the history and can't restart Studio

### ISSUE THREAD

**Issue by nikolasburk** [prisma/studio#590]
## Problem

I opened a project from the project history which actually doesn't exist on my file system any more. Now I can't exit the error screen, no matter if I click "Restart Studio" or "Discard all unsaved changes and restart Studio".

![image](https://user-images.githubusercontent.com/4058327/101456157-ebf8d280-3933-11eb-9ee4-33f7d97d80e8.png)

## Error message

```
Error starting Prisma Client: {
  "message": "Get config thread 'main' panicked at 'Could not open datamodel file \"/Users/nikolasburk/Desktop/blogr-nextjs-prisma/prisma/schema.prisma\"', query-engine/query-engine/src/opt.rs:185:53\nstack backtrace:\n   0: _rust_begin_unwind\n   1: std::panicking::begin_panic_fmt\n   2: query_engine::opt::load_datamodel_file::{{closure}}\n   3: structopt::StructOpt::from_args\n   4: query_engine::main::main::{{closure}}::main::{{closure}}\n   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   6: std::thread::local::LocalKey<T>::with\n   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   8: async_io::driver::block_on\n   9: tokio::runtime::context::enter\n  10: async_global_executor::reactor::block_on\n  11: std::thread::local::LocalKey<T>::with\n  12: async_std::task::builder::Builder::blocking\n  13: query_engine::main\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.",
  "stack": "Error: Get config thread 'main' panicked at 'Could not open datamodel file \"/Users/nikolasburk/Desktop/blogr-nextjs-prisma/prisma/schema.prisma\"', query-engine/query-engine/src/opt.rs:185:53\nstack backtrace:\n   0: _rust_begin_unwind\n   1: std::panicking::begin_panic_fmt\n   2: query_engine::opt::load_datamodel_file::{{closure}}\n   3: structopt::StructOpt::from_args\n   4: query_engine::main::main::{{closure}}::main::{{closure}}\n   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   6: std::thread::local::LocalKey<T>::with\n   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   8: async_io::driver::block_on\n   9: tokio::runtime::context::enter\n  10: async_global_executor::reactor::block_on\n  11: std::thread::local::LocalKey<T>::with\n  12: async_std::task::builder::Builder::blocking\n  13: query_engine::main\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n    at Object.getConfig (/Applications/Prisma Studio.app/Contents/Resources/app/node_modules/@prisma/sdk/dist/engineCommands.js:175:23)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Photon.generate (/Applications/Prisma Studio.app/Contents/Resources/app/node_modules/@prisma/studio-pcw/build/pcw.js:25:53)\n    at async IpcMainImpl.photon (/Applications/Prisma Studio.app/Contents/Resources/app/build/ipc/photon-ipc.js:29:63)"
}
Error: Error starting Prisma Client: {
  "message": "Get config thread 'main' panicked at 'Could not open datamodel file \"/Users/nikolasburk/Desktop/blogr-nextjs-prisma/prisma/schema.prisma\"', query-engine/query-engine/src/opt.rs:185:53\nstack backtrace:\n   0: _rust_begin_unwind\n   1: std::panicking::begin_panic_fmt\n   2: query_engine::opt::load_datamodel_file::{{closure}}\n   3: structopt::StructOpt::from_args\n   4: query_engine::main::main::{{closure}}::main::{{closure}}\n   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   6: std::thread::local::LocalKey<T>::with\n   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   8: async_io::driver::block_on\n   9: tokio::runtime::context::enter\n  10: async_global_executor::reactor::block_on\n  11: std::thread::local::LocalKey<T>::with\n  12: async_std::task::builder::Builder::blocking\n  13: query_engine::main\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.",
  "stack": "Error: Get config thread 'main' panicked at 'Could not open datamodel file \"/Users/nikolasburk/Desktop/blogr-nextjs-prisma/prisma/schema.prisma\"', query-engine/query-engine/src/opt.rs:185:53\nstack backtrace:\n   0: _rust_begin_unwind\n   1: std::panicking::begin_panic_fmt\n   2: query_engine::opt::load_datamodel_file::{{closure}}\n   3: structopt::StructOpt::from_args\n   4: query_engine::main::main::{{closure}}::main::{{closure}}\n   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   6: std::thread::local::LocalKey<T>::with\n   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   8: async_io::driver::block_on\n   9: tokio::runtime::context::enter\n  10: async_global_executor::reactor::block_on\n  11: std::thread::local::LocalKey<T>::with\n  12: async_std::task::builder::Builder::blocking\n  13: query_engine::main\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n    at Object.getConfig (/Applications/Prisma Studio.app/Contents/Resources/app/node_modules/@prisma/sdk/dist/engineCommands.js:175:23)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Photon.generate (/Applications/Prisma Studio.app/Contents/Resources/app/node_modules/@prisma/studio-pcw/build/pcw.js:25:53)\n    at async IpcMainImpl.photon (/Applications/Prisma Studio.app/Contents/Resources/app/build/ipc/photon-ipc.js:29:63)"
}
    at ir.init (file:///Applications/Prisma%20Studio.app/Contents/Resources/app/renderer/mainChunk.js:395:160062)
```

## Version

![image](https://user-images.githubusercontent.com/4058327/101456046-c370d880-3933-11eb-8ad1-1ad1a6184634.png)

**Comment by madebysid** [comment]
@nikolasburk Ah I think this only makes sense in the web version. I'll change the buttons so they close this window and take you back to the splash screen.

**Comment by madebysid** [comment]
This is what this screen looks like on the electron app now:

![Screenshot 2020-12-08 at 10 44 37](https://user-images.githubusercontent.com/7689783/101467277-629ccc80-3942-11eb-9a28-e550f147cd17.png)

`Reopen Project` will reload the page (as it does currently), and the secondary link will let you close the currently open project. The reason the primary CTA is "reload" and not "close" is because this generic error screen is shown when any unknow error occurs in Prisma Client, which in most cases is an incorrect query or contraint violations etc.

Hopefully the new buttons make sense!
