### ISSUE TITLE
createMany (preview flag) crashes Studio

### ISSUE THREAD

**Issue by martineboh** [prisma/studio#623]
## Bug description 
I just discovered what seems to be a bug to me. **Studio is closed source, so I can’t really do much** 👨🏽‍💻

`The preview feature \"createMany\" is not known. Expected one of: nativeTypes, microsoftSqlServer, groupBy\n`

Adding `createMany` preview flag to **previwFeatures** array crashes **Prisma Studio**. Studio starts working again when `createMany` is removed from the previewFeatures.

**npx prisma -v:**
```
prisma               : 2.16.0
@prisma/client       : 2.16.0
Current platform     : windows
Query Engine         : query-engine 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules\prisma\node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules\prisma\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules\prisma\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules\prisma\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.346.0
Preview Features     : groupBy, createMany
```

Here's the log from Prisma Studio:
```
Error starting Prisma Client: {
  "message": "Schema Parsing P1012\n\nGet config \nerror: The preview feature \"createMany\" is not known. Expected one of: nativeTypes, microsoftSqlServer, groupBy\n  -->  schema.prisma:13\n   | \n12 |   provider        = \"prisma-client-js\"\n13 |   previewFeatures = [\"groupBy\", \"createMany\"]\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Schema Parsing P1012\n\nGet config \nerror: The preview feature \"createMany\" is not known. Expected one of: nativeTypes, microsoftSqlServer, groupBy\n  -->  schema.prisma:13\n   | \n12 |   provider        = \"prisma-client-js\"\n13 |   previewFeatures = [\"groupBy\", \"createMany\"]\n   | \n\nValidation Error Count: 1\n\n    at Object.getConfig (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\sdk\\dist\\engineCommands.js:182:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Photon.generate (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\studio-pcw\\build\\pcw.js:26:53)\n    at async IpcMainImpl.photon (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\build\\ipc\\photon-ipc.js:40:63)"
}
Error: Error starting Prisma Client: {
  "message": "Schema Parsing P1012\n\nGet config \nerror: The preview feature \"createMany\" is not known. Expected one of: nativeTypes, microsoftSqlServer, groupBy\n  -->  schema.prisma:13\n   | \n12 |   provider        = \"prisma-client-js\"\n13 |   previewFeatures = [\"groupBy\", \"createMany\"]\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Schema Parsing P1012\n\nGet config \nerror: The preview feature \"createMany\" is not known. Expected one of: nativeTypes, microsoftSqlServer, groupBy\n  -->  schema.prisma:13\n   | \n12 |   provider        = \"prisma-client-js\"\n13 |   previewFeatures = [\"groupBy\", \"createMany\"]\n   | \n\nValidation Error Count: 1\n\n    at Object.getConfig (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\sdk\\dist\\engineCommands.js:182:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Photon.generate (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\studio-pcw\\build\\pcw.js:26:53)\n    at async IpcMainImpl.photon (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\build\\ipc\\photon-ipc.js:40:63)"
}
    at ir.init (file:///C:/Users/Martin/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/renderer/mainChunk.js:395:162772)
```

Below is the schema for reproduction:

```js
// Database connection
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["groupBy", "createMany"]
  output          = "../node_modules/@prisma/client"
  binaryTargets   = ["native"]
}

generator dbml {
  provider = "prisma-dbml-generator"
  output   = "./dbml"
}

model UserSessonInfo {
  id         String   @id @default(cuid())
  sessionID  String   @unique
  deviceType String?
  userId     String
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt

  @@index([sessionID], name: "idx_user_session_info_sessionID")
  @@index([deviceType], name: "idx_user_session_info_deviceType")
  @@index([userId], name: "idx_user_session_info_userId")
  @@index([createdAt], name: "idx_user_session_info_createAt")
  @@index([updatedAt], name: "idx_user_session_info_updatedAt")
}

model User {
  id             String    @id @default(cuid())
  email          String    @unique
  hashedPassword String
  username       String    @unique
  emailVerified  Boolean   @default(false)
  lastLogin      DateTime?
  isActive       Boolean   @default(true)
  isBanned       Boolean   @default(false)
  profileId      Int?      @unique
  refresh_token  String?
  isGovControl   Boolean   @default(false)
  createdAt      DateTime  @default(now())
  updatedAt      DateTime  @updatedAt

  @@index([email], name: "idx_user_email")
  @@index([username], name: "idx_user_username")
  @@index([profileId], name: "idx_user_profileId")
  @@index([isActive], name: "idx_user_isactive")
  @@index([isBanned], name: "idx_user_isbanned")
  @@index([createdAt], name: "idx_user_createdAt")
  @@index([updatedAt], name: "idx_user_updatedAt")
}
```

Though removing `createMany` from **previewFeatures** array fixes this.

**Comment by madebysid** [comment]
Very intriguing. I'll take a look at this soon, thanks for reporting!

**Comment by martineboh** [comment]
@madebysid Has this issue been confirmed yet? Any update or possible release date for a fix (if confirmed)? It's really tiring using the web browser as viewer.

**Comment by madebysid** [comment]
Hey, am I correct in assuming that this is only happening on the Electron app? If so, I know what's up and can publish a fix Monday

**Comment by martineboh** [comment]
You're correct! It's only happening in the Desktop (electron app).

```js

Error starting Prisma Client: {
  "message": "Schema Parsing P1012\n\nGet config \nerror: The preview feature \"createMany\" is not known. Expected one of: nativeTypes, microsoftSqlServer, groupBy\n  -->  schema.prisma:13\n   | \n12 |   provider        = \"prisma-client-js\"\n13 |   previewFeatures = [\"groupBy\", \"createMany\"]\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Schema Parsing P1012\n\nGet config \nerror: The preview feature \"createMany\" is not known. Expected one of: nativeTypes, microsoftSqlServer, groupBy\n  -->  schema.prisma:13\n   | \n12 |   provider        = \"prisma-client-js\"\n13 |   previewFeatures = [\"groupBy\", \"createMany\"]\n   | \n\nValidation Error Count: 1\n\n    at Object.getConfig (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\sdk\\dist\\engineCommands.js:182:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Photon.generate (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\studio-pcw\\build\\pcw.js:26:53)\n    at async IpcMainImpl.photon (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\build\\ipc\\photon-ipc.js:40:63)"
}
Error: Error starting Prisma Client: {
  "message": "Schema Parsing P1012\n\nGet config \nerror: The preview feature \"createMany\" is not known. Expected one of: nativeTypes, microsoftSqlServer, groupBy\n  -->  schema.prisma:13\n   | \n12 |   provider        = \"prisma-client-js\"\n13 |   previewFeatures = [\"groupBy\", \"createMany\"]\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Schema Parsing P1012\n\nGet config \nerror: The preview feature \"createMany\" is not known. Expected one of: nativeTypes, microsoftSqlServer, groupBy\n  -->  schema.prisma:13\n   | \n12 |   provider        = \"prisma-client-js\"\n13 |   previewFeatures = [\"groupBy\", \"createMany\"]\n   | \n\nValidation Error Count: 1\n\n    at Object.getConfig (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\sdk\\dist\\engineCommands.js:182:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Photon.generate (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\@prisma\\studio-pcw\\build\\pcw.js:26:53)\n    at async IpcMainImpl.photon (C:\\Users\\Martin\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\build\\ipc\\photon-ipc.js:40:63)"
}
    at ir.init (file:///C:/Users/Martin/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/renderer/mainChunk.js:395:162772)

```

**Comment by madebysid** [comment]
Hey Martin, I've just published v0.351.0 of the desktop app and that should fix this. Let me know if it doesn't!

**Comment by martineboh** [comment]
Thanks @madebysid. I will download and update you on it.

**Comment by martineboh** [comment]
@madebysid I can confirm - It's fixed! Thanks
