### ISSUE TITLE
Prisma Studio throws an error because of initially set filter

### ISSUE THREAD

**Issue by zeekrey** [prisma/studio#635]
1. Prisma version (`prisma -v` or `npx prisma -v`):

```
prisma               : 2.18.0-dev.17
@prisma/client       : 2.18.0-dev.17
Current platform     : windows
Query Engine         : query-engine 892d7238dc86383e8148a737ced422777a6c8487 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 892d7238dc86383e8148a737ced422777a6c8487 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 892d7238dc86383e8148a737ced422777a6c8487 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 892d7238dc86383e8148a737ced422777a6c8487 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.355.0
```

2. Logs from Developer Tools Console or Command line, if any:

```
Error: Invalid fieldId
    at t.a (http://localhost:5555/main.js:16:52477)
    at http://localhost:5555/main.js:402:123357
    at Array.map (<anonymous>)
    at Proxy.forEach.fn.<computed> (http://localhost:5555/main.js:16:38493)
    at zn.get fields (http://localhost:5555/main.js:402:123307)
    at le (http://localhost:5555/main.js:16:7913)
    at e.computeValue (http://localhost:5555/main.js:16:14214)
    at e.trackAndCompute (http://localhost:5555/main.js:16:14040)
    at e.get (http://localhost:5555/main.js:16:13091)
    at e.read (http://localhost:5555/main.js:16:46410)
    at zn.get (http://localhost:5555/main.js:16:47863)
    at Hn (http://localhost:5555/main.js:402:121013)
    at zn.get isValid (http://localhost:5555/main.js:402:125208)
    at le (http://localhost:5555/main.js:16:7913)
    at e.computeValue (http://localhost:5555/main.js:16:14214)
    at e.trackAndCompute (http://localhost:5555/main.js:16:14040)
    at e.get (http://localhost:5555/main.js:16:13091)
    at e.read (http://localhost:5555/main.js:16:46410)
    at zn.get (http://localhost:5555/main.js:16:47863)
    at Di.render (http://localhost:5555/main.js:402:189463)
    at _e (http://localhost:5555/main.js:16:9807)
    at http://localhost:5555/main.js:29:3292
    at le (http://localhost:5555/main.js:16:7913)
    at e.track (http://localhost:5555/main.js:16:19256)
    at Di.c [as render] (http://localhost:5555/main.js:29:3240)
    at Di.E (http://localhost:5555/main.js:29:3387)
    at Di.t.render (http://localhost:5555/main.js:29:2643)
    at Gs (http://localhost:5555/main.js:386:69875)
    at ks (http://localhost:5555/main.js:386:69670)
    at va (http://localhost:5555/main.js:386:105469)
    at ul (http://localhost:5555/main.js:386:96716)
    at al (http://localhost:5555/main.js:386:96641)
    at Za (http://localhost:5555/main.js:386:93671)
    at http://localhost:5555/main.js:386:45313
    at t.unstable_runWithPriority (http://localhost:5555/main.js:394:3844)
    at Br (http://localhost:5555/main.js:386:45022)
    at Yr (http://localhost:5555/main.js:386:45258)
    at qr (http://localhost:5555/main.js:386:45193)
    at L (http://localhost:5555/main.js:386:114342)
    at $t (http://localhost:5555/main.js:386:22723)
    at HTMLDocument.o (http://localhost:5555/main.js:402:44759)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Still persists.

4. Prisma schema (if relevant):
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model Product {
  id            Int       @id @default(autoincrement())
  nameDe        String
  nameEn        String
  descriptionDe String
  descriptionEn String
  slug          String    @default("/")
  files         String
  variants      Variant[]
}

model Variant {
  id            Int     @id @default(autoincrement())
  productId     Int
  nameDe        String
  nameEn        String
  variant       String
  size          String
  color         String
  type          String
  syncVariantId Int     @default(1)
  variantId     Int
  printfulPid   Int
  files         String
  price         Float   @default(0)
  product       Product @relation(fields: [productId], references: [id])
}

```

When I start the Prisma Studio and select the table `Variant` a filter is set. I feel like this filter is set to a field that doesn't exist anymore. But I can't debug this. I tried to reinstall everything but nothing worked so far.

**Comment by madebysid** [comment]
Hey Christian! That's interesting, when you open a model in a new tab, there shouldn't ever be a filter set.

Just to clarify: you're not attempting to switch to a tab with this filter already applied, are you? If so, you'll likely have to close that tab. I do acknowledge that this is a bug though that needs fixing. 

If this is happening on brand new tabs as well, then there's something wrong there as well. If you could dump the contents of your IndexedDB (where Studio stores it's data), that will possibly help me debug this. Here's how you can do that: https://gist.github.com/madebysid/2f084889730528511d5da12984491678

Then, you can clear out your IndexedDB and see if that helps.
