### ISSUE TITLE
[Feature Request] Add support for different connection string than .env file

### ISSUE THREAD

**Issue by puchm** [prisma/studio#650]
1. Prisma version (`prisma -v` or `npx prisma -v`):
Prisma Studio 0.359.0
Prisma 2.20.1
2. Logs from Developer Tools Console or Command line, if any:
```
Message: Error in Prisma Client request: 

Error: Can't reach database server at `db`:`5432`

Please make sure your database server is running at `db`:`5432`.
    at cb (C:\Users\Moritz\AppData\Roaming\@prisma\studio-electron\projects\7a225383\runtime\index.js:34780:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Moritz\AppData\Local\Programs\@prismastudio-electron\resources\app.asar\node_modules\@prisma\studio-pcw\build\pcw.js:133:35
    at async C:\Users\Moritz\AppData\Local\Programs\@prismastudio-electron\resources\app.asar\node_modules\@prisma\studio-pcw\build\pcw.js:106:32
    at async PCW.request (C:\Users\Moritz\AppData\Local\Programs\@prismastudio-electron\resources\app.asar\node_modules\@prisma\studio-pcw\build\pcw.js:173:46)
    at async IpcMainImpl.prisma (C:\Users\Moritz\AppData\Local\Programs\@prismastudio-electron\resources\app.asar\build\ipc\prisma-ipc.js:72:34)

Query:
prisma.user.findMany({
  take: 100,
  skip: 0,
  select: {
    id: true,
    email: true,
    userName: true,
    fullName: true,
    password: true,
  }
})
```

## Feature Request
I would like to have the possibility to specify a different hostname than what Prisma loads from my .env file.
Since I am running Prisma Migrate, my development database and everything else in Docker containers the IP is the name of the docker container, e.g. `db:5432`. Prisma Studio is the only thing not running in Docker containers and needs to use a different IP to access the database from outside, e.g. `localhost:5432`.

Please add the possibility to use a different hostname for Studio than for the other stuff. I think this could be accomplished using either
- a hostname field when opening a schema in Prisma Studio
- a second `url` parameter in the schema file inside the `datasource` block, e.g. `studioUrl`

At the moment I am solving this by supplying a different .env file to the containers but I would like to use the same for both.

Thanks for your great work with Prisma, I love it.
-Moritz

**Comment by hollandThomas** [comment]
**Workaround**
Create a second .env file, e.g. `.env.local` that uses `localhost` instead of `db` as hostname.
```
# .env
DATABASE_URL="postgresql://postgres:postgres@db:5432/mydb?schema=public"
```

```
# .env.local
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/mydb?schema=public"
```

Install https://github.com/venthur/dotenv-cli as a dev-dependency. For convenience sake, add a npm script
```json
"scripts": {
  "prisma:studio": "npx dotenv -e path/to/.env.local -- npx prisma studio",
},
```

The same idea can be applied in case that you want to run e.g. `prisma migrate dev -- <NAME>` outside of your Docker container

**Comment by igalklebanov** [comment]
Hey :wave:

Prisma ORM 7 introduces a brand new standalone [Studio](https://www.prisma.io/docs/orm/tools/prisma-studio), built from the ground up to work everywhere, with or without Prisma ORM. Consequently, all "old Studio" issues are being closed as there won't be any further work on it. :mega:

The new Studio is also available in the Prisma VS Code extension and in the Prisma Console application. :electric_plug:

Help shape, improve and fix the new Studio with us in this repository by submitting bug reports and feature requests. :construction_worker:
