### ISSUE TITLE
Feature Requst: Support latest version with mongodb

### ISSUE THREAD

**Issue by willin** [prisma/studio#663]
1. Prisma version (`prisma -v` or `npx prisma -v`):

Studio App （dmg）：0.359.0.8155

2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "message": "Schema Parsing P1012\n\nGet config \nerror: The preview feature \"mongodb\" is not known. Expected one of: microsoftSqlServer, groupBy, createMany, orderByRelation, napi, selectRelationCount\n  -->  schema.prisma:11\n   | \n10 |   provider        = \"prisma-client-js\"\n11 |   previewFeatures = [\"mongodb\"]\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Schema Parsing P1012\n\nGet config \nerror: The preview feature \"mongodb\" is not known. Expected one of: microsoftSqlServer, groupBy, createMany, orderByRelation, napi, selectRelationCount\n  -->  schema.prisma:11\n   | \n10 |   provider        = \"prisma-client-js\"\n11 |   previewFeatures = [\"mongodb\"]\n   | \n\nValidation Error Count: 1\n\n    at Object.getConfig (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/sdk/dist/engineCommands.js:190:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async PCW.generate (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/build/pcw.js:26:53)\n    at async IpcMainImpl.prisma (/Applications/Prisma Studio.app/Contents/Resources/app.asar/build/ipc/prisma-ipc.js:40:17)"
}
Error: Error starting Prisma Client: {
  "message": "Schema Parsing P1012\n\nGet config \nerror: The preview feature \"mongodb\" is not known. Expected one of: microsoftSqlServer, groupBy, createMany, orderByRelation, napi, selectRelationCount\n  -->  schema.prisma:11\n   | \n10 |   provider        = \"prisma-client-js\"\n11 |   previewFeatures = [\"mongodb\"]\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Schema Parsing P1012\n\nGet config \nerror: The preview feature \"mongodb\" is not known. Expected one of: microsoftSqlServer, groupBy, createMany, orderByRelation, napi, selectRelationCount\n  -->  schema.prisma:11\n   | \n10 |   provider        = \"prisma-client-js\"\n11 |   previewFeatures = [\"mongodb\"]\n   | \n\nValidation Error Count: 1\n\n    at Object.getConfig (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/sdk/dist/engineCommands.js:190:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async PCW.generate (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/build/pcw.js:26:53)\n    at async IpcMainImpl.prisma (/Applications/Prisma Studio.app/Contents/Resources/app.asar/build/ipc/prisma-ipc.js:40:17)"
}
    at Eo.init (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/renderer/main.js:402:148954)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

i have no idea with this

4. Prisma schema (if relevant):

```
// We want to connect to the MongoDB datasource
datasource db {
  provider = "mongodb"
  url      = "mongodb://127.0.0.1:27017/prisma-demo"
}

// We want to generate a typescript client
// Since mongodb is a preview feature, we'll enable that.
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

// Create our post schema. All posts have a title, slug and body.
// The id attributes tell Prisma it's a primary key and to generate 
// object ids by default when we insert posts.
model Post {
  id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  slug  String @unique
  title String
  body  String
  comments Comment[]
}

// Comments contain a comment string and connect back to the post.
// postId must have @db.ObjectId to match up with Post's id type
model Comment {
  id      String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  post    Post   @relation(fields: [postId], references: [id])
  postId  String @db.ObjectId
  comment String
}
```

https://www.notion.so/Getting-Started-with-MongoDB-and-Prisma-58b41c67eb554787944c600d2239801f

**Comment by willin** [comment]
when start with `npx prisma studio`

```
Message: Error in Prisma Client request: 

PANIC in query-engine/connectors/mongodb-query-connector/src/error.rs:104:63
not yet implemented

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v14.16.1+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+undefined%7C%0A%7C+Prisma+Client+++%7C+in-memory++++++++++%7C%0A%7C+Query+Engine++++%7C+query-engine+0a7721e852b67fc4174613a4e3166dd29addf70f%7C%0A%7C+Database++++++++%7C+undefined%7C%0A%0A%0A%0A%23%23+Query%0A%60%60%60%0Aquery+%7B%0A++findManyComment%28%0A++++where%3A+%7B%0A++++++AND%3A+%5B%5D%0A++++%7D%0A++++take%3A+5%0A++++skip%3A+5%0A++%29+%7B%0A++++id%0A++++post+%7B%0A++++++id%0A++++++slug%0A++++++title%0A++++++body%0A++++%7D%0A++++postId%0A++++comment%0A++%7D%0A%7D%0A%60%60%60%0A%0A%23%23+Logs%0A%60%60%60%0AX+Execution+permissions+of+%2FUsers%2Fwillin%2FDesktop%2Fblog%2Fnode_modules%2F%40prisma%2Fengines%2Fquery-engine-darwin+are+fine++%0A++prisma%3Aengine+stderr++%5Bquery-engine%2Fconnectors%2Fmongodb-query-connector%2Fsrc%2Ferror.rs%3A28%5D+%26self+%3D+DriverError%28++%0A++prisma%3Aengine+stderr++++++Error+%7B++%0A++prisma%3Aengine+stderr++++++++++kind%3A+CommandError%28++%0A++prisma%3Aengine+stderr++++++++++++++CommandError+%7B++%0A++prisma%3Aengine+stderr++++++++++++++++++code%3A+2%2C++%0A++prisma%3Aengine+stderr++++++++++++++++++code_name%3A+%22BadValue%22%2C++%0A++prisma%3Aengine+stderr++++++++++++++++++message%3A+%22%24and%2F%24or%2F%24nor+must+be+a+nonempty+array%22%2C++%0A++prisma%3Aengine+stderr++++++++++++++++++labels%3A+%5B%5D%2C++%0A++prisma%3Aengine+stderr++++++++++++++%7D%2C++%0A++prisma%3Aengine+stderr++++++++++%29%2C++%0A++prisma%3Aengine+stderr++++++++++labels%3A+%5B%5D%2C++%0A++prisma%3Aengine+stderr++++++%7D%2C++%0A++prisma%3Aengine+stderr++%29++%0A++prisma%3Aengine+stdout++PANIC+in+query-engine%2Fconnectors%2Fmongodb-query-connector%2Fsrc%2Ferror.rs%3A104%3A63%0Anot+yet+implemented++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+SocketError%3A+other+side+closed%0A++prisma%3Aengine+++++++at+Socket.onSocketEnd+%28%2FUsers%2Fwillin%2FDesktop%2Fblog%2Fnode_modules%2Fprisma%2Fprisma-client%2Fruntime%2Findex.js%3A25208%3A24%29%0A++prisma%3Aengine+++++++at+Socket.emit+%28events.js%3A327%3A22%29%0A++prisma%3Aengine+++++++at+Socket.EventEmitter.emit+%28domain.js%3A467%3A12%29%0A++prisma%3Aengine+++++++at+endReadableNT+%28internal%2Fstreams%2Freadable.js%3A1327%3A12%29%0A++prisma%3Aengine+++++++at+processTicksAndRejections+%28internal%2Fprocess%2Ftask_queues.js%3A80%3A21%29+%7B%0A++prisma%3Aengine+++++code%3A+%27UND_ERR_SOCKET%27%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++prisma%3Aengine+%7B+cwd%3A+%27%2FUsers%2Fwillin%2FDesktop%2Fblog%2Fprisma%27+%7D++%0A++prisma%3Aengine+Client+Version%3A+in-memory++%0A++prisma%3Aengine+Engine+Version%3A+query-engine+0a7721e852b67fc4174613a4e3166dd29addf70f++%0A++prisma%3Aengine+Active+provider%3A+mongodb++%0A++plusX+Execution+permissions+of+%2FUsers%2Fwillin%2FDesktop%2Fblog%2Fnode_modules%2F%40prisma%2Fengines%2Fquery-engine-darwin+are+fine++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++flags%3A+%5B%0A++prisma%3Aengine+++++%27--enable-experimental%3Dmongodb%2Cmongodb%27%2C%0A++prisma%3Aengine+++++%27--enable-raw-queries%27%2C%0A++prisma%3Aengine+++++%27--port%27%2C%0A++prisma%3Aengine+++++%2753797%27%0A++prisma%3Aengine+++%5D%0A++prisma%3Aengine+%7D++%0A++prisma%3Aengine+stdout++Started+http+server+on+http%3A%2F%2F127.0.0.1%3A53792++%0A++plusX+Execution+permissions+of+%2FUsers%2Fwillin%2FDesktop%2Fblog%2Fnode_modules%2F%40prisma%2Fengines%2Fquery-engine-darwin+are+fine++%0A++prisma%3Aengine+Stopping+Prisma+engine4++%0A++prisma%3Aengine+Waiting+for+start+promise++%0A++prisma%3Aengine+Done+waiting+for+start+promise++%0A++prisma%3Aengine+Client+Version%3A+in-memory++%0A++prisma%3Aengine+Engine+Version%3A+query-engine+0a7721e852b67fc4174613a4e3166dd29addf70f++%0A++prisma%3Aengine+Active+provider%3A+mongodb++%0A++prisma%3Aengine+stdout++Started+http+server+on+http%3A%2F%2F127.0.0.1%3A53797++%0A++plusX+Execution+permissions+of+%2FUsers%2Fwillin%2FDesktop%2Fblog%2Fnode_modules%2F%40prisma%2Fengines%2Fquery-engine-darwin+are+fine++%0A++prisma%3Aengine+stderr++%5Bquery-engine%2Fconnectors%2Fmongodb-query-connector%2Fsrc%2Ferror.rs%3A28%5D+%26self+%3D+DriverError%28++%0A++prisma%3Aengine+stderr++++++Error+%7B++%0A++prisma%3Aengine+stderr++++++++++kind%3A+CommandError%28++%0A++prisma%3Aengine+stderr++++++++++++++CommandError+%7B++%0A++prisma%3Aengine+stderr++++++++++++++++++code%3A+2%2C++%0A++prisma%3Aengine+stderr++++++++++++++++++code_name%3A+%22BadValue%22%2C++%0A++prisma%3Aengine+stderr++++++++++++++++++message%3A+%22%24and%2F%24or%2F%24nor+must+be+a+nonempty+array%22%2C++%0A++prisma%3Aengine+stderr++++++++++++++++++labels%3A+%5B%5D%2C++%0A++prisma%3Aengine+stderr++++++++++++++%7D%2C++%0A++prisma%3Aengine+stderr++++++++++%29%2C++%0A++prisma%3Aengine+stderr++++++++++labels%3A+%5B%5D%2C++%0A++prisma%3Aengine+stderr++++++%7D%2C++%0A++prisma%3Aengine+stderr++%29++%0A++prisma%3Aengine+stdout++PANIC+in+query-engine%2Fconnectors%2Fmongodb-query-connector%2Fsrc%2Ferror.rs%3A104%3A63%0Anot+yet+implemented++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+SocketError%3A+other+side+closed%0A++prisma%3Aengine+++++++at+Socket.onSocketEnd+%28%2FUsers%2Fwillin%2FDesktop%2Fblog%2Fnode_modules%2Fprisma%2Fprisma-client%2Fruntime%2Findex.js%3A25208%3A24%29%0A++prisma%3Aengine+++++++at+Socket.emit+%28events.js%3A327%3A22%29%0A++prisma%3Aengine+++++++at+Socket.EventEmitter.emit+%28domain.js%3A467%3A12%29%0A++prisma%3Aengine+++++++at+endReadableNT+%28internal%2Fstreams%2Freadable.js%3A1327%3A12%29%0A++prisma%3Aengine+++++++at+processTicksAndRejections+%28internal%2Fprocess%2Ftask_queues.js%3A80%3A21%29+%7B%0A++prisma%3Aengine+++++code%3A+%27UND_ERR_SOCKET%27%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A&title=PANIC+in+query-engine%2Fconnectors%2Fmongodb-query-connector%2Fsrc%2Ferror.rs%3A104%3A63%0Anot+yet+implemented&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

  
  Query:
  prisma.comment.findMany({
  where: {
    AND: [
    ]
  },
  take: 100,
  skip: 0,
  select: {
    id: true,
    post: true,
    postId: true,
    comment: true,
  }
})
```

**Comment by janpio** [comment]
Hey @willin, seems you are using an older version of Prisma CLI on your machine. Here is the full version output of the current version that supports MongoDB:

```
λ npx prisma -v
Environment variables loaded from .env
prisma               : 2.21.2
@prisma/client       : Not found
Current platform     : windows
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
Preview Features     : mongodb
```

Studio is on `0.371.0` here.

I think upgrading your CLI should already fix your problem.

**Comment by willin** [comment]
dev.26  previous，now

```
 "@prisma/client": "^2.22.0-dev.32", 
    "prisma": "^2.22.0-dev.32",
``

**Comment by madebysid** [comment]
Hey @willin, totally forgot about this, but the latest version of the CLI should now work with MongoDB if you set the correct feature flag. Let me know if it doesn't!
