### ISSUE TITLE
Unable to start the studio

### ISSUE THREAD

**Issue by nizar-zouaoui** [prisma/studio#667]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma               : 2.21.2
@prisma/client       : Not found
Current platform     : windows
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at ..\..\AppData\Local\Yarn\Data\global\node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at ..\..\AppData\Local\Yarn\Data\global\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at ..\..\AppData\Local\Yarn\Data\global\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at ..\..\AppData\Local\Yarn\Data\global\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
Preview Features     : microsoftSqlServer
```
2. Logs from Developer Tools Console or Command line, if any:
```
    Cannot read property 'forEach' of undefined
    TypeError: Cannot read property 'forEach' of undefined
    at Object.hydrate (http://localhost:5555/index.js:1:75146)
    at ki.init (http://localhost:5555/index.js:1:104917)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
Yes
4. Prisma schema (if relevant):
```
No schema available yet
```

**Comment by janpio** [comment]
Can you connect to the server with other commands like `prisma introspect`?

**Comment by madebysid** [comment]
Hey @nizar-zouaoui, I cannot see this on `prisma` v2.22.0, so I'm going to close this. Please feel free to reopen if this is still an issue!
