### ISSUE TITLE
Prisma Studio unable to locate @prisma/client module.

### ISSUE THREAD

**Issue by BJDubb** [prisma/studio#674]
1. Prisma version (`prisma -v` or `npx prisma -v`):

prisma: 2.22.0
prisma client: 2.22.0

2. Logs from Developer Tools Console or Command line, if any:
```
Prisma schema loaded from prisma\schema.prisma
Prisma Studio is up on http://localhost:5555
Unable to get DMMF from Prisma Client:  Error: Cannot find module '@prisma/client'
Require stack:
- C:\Users\*****\AppData\Roaming\npm-cache\_npx\52476\node_modules\prisma\build\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at PCW.resolvePrismaClient (C:\Users\*****\AppData\Roaming\npm-cache\_npx\52476\node_modules\prisma\build\index.js:139265:83)
    at PCW.getDMMF (C:\Users\*****\AppData\Roaming\npm-cache\_npx\52476\node_modules\prisma\build\index.js:139094:41)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PrismaService.respond (C:\Users\*****\AppData\Roaming\npm-cache\_npx\52476\node_modules\prisma\build\index.js:139362:50)
    at async C:\Users\*****\AppData\Roaming\npm-cache\_npx\52476\node_modules\prisma\build\index.js:139544:35 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\*****\\AppData\\Roaming\\npm-cache\\_npx\\52476\\node_modules\\prisma\\build\\index.js'
  ]
}
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

No

4. Prisma schema (if relevant):
```
datasource db {
  provider = "mysql"
  url      = "mysql://****:****@****.com:3306/****"
}

generator client {
  provider = "prisma-client-js"
}

model business {
  id          String     @id @default(cuid())
  displayName String
  employees   employee[]
}

model employee {
  id            String    @id @default(cuid())
  businessId    String
  business      business? @relation(fields: [businessId], references: [id])
  prefferedName String
  firstname     String
  surname       String
  gender        String
  phone         String
  email         String
  department    String
  payrate       Decimal
  timesheets    timesheet[]
}

model timesheet {
  id             String    @id @default(cuid())
  employeeId     String
  employee       employee? @relation(fields: [employeeId], references: [id])
  rosteredStart  DateTime
  rosteredFinish DateTime
  actualStart    DateTime
  actualFinish   DateTime
  department     String
  breakTime      Int
}

model Account {
  id                 Int       @default(autoincrement()) @id
  compoundId         String    @unique @map(name: "compound_id")
  userId             Int       @map(name: "user_id")
  providerType       String    @map(name: "provider_type")
  providerId         String    @map(name: "provider_id")
  providerAccountId  String    @map(name: "provider_account_id")
  refreshToken       String?   @map(name: "refresh_token")
  accessToken        String?   @map(name: "access_token")
  accessTokenExpires DateTime? @map(name: "access_token_expires")
  createdAt          DateTime  @default(now()) @map(name: "created_at")
  updatedAt          DateTime  @default(now()) @map(name: "updated_at")

  @@index([providerAccountId], name: "providerAccountId")
  @@index([providerId], name: "providerId")
  @@index([userId], name: "userId")

  @@map(name: "accounts")
}

model Session {
  id           Int      @default(autoincrement()) @id
  userId       Int      @map(name: "user_id")
  expires      DateTime
  sessionToken String   @unique @map(name: "session_token")
  accessToken  String   @unique @map(name: "access_token")
  createdAt    DateTime @default(now()) @map(name: "created_at")
  updatedAt    DateTime @default(now()) @map(name: "updated_at")

  @@map(name: "sessions")
}

model User {
  id            Int       @default(autoincrement()) @id
  name          String?
  email         String?   @unique
  emailVerified DateTime? @map(name: "email_verified")
  image         String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
  updatedAt     DateTime  @default(now()) @map(name: "updated_at")

  @@map(name: "users")
}

model VerificationRequest {
  id         Int      @default(autoincrement()) @id
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime  @default(now()) @map(name: "created_at")
  updatedAt  DateTime  @default(now()) @map(name: "updated_at")

  @@map(name: "verification_requests")
}
```

**Comment by madebysid** [comment]
Hey @BJDubb! Am I correct in assuming that you have the Prisma CLI installed globally?

I can see the same error when I have it installed globally, but not when `prisma` is a `devDependency` of my project (and hence is run via an npm script, for example).

Nevertheless, this is a workaround, and I will investigate why Studio doesn't work from a global installation, thanks for reporting this!

**Comment by BJDubb** [comment]
> Hey @BJDubb! Am I correct in assuming that you have the Prisma CLI installed globally?
> 
> I can see the same error when I have it installed globally, but not when `prisma` is a `devDependency` of my project (and hence is run via an npm script, for example).
> 
> Nevertheless, this is a workaround, and I will investigate why Studio doesn't work from a global installation, thanks for reporting this!

Yes, you are correct. The Prisma CLI is installed globally. Its not a worry to me as I am now using the alpha, however the error does still exist and may be difficult for newer users of npm/prisma to debug. 

Cheers!

**Comment by Manubi** [comment]
I had the same problem with prisma inside a docker container. `npm install -g prisma` had the error. `npm install -D prisma` works.

**Comment by ra-kesh** [comment]
I was struglling with same error since morning..I was using `prisma studio` directly...so if anyone is doing that, please run the command as a npm script..it will work.. all the best..

**Comment by jamesdh** [comment]
Just ran into this trying to setup Prisma Studio for the first time outside of any npm based project.
