### ISSUE TITLE
Prisma Studio standalone app crashes when opening prisma-client-go schema file

### ISSUE THREAD

**Issue by zackartz** [prisma/studio#677]
1. Prisma version (`prisma -v` or `npx prisma -v`):
prisma studio electron app v0.359.0 prisma v2.22.1
2. Logs from Developer Tools Console or Command line, if any:
```
Unable to init PersistenceStore
Error: Unable to init PersistenceStore
    at t.a (file:///C:/Users/zack/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/renderer/main.js:16:52477)
    at Object.init (file:///C:/Users/zack/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/renderer/main.js:402:72210)
    at async Eo.init (file:///C:/Users/zack/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/renderer/main.js:402:149333)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
in a prisma-client-go project, latest version (v0.8.0)

4. Prisma schema (if relevant):
```
datasource db {
  // could be postgresql or mysql
  provider = "postgres"
  url      = "postgresql://postgres:password@localhost:5432/postgres?schema=public"
}

generator db {
  provider = "go run github.com/prisma/prisma-client-go"
}

model Post {
  id         String    @id @default(cuid())
  createdAt  DateTime  @default(now())
  updatedAt  DateTime  @updatedAt
  title      String
  published  Boolean
  desc       String?
  comments   Comment[]
}

model Comment {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  content   String

  post   Post   @relation(fields: [postID], references: [id])
  postID String
}

```

**Comment by zackartz** [comment]
apparently a process was still running, this is a non issue. my apologies
