### ISSUE TITLE
RESOLVED: Non Recoverable Error Has Occurred

### ISSUE THREAD

**Issue by thecodeclimber** [prisma/studio#704]
![image](https://user-images.githubusercontent.com/65869221/121406714-25ec7500-c967-11eb-8458-38e9a347d7dc.png)

```
Error starting Prisma Client: {
  "stack": "Error: Cannot find module '@prisma/client'\nRequire stack:\n- C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)\n    at Function.resolve (internal/modules/cjs/helpers.js:94:19)\n    at eval (eval at resolvePrismaClient (C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js:110600:75), <anonymous>:1:9)\n    at PCW.resolvePrismaClient (C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js:110600:75)\n    at PCW.getDMMF (C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js:110427:41)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async PrismaService.respond (C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js:110692:50)\n    at async C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js:110867:35",
  "message": "Cannot find module '@prisma/client'\nRequire stack:\n- C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js",
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js"
  ]
}
Error: Error starting Prisma Client: {
  "stack": "Error: Cannot find module '@prisma/client'\nRequire stack:\n- C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)\n    at Function.resolve (internal/modules/cjs/helpers.js:94:19)\n    at eval (eval at resolvePrismaClient (C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js:110600:75), <anonymous>:1:9)\n    at PCW.resolvePrismaClient (C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js:110600:75)\n    at PCW.getDMMF (C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js:110427:41)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async PrismaService.respond (C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js:110692:50)\n    at async C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js:110867:35",
  "message": "Cannot find module '@prisma/client'\nRequire stack:\n- C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js",
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "C:\\code\\learn\\nextjs\\holiday\\house-app\\node_modules\\prisma\\build\\index.js"
  ]
}
    at ki.init (http://localhost:5555/assets/index.js:1:103828)

```

**Comment by thecodeclimber** [comment]
I had not yet installed `@prisma/client`

**Comment by thecodeclimber** [comment]
okay - thanks for letting me know.

**Comment by madebysid** [comment]
Let's close this in favour of #703 then
