### ISSUE TITLE
unable to start studio

### ISSUE THREAD

**Issue by vanceeasleaf** [prisma/studio#705]
1. Prisma version (`prisma -v` or `npx prisma -v`):2.24.1
nodejs version 13.7
2. Logs from Developer Tools Console or Command line, if any:
```
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at Object.hydrate (http://localhost:5555/assets/index.js:1:75344)
    at ki.init (http://localhost:5555/assets/index.js:1:104419)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

```

**Comment by vanceeasleaf** [comment]
well.... edit schema and npx prisma instrospect  is the answer

**Comment by vanceeasleaf** [comment]
mysql fulltext index is not supported.. well I have to use sequelize instead
