### ISSUE TITLE
Prisma Studio can't find client

### ISSUE THREAD

**Issue by nailuj29gaming** [prisma/studio#708]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```
Environment variables loaded from ../../../.env
Prisma schema loaded from prisma/schema.prisma
Prisma Studio is up on http://localhost:5555
Unable to get DMMF from Prisma Client:  Error: Cannot find module '@prisma/client'
Require stack:
- /home/nailuj29/.config/yarn/global/node_modules/prisma/build/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.resolve (node:internal/modules/cjs/helpers:99:19)
    at eval (eval at resolvePrismaClient (/home/nailuj29/.config/yarn/global/node_modules/prisma/build/index.js:110600:75), <anonymous>:1:9)
    at PCW.resolvePrismaClient (/home/nailuj29/.config/yarn/global/node_modules/prisma/build/index.js:110600:75)
    at PCW.getDMMF (/home/nailuj29/.config/yarn/global/node_modules/prisma/build/index.js:110427:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PrismaService.respond (/home/nailuj29/.config/yarn/global/node_modules/prisma/build/index.js:110692:50)
    at async /home/nailuj29/.config/yarn/global/node_modules/prisma/build/index.js:110867:35 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/nailuj29/.config/yarn/global/node_modules/prisma/build/index.js'
  ]
}

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
yes
4. Prisma schema (if relevant):
```
n/a
```

**Comment by ducdev** [comment]
Same here.

**Comment by nailuj29gaming** [comment]
That worked, thanks! It might be useful to have globally-installed Prisma use the local `@prisma/client` if a schema exists

**Comment by madebysid** [comment]
Hey @nailuj29gaming @ducdev this is most definitely a bug, since Studio should be able to launch from a global installation as well.

This looks like the same issue as https://github.com/prisma/studio/issues/703 then, so I'll close this one just to keep things manageable for myself. Please let me know if I misunderstood and I will reopen!
