### ISSUE TITLE
Error prisma studio

### ISSUE THREAD

**Issue by OlegCinema** [prisma/studio#709]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```
Unable to get DMMF from Prisma Client:  Error: Schema parsing
error: Found argument '--enable-experimental' which wasn't expected, or isn't valid in this context
	Did you mean --enable-playground?

USAGE:
    query-engine-darwin --enable-playground

For more information try --help
    at Object.getDMMF2 [as getDMMF] (/Users/pavliukdanila/Desktop/Projects/wikiever/node_modules/@prisma/client/generator-build/index.js:33169:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getDMMF (/Users/pavliukdanila/Desktop/Projects/wikiever/node_modules/@prisma/client/generator-build/index.js:77086:16)
    at async PCW.getDMMF (/Users/pavliukdanila/Desktop/Projects/wikiever/node_modules/prisma/build/index.js:110429:24)
    at async PrismaService.respond (/Users/pavliukdanila/Desktop/Projects/wikiever/node_modules/prisma/build/index.js:110692:50)
    at async /Users/pavliukdanila/Desktop/Projects/wikiever/node_modules/prisma/build/index.js:110867:35
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["orderByRelation"]
}

model Account {
  id                 Int       @id @default(autoincrement())
  compoundId         String    @unique @map(name: "compound_id")
  userId             Int       @map(name: "user_id")
  providerType       String    @map(name: "provider_type")
  providerId         String    @map(name: "provider_id")
  providerAccountId  String    @map(name: "provider_account_id")
  refreshToken       String?   @map(name: "refresh_token")
  accessToken        String?   @map(name: "access_token")
  accessTokenExpires DateTime? @map(name: "access_token_expires")
  createdAt          DateTime  @default(now()) @map(name: "created_at")
  updatedAt          DateTime  @default(now()) @map(name: "updated_at")


  @@index([providerAccountId], name: "providerAccountId")
  @@index([providerId], name: "providerId")
  @@index([userId], name: "userId")
  @@map(name: "accounts")
}

model Session {
  id           Int      @id @default(autoincrement())
  userId       Int      @map(name: "user_id")
  expires      DateTime
  sessionToken String   @unique @map(name: "session_token")
  accessToken  String   @unique @map(name: "access_token")
  createdAt    DateTime @default(now()) @map(name: "created_at")
  updatedAt    DateTime @default(now()) @map(name: "updated_at")

  @@map(name: "sessions")
}

model User {
  id            Int       @id @default(autoincrement())
  name          String?
  email         String?   @unique
  emailVerified DateTime? @map(name: "email_verified")
  image         String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
  updatedAt     DateTime  @default(now()) @map(name: "updated_at")
  Request       Request[]

  @@map(name: "users")
}

model VerificationRequest {
  id         Int      @id @default(autoincrement())
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now()) @map(name: "created_at")
  updatedAt  DateTime @default(now()) @map(name: "updated_at")

  @@map(name: "verification_requests")
}

model Link {
  id     Int    @id @default(autoincrement())
  href   String @unique
  action Odd[]
}

model Revision {
  id            Int      @id
  userName      String   @map(name: "user_name")
  userId        Int      @map(name: "user_id")
  userRights    String[] @map(name: "user_rights")
  createdAt     DateTime
  isBot         Boolean  @map(name: "is_bot")
  pageTitle     String   @map(name: "page_title")
  pageNamespace String?  @map(name: "page_namespace")
  Odd           Odd[]
}

enum Role {
  DELETE
  ADD
}

enum RequestType {
  LINK
}

model Odd {
  id         Int      @id @default(autoincrement())
  revision   Revision @relation(fields: [revisionId], references: [id])
  type       Role
  revisionId Int
  links      Link[]
}

model Request {
  id         Int         @id @default(autoincrement())
  requestAt  DateTime    @default(now()) @map(name: "request_at")
  type       RequestType
  urlRequest String      @map(name: "url_request")
  isExport   Boolean     @default(false) @map(name: "is_export")
  authorIP   String      @map(name: "author_ip")
  author     User        @relation(fields: [authorId], references: [id])
  authorId   Int

  @@map(name: "check_link_requests")
}
```

**Comment by OlegCinema** [comment]
```
Error starting Prisma Client: {
  "stack": "Error: \u001b[91m\u001b[1mSchema parsing\u001b[22m\u001b[39m\n\u001b[91m\u001b[1m\u001b[22m\u001b[39merror: Found argument '--enable-experimental' which wasn't expected, or isn't valid in this context\n\tDid you mean \u001b[32m--\u001b[0m\u001b[32menable-playground\u001b[0m?\n\nUSAGE:\n    query-engine-darwin --enable-playground\n\nFor more information try --help\n    at Object.getDMMF2 [as getDMMF] (/Users/pavliukdanila/Desktop/Projects/wikiever/node_modules/@prisma/client/generator-build/index.js:33169:15)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getDMMF (/Users/pavliukdanila/Desktop/Projects/wikiever/node_modules/@prisma/client/generator-build/index.js:77086:16)\n    at async PCW.getDMMF (/Users/pavliukdanila/Desktop/Projects/wikiever/node_modules/prisma/build/index.js:110429:24)\n    at async PrismaService.respond (/Users/pavliukdanila/Desktop/Projects/wikiever/node_modules/prisma/build/index.js:110692:50)\n    at async /Users/pavliukdanila/Desktop/Projects/wikiever/node_modules/prisma/build/index.js:110867:35",
  "message": "\u001b[91m\u001b[1mSchema parsing\u001b[22m\u001b[39m\n\u001b[91m\u001b[1m\u001b[22m\u001b[39merror: Found argument '--enable-experimental' which wasn't expected, or isn't valid in this context\n\tDid you mean \u001b[32m--\u001b[0m\u001b[32menable-playground\u001b[0m?\n\nUSAGE:\n    query-engine-darwin --enable-playground\n\nFor more information try --help"
}
http://localhost:5557/assets/index.js:1:103837
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

**Comment by madebysid** [comment]
Thanks for reporting @OlegCinema, It looks like the binary Prisma uses internally is very old in your case, can you try running `npx prisma -v` and let me know what the result is?
Do you also have `prisma` installed globally (instead of your project)?
