### ISSUE TITLE
Prisma Studio crash on launch "Unable to get DMMF from Prisma Client:  Error: Cannot find module '@prisma/client'"

### ISSUE THREAD

**Issue by jdheeter** [prisma/studio#710]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma               : 2.24.1
@prisma/client       : 2.24.1
Current platform     : darwin
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at ../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at ../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at ../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at ../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0
```
2. Logs from Developer Tools Console or Command line, if any:
```
johnheeter@Johns-MBP upliftlogger % npx prisma studio
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Prisma Studio is up on http://localhost:5555
Unable to get DMMF from Prisma Client:  Error: Cannot find module '@prisma/client'
Require stack:
- /Users/johnheeter/.npm/_npx/2778af9cee32ff87/node_modules/prisma/build/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at eval (eval at resolvePrismaClient (/Users/johnheeter/.npm/_npx/2778af9cee32ff87/node_modules/prisma/build/index.js:110600:75), <anonymous>:1:9)
    at PCW.resolvePrismaClient (/Users/johnheeter/.npm/_npx/2778af9cee32ff87/node_modules/prisma/build/index.js:110600:75)
    at PCW.getDMMF (/Users/johnheeter/.npm/_npx/2778af9cee32ff87/node_modules/prisma/build/index.js:110427:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PrismaService.respond (/Users/johnheeter/.npm/_npx/2778af9cee32ff87/node_modules/prisma/build/index.js:110692:50)
    at async /Users/johnheeter/.npm/_npx/2778af9cee32ff87/node_modules/prisma/build/index.js:110867:35 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/johnheeter/.npm/_npx/2778af9cee32ff87/node_modules/prisma/build/index.js'
  ]
}

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
yes

**Comment by madebysid** [comment]
Hey @jdheeter, this is the same issue as https://github.com/prisma/studio/issues/703, which is now fixed and will be released today!
I'm closing this, but if you see this after Prisma 2.25.0 is out, please do reopen!
