### ISSUE TITLE
Prisma studio error

### ISSUE THREAD

**Issue by Ivaniku** [prisma/studio#711]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma               : 2.24.1
@prisma/client       : 2.24.1
Current platform     : windows
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\introspection-engine-windows.exe)        
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0
```

2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "stack": "Error: Cannot find module '@prisma/client'\nRequire stack:\n- C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)\n    at Function.resolve (node:internal/modules/cjs/helpers:99:19)\n    at eval (eval at resolvePrismaClient (C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js:110600:75), <anonymous>:1:9)\n    at PCW.resolvePrismaClient (C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js:110600:75)\n    at PCW.getDMMF (C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js:110427:41)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PrismaService.respond (C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js:110692:50)\n    at async C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js:110867:35",
  "message": "Cannot find module '@prisma/client'\nRequire stack:\n- C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js",
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js"
  ]
}
Error: Error starting Prisma Client: {
  "stack": "Error: Cannot find module '@prisma/client'\nRequire stack:\n- C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)\n    at Function.resolve (node:internal/modules/cjs/helpers:99:19)\n    at eval (eval at resolvePrismaClient (C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js:110600:75), <anonymous>:1:9)\n    at PCW.resolvePrismaClient (C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js:110600:75)\n    at PCW.getDMMF (C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js:110427:41)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PrismaService.respond (C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js:110692:50)\n    at async C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js:110867:35",
  "message": "Cannot find module '@prisma/client'\nRequire stack:\n- C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js",
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\prisma\\build\\index.js"
  ]
}
    at ki.init (http://localhost:5555/assets/index.js:1:103828)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
`Yes`

**Comment by madebysid** [comment]
Hey @Ivaniku, this is the same issue as https://github.com/prisma/studio/issues/703, which is now fixed and will be released today!
I'm closing this, but if you see this after Prisma 2.25.0 is out, please do reopen!
