### ISSUE TITLE
Fatal error in electron app with `referentialActions` flag

### ISSUE THREAD

**Issue by kkarimi** [prisma/studio#716]
1. Prisma version (`prisma -v` or `npx prisma -v`): 
```
Environment variables loaded from .env
prisma               : 2.26.0
@prisma/client       : 2.26.0
Current platform     : darwin
Query Engine         : query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 9b816b3aa13cc270074f172f30d6eda8a8ce867d
Studio               : 0.408.0
Preview Features     : orderByRelation, nApi, referentialActions
```
2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "message": "Schema Parsing P1012\n\nGet config \nerror: The preview feature \"referentialActions\" is not known. Expected one of: microsoftSqlServer, orderByRelation, nApi, selectRelationCount, orderByAggregateGroup, filterJson\n  -->  schema.prisma:9\n   | \n 8 |   provider        = \"prisma-client-js\"\n 9 |   previewFeatures = [\"orderByRelation\", \"nApi\", \"referentialActions\"]\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Schema Parsing P1012\n\nGet config \nerror: The preview feature \"referentialActions\" is not known. Expected one of: microsoftSqlServer, orderByRelation, nApi, selectRelationCount, orderByAggregateGroup, filterJson\n  -->  schema.prisma:9\n   | \n 8 |   provider        = \"prisma-client-js\"\n 9 |   previewFeatures = [\"orderByRelation\", \"nApi\", \"referentialActions\"]\n   | \n\nValidation Error Count: 1\n\n    at Object.getConfig (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/sdk/dist/engineCommands.js:174:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async PCW.getDMMF (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/dist/pcw.js:52:32)\n    at async IpcMainImpl.prisma (/Applications/Prisma Studio.app/Contents/Resources/app.asar/build/ipc/prisma-ipc.js:13:54)"
}
Error: Error starting Prisma Client: {
  "message": "Schema Parsing P1012\n\nGet config \nerror: The preview feature \"referentialActions\" is not known. Expected one of: microsoftSqlServer, orderByRelation, nApi, selectRelationCount, orderByAggregateGroup, filterJson\n  -->  schema.prisma:9\n   | \n 8 |   provider        = \"prisma-client-js\"\n 9 |   previewFeatures = [\"orderByRelation\", \"nApi\", \"referentialActions\"]\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Schema Parsing P1012\n\nGet config \nerror: The preview feature \"referentialActions\" is not known. Expected one of: microsoftSqlServer, orderByRelation, nApi, selectRelationCount, orderByAggregateGroup, filterJson\n  -->  schema.prisma:9\n   | \n 8 |   provider        = \"prisma-client-js\"\n 9 |   previewFeatures = [\"orderByRelation\", \"nApi\", \"referentialActions\"]\n   | \n\nValidation Error Count: 1\n\n    at Object.getConfig (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/sdk/dist/engineCommands.js:174:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async PCW.getDMMF (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/dist/pcw.js:52:32)\n    at async IpcMainImpl.prisma (/Applications/Prisma Studio.app/Contents/Resources/app.asar/build/ipc/prisma-ipc.js:13:54)"
}
    at ki.init (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/renderer/assets/index.js:1:103826)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`) Yes

4. Prisma schema (if relevant):
```

```

I just added the new `referentialActions` flag per release notes and I cannot open studio

**Comment by madebysid** [comment]
Hey @kkarimi, thanks for reporting! I'll check this out right away and let you know what I find.

**Comment by madebysid** [comment]
Hmm I'm unable to see an error on Prisma CLI v2.26.0 when `nApi` and `referentialActions` is turned on, Studio loads up just fine for me.

If this issue is about https://cloud.prisma.io like you also reported on Slack, then that's fixed though :D

Let me know, then I'll investigate / close this issue.

**Comment by kkarimi** [comment]
thanks for looking in to it @madebysid - yes I still get it locally in the electron app - CLI seems to be fine. 

  <img width="968" alt="Screenshot 2021-06-30 at 12 01 21" src="https://user-images.githubusercontent.com/875218/123949799-e67bdc00-d99a-11eb-987a-e50be3ef9c12.png">

The error makes me think this is a code issue:
```
The preview feature \"referentialActions\" is not known. Expected one of: microsoftSqlServer, orderByRelation, nApi, selectRelationCount, orderByAggregateGroup
```

`nApi` seems to be fine with electron app, as soon as I add `referentialActions` it's not though, and it seems to be missing in the error list so seems like there's an update required?

**Comment by madebysid** [comment]
Oh okay cool, I haven't released the Electron app since yesterday's release, so that's probably why. I'll do that soon and let you know!

**Comment by kkarimi** [comment]
@madebysid any news on release? thanks

**Comment by madebysid** [comment]
I was waiting for the next Prisma CLI release to sync versions, but I just pushed out 0.410.0 for you, let me know if that works!

**Comment by madebysid** [comment]
Can I close this now @kkarimi?

**Comment by kkarimi** [comment]
all good now thanks @madebysid
