### ISSUE TITLE
Can't open Prisma Studio from WSL 2

### ISSUE THREAD

**Issue by twhitson** [prisma/studio#719]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma               : 2.26.0
@prisma/client       : 2.26.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 9b816b3aa13cc270074f172f30d6eda8a8ce867d
Studio               : 0.408.0
```

2. Logs from Developer Tools Console or Command line, if any:

Browser:
```
Error starting Prisma Client: {
  "stack": "Error: Unable to get Prisma Client generator. This is a bug.
        at PCW.getDMMF (/home/twhitson/.nvm/versions/node/v16.4.1/lib/node_modules/prisma/build/index.js:108850:19)
        at async PrismaService.respond (/home/twhitson/.nvm/versions/node/v16.4.1/lib/node_modules/prisma/build/index.js:109180:50)
        at async /home/twhitson/.nvm/versions/node/v16.4.1/lib/node_modules/prisma/build/index.js:109354:35",
  "message": "Unable to get Prisma Client generator. This is a bug."
}
ki/this.init@http://localhost:5555/assets/index.js:1:103816
```
CLI:
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Prisma Studio is up on http://localhost:5555
Unable to get DMMF from Prisma Client:  Error: Unable to get Prisma Client generator. This is a bug.
    at PCW.getDMMF (/home/twhitson/.nvm/versions/node/v16.4.1/lib/node_modules/prisma/build/index.js:108850:19)
    at async PrismaService.respond (/home/twhitson/.nvm/versions/node/v16.4.1/lib/node_modules/prisma/build/index.js:109180:50)
    at async /home/twhitson/.nvm/versions/node/v16.4.1/lib/node_modules/prisma/build/index.js:109354:35
```

3. Other relevant versions:
- Microsoft Windows 10 Pro 10.0.19043 Build 19043
- Ubuntu 20.04.2 LTS on Windows 10 x86_64
- zsh 5.8
- node v16.4.1
- npm v7.18.1
- yarn v1.22.5

**Comment by twhitson** [comment]
I managed to figure this out, running `prisma generate` fixed it. I'm going to leave this bug open, however, because the error messaging could probably be improved.

**Comment by madebysid** [comment]
Hey @twhitson, this is definitely a bug, because Studio shouldn't depend on `prisma generate` at all. I'll investigate on WSL2, thanks for reporting!

**Comment by madebysid** [comment]
Okay I've just pushed out a `dev` version that should fix this. You can try it out by installing it: `npm i prisma@dev @prisma/client@dev`!

Going to close this now, but if you still see this, let me know!
