### ISSUE TITLE
Error starting Prisma Client: {   "message": "\n    Error: spawn typegraphql-prisma ENOENT\n        at notFoundError 

### ISSUE THREAD

**Issue by yashmc3** [prisma/studio#730]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "message": "\n    Error: spawn typegraphql-prisma ENOENT\n        at notFoundError (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:6:26)\n        at verifyENOENT (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:40:16)\n        at ChildProcess.cp.emit (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:27:25)",
  "stack": "AggregateError: \n    Error: spawn typegraphql-prisma ENOENT\n        at notFoundError (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:6:26)\n        at verifyENOENT (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:40:16)\n        at ChildProcess.cp.emit (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:27:25)\n    at next (C:\\Users\\c3controls\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\p-map\\index.js:43:14)\n    at C:\\Users\\c3controls\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\p-map\\index.js:59:6\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
}
Error: Error starting Prisma Client: {
  "message": "\n    Error: spawn typegraphql-prisma ENOENT\n        at notFoundError (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:6:26)\n        at verifyENOENT (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:40:16)\n        at ChildProcess.cp.emit (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:27:25)",
  "stack": "AggregateError: \n    Error: spawn typegraphql-prisma ENOENT\n        at notFoundError (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:6:26)\n        at verifyENOENT (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:40:16)\n        at ChildProcess.cp.emit (C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/node_modules/cross-spawn/lib/enoent.js:27:25)\n    at next (C:\\Users\\c3controls\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\p-map\\index.js:43:14)\n    at C:\\Users\\c3controls\\AppData\\Local\\Programs\\@prismastudio-electron\\resources\\app.asar\\node_modules\\p-map\\index.js:59:6\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
}
    at ki.init (file:///C:/Users/c3controls/AppData/Local/Programs/@prismastudio-electron/resources/app.asar/renderer/assets/index.js:1:103816)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @yashmc3 , thanks for reporting this. Could you show me the `generator`s you have defined in your Prisma Schema?
I think this might be related to (or the same thing as) #720

**Comment by madebysid** [comment]
Hey @yashmc3, I've just pushed out a `dev` version that should fix this. Could you try updating your Prisma CLI (and Client) version to `2.27.0-dev.5` and try again?

Do note that `dev` versions are mostly meant for internal use, and might contain unannounced breaking changes, so I'd recommend sticking with a stable Prisma version for your app.

Let me know if this is still broken for you, and I'll reopen!
