### ISSUE TITLE
Unable to connect to database

### ISSUE THREAD

**Issue by merelinguist** [prisma/studio#737]
**Describe the bug**
Clicking 'connect to database' isn't working.

**To Reproduce**
1. Import project from GitHub and to https://cloud.prisma.io/[username]/[slug]/newDatabase
2. There’s a text field to add a connection string
3. Clicking the submit button logs this to the console:

```
Uncaught (in promise) t: Command failed with ENOENT: /var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x
spawnSync /var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x ENOENT
{
  "message": "Command failed with ENOENT: /var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x\nspawnSync /var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x ENOENT",
  "locations": [
    {
      "line": 1,
      "column": 35
    }
  ],
  "path": [
    "linkDatabase"
  ],
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR",
    "exception": {
      "errno": -2,
      "code": "ENOENT",
      "syscall": "spawnSync /var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x",
      "path": "/var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x",
      "spawnargs": [],
      "originalMessage": "spawnSync /var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x ENOENT",
      "shortMessage": "Command failed with ENOENT: /var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x\nspawnSync /var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x ENOENT",
      "command": "/var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x",
      "escapedCommand": "\"/var/task/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x\"",
      "stdout": "",
      "stderr": "",
      "failed": true,
      "timedOut": false,
      "isCanceled": false,
      "killed": false
    }
  }
}
    at https://cloud.prisma.io/_next/static/chunks/371-9a408a3da60c968034a5.js:1:40137
    at https://cloud.prisma.io/_next/static/chunks/371-9a408a3da60c968034a5.js:1:38034
    at Object.next (https://cloud.prisma.io/_next/static/chunks/371-9a408a3da60c968034a5.js:1:38139)
    at a (https://cloud.prisma.io/_next/static/chunks/371-9a408a3da60c968034a5.js:1:36877)
```

**Expected behavior**
The database should connect.

**Desktop:**
 - OS: macOS Version 11.2.3 (Build 20D91)
 - Browser chrome
 - Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by madebysid** [comment]
Hey @merelinguist, thanks for reporting this! I'm able to see this as well, and I think I broke this in a recent deployment. I'll take a look ASAP and let you know what I find.

**Comment by madebysid** [comment]
Hey @merelinguist, this should be fixed now, please try again! Let me know if this still doesn't work for you. Sorry for the outage!
