### ISSUE TITLE
Could not find query-engine binary

### ISSUE THREAD

**Issue by kkarimi** [prisma/studio#770]
1. Prisma version (`prisma -v` or `npx prisma -v`):
Cloud Prisma studio (cloud.prisma.io) 

2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "message": "Could not find query-engine binary. Searched in /var/task/node_modules/@prisma/sdk/query-engine-rhel-openssl-1.0.x and /var/task/node_modules/@prisma/query-engine-rhel-openssl-1.0.x",
  "stack": "Error: Could not find query-engine binary. Searched in /var/task/node_modules/@prisma/sdk/query-engine-rhel-openssl-1.0.x and /var/task/node_modules/@prisma/query-engine-rhel-openssl-1.0.x\n    at resolveBinary (/var/task/node_modules/@prisma/sdk/dist/resolveBinary.js:93:9)\n    at async getConfigBinary (/var/task/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:102:27)\n    at async getConfig (/var/task/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:54:12)\n    at async Object.getGenerators (/var/task/node_modules/@prisma/sdk/dist/getGenerators.js:93:18)\n    at async Object.getGenerator (/var/task/node_modules/@prisma/studio-pcw/dist/generators.js:13:30)\n    at async PCW.getDMMF (/var/task/node_modules/@prisma/studio-pcw/dist/pcw.js:56:47)\n    at async handler (/var/task/.next/server/pages/api/databrowser.js:703:17)\n    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)\n    at async Server.handleApiRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:67:462)\n    at async Object.fn (/var/task/node_modules/next/dist/next-server/server/next-server.js:59:492)"
}
Error: Error starting Prisma Client: {
  "message": "Could not find query-engine binary. Searched in /var/task/node_modules/@prisma/sdk/query-engine-rhel-openssl-1.0.x and /var/task/node_modules/@prisma/query-engine-rhel-openssl-1.0.x",
  "stack": "Error: Could not find query-engine binary. Searched in /var/task/node_modules/@prisma/sdk/query-engine-rhel-openssl-1.0.x and /var/task/node_modules/@prisma/query-engine-rhel-openssl-1.0.x\n    at resolveBinary (/var/task/node_modules/@prisma/sdk/dist/resolveBinary.js:93:9)\n    at async getConfigBinary (/var/task/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:102:27)\n    at async getConfig (/var/task/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:54:12)\n    at async Object.getGenerators (/var/task/node_modules/@prisma/sdk/dist/getGenerators.js:93:18)\n    at async Object.getGenerator (/var/task/node_modules/@prisma/studio-pcw/dist/generators.js:13:30)\n    at async PCW.getDMMF (/var/task/node_modules/@prisma/studio-pcw/dist/pcw.js:56:47)\n    at async handler (/var/task/.next/server/pages/api/databrowser.js:703:17)\n    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)\n    at async Server.handleApiRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:67:462)\n    at async Object.fn (/var/task/node_modules/next/dist/next-server/server/next-server.js:59:492)"
}
    at ki.init (https://cloud.prisma.io/studio/assets/index.js:1:104126)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
NA

4. Prisma schema (if relevant):
```
NA
```

**Comment by madebysid** [comment]
Hey @kkarimi, just seeing this issue. I believe this was an issue, but the latest Prisma version (2.30.3 as of writing) should fix this. Could you confirm?
