### ISSUE TITLE
Error when opening Prisma Studio with `previewFeatures = ["fullTextSearch"]` in the Prisma schema

### ISSUE THREAD

**Issue by ValentaTomas** [prisma/studio#773]
Adding `fullTextSearch` preview features to the schema causes fatal error in Prisma Studio.

1. Prisma version (`prisma -v` or `npx prisma -v`):

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
Preview Features        : fullTextSearch
```

2. Logs from Developer Tools Console or Command line, if any:
Here are error logs from the Prisma Studio:
```
Error starting Prisma Client: {
  "message": "Get config: Schema Parsing P1012\n\nerror: The preview feature \"fullTextSearch\" is not known. Expected one of: microsoftSqlServer, orderByRelation, nApi, selectRelationCount, orderByAggregateGroup, filterJson, planetScaleMode, referentialActions, mongoDb, interactiveTransactions, namedConstraints\n  -->  schema.prisma:3\n   | \n 2 |   provider        = \"prisma-client-js\"\n 3 |   previewFeatures = [\"fullTextSearch\"]\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Get config: Schema Parsing P1012\n\nerror: The preview feature \"fullTextSearch\" is not known. Expected one of: microsoftSqlServer, orderByRelation, nApi, selectRelationCount, orderByAggregateGroup, filterJson, planetScaleMode, referentialActions, mongoDb, interactiveTransactions, namedConstraints\n  -->  schema.prisma:3\n   | \n 2 |   provider        = \"prisma-client-js\"\n 3 |   previewFeatures = [\"fullTextSearch\"]\n   | \n\nValidation Error Count: 1\n\n    at getConfigBinary (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:148:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getConfig (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:53:12)\n    at async Object.getGenerators (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/sdk/dist/getGenerators.js:93:18)\n    at async Object.getGenerator (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/dist/generators.js:9:30)\n    at async PCW.getDMMF (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/dist/pcw.js:56:47)\n    at async IpcMainImpl.prisma (/Applications/Prisma Studio.app/Contents/Resources/app.asar/build/ipc/prisma-ipc.js:26:54)"
}
Error: Error starting Prisma Client: {
  "message": "Get config: Schema Parsing P1012\n\nerror: The preview feature \"fullTextSearch\" is not known. Expected one of: microsoftSqlServer, orderByRelation, nApi, selectRelationCount, orderByAggregateGroup, filterJson, planetScaleMode, referentialActions, mongoDb, interactiveTransactions, namedConstraints\n  -->  schema.prisma:3\n   | \n 2 |   provider        = \"prisma-client-js\"\n 3 |   previewFeatures = [\"fullTextSearch\"]\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Get config: Schema Parsing P1012\n\nerror: The preview feature \"fullTextSearch\" is not known. Expected one of: microsoftSqlServer, orderByRelation, nApi, selectRelationCount, orderByAggregateGroup, filterJson, planetScaleMode, referentialActions, mongoDb, interactiveTransactions, namedConstraints\n  -->  schema.prisma:3\n   | \n 2 |   provider        = \"prisma-client-js\"\n 3 |   previewFeatures = [\"fullTextSearch\"]\n   | \n\nValidation Error Count: 1\n\n    at getConfigBinary (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:148:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getConfig (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/sdk/dist/engine-commands/getConfig.js:53:12)\n    at async Object.getGenerators (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/sdk/dist/getGenerators.js:93:18)\n    at async Object.getGenerator (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/dist/generators.js:9:30)\n    at async PCW.getDMMF (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/dist/pcw.js:56:47)\n    at async IpcMainImpl.prisma (/Applications/Prisma Studio.app/Contents/Resources/app.asar/build/ipc/prisma-ipc.js:26:54)"
}
    at ki.init (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/renderer/assets/index.js:1:104126)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}
...
```

**Comment by janpio** [comment]
The error message you are getting indicates it is running an older Query Engine in the CLI than expected - which does not support `fullTextSearch` yet. What command are you using to start Prisma Studio?

**Comment by ValentaTomas** [comment]
I'm using the Prisma Studio macOS app and I'm not starting it with a command, but via the actual App. The `-v` output is from the `npx prisma -v` from the project root directory where the schema is.

**Comment by janpio** [comment]
Seems the Electron app was not updated yet to support this preview feature. 

As you can see the CLI reports `Studio                  : 0.423.0`, but at least on Windows the downloadable app still lists `0.420.0` on the project selection screen 😢

**Comment by ValentaTomas** [comment]
Got it, can you please ping me here when the new Prisma Studio version is released?

**Comment by lohnsonok** [comment]
Prisma studio app open schema with error since update to 3.0.2 and run `prisma db pull`

**Comment by ValentaTomas** [comment]
I've tried it and everything looks good, thank you!
