### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hackemateninja** [prisma/studio#810]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "message": "\nYou don't have any models defined in your schema.prisma, so nothing will be generated.\nYou can define a model like this:\n\nmodel User {\n  id    Int     @id @default(autoincrement())\n  email String  @unique\n  name  String?\n}\n\nMore information in our documentation:\nhttps://pris.ly/d/prisma-schema\n",
  "stack": "Error: \nYou don't have any models defined in your schema.prisma, so nothing will be generated.\nYou can define a model like this:\n\nmodel User {\n  id    Int     @id @default(autoincrement())\n  email String  @unique\n  name  String?\n}\n\nMore information in our documentation:\nhttps://pris.ly/d/prisma-schema\n\n    at Object.getGenerators (/var/task/node_modules/@prisma/sdk/dist/get-generators/getGenerators.js:118:11)\n    at async $d91cd755f6821e74$export$a86aca265ced559b (/var/task/node_modules/@prisma/studio-pcw/dist/index.js:62:30)\n    at async $25632e7ad2eabd1d$var$PCW.getDMMF (/var/task/node_modules/@prisma/studio-pcw/dist/index.js:304:47)\n    at async /var/task/.next/server/pages/api/databrowser.js:865:19\n    at async /var/task/.next/server/pages/api/databrowser.js:861:37\n    at async /var/task/.next/server/pages/api/databrowser.js:1442:7\n    at async /var/task/.next/server/pages/api/databrowser.js:1442:7\n    at async handlerTraceWrapperSpan (/var/task/.next/server/pages/api/databrowser.js:214:22)\n    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:101:9)\n    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:770:9)"
}
Error: Error starting Prisma Client: {
  "message": "\nYou don't have any models defined in your schema.prisma, so nothing will be generated.\nYou can define a model like this:\n\nmodel User {\n  id    Int     @id @default(autoincrement())\n  email String  @unique\n  name  String?\n}\n\nMore information in our documentation:\nhttps://pris.ly/d/prisma-schema\n",
  "stack": "Error: \nYou don't have any models defined in your schema.prisma, so nothing will be generated.\nYou can define a model like this:\n\nmodel User {\n  id    Int     @id @default(autoincrement())\n  email String  @unique\n  name  String?\n}\n\nMore information in our documentation:\nhttps://pris.ly/d/prisma-schema\n\n    at Object.getGenerators (/var/task/node_modules/@prisma/sdk/dist/get-generators/getGenerators.js:118:11)\n    at async $d91cd755f6821e74$export$a86aca265ced559b (/var/task/node_modules/@prisma/studio-pcw/dist/index.js:62:30)\n    at async $25632e7ad2eabd1d$var$PCW.getDMMF (/var/task/node_modules/@prisma/studio-pcw/dist/index.js:304:47)\n    at async /var/task/.next/server/pages/api/databrowser.js:865:19\n    at async /var/task/.next/server/pages/api/databrowser.js:861:37\n    at async /var/task/.next/server/pages/api/databrowser.js:1442:7\n    at async /var/task/.next/server/pages/api/databrowser.js:1442:7\n    at async handlerTraceWrapperSpan (/var/task/.next/server/pages/api/databrowser.js:214:22)\n    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:101:9)\n    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:770:9)"
}
    at Us.init (https://cloud.prisma.io/studio/assets/index.js:1:85029)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @hackemateninja, as the error suggests, you'll need at least one model defined in your Prisma Schema for Studio to be able to do anything. I'm closing this for now, but please let me know if you disagree
