### ISSUE TITLE
postgres

### ISSUE THREAD

**Issue by jura4mal** [prisma/studio#817]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at us.serialize (https://5555-crimson-gopher-2kvh3tb9.ws-eu25.gitpod.io/assets/index.js:1:68610)
    at us.update (https://5555-crimson-gopher-2kvh3tb9.ws-eu25.gitpod.io/assets/index.js:1:14113)
    at yc (https://5555-crimson-gopher-2kvh3tb9.ws-eu25.gitpod.io/assets/vendor.js:41:6994)
    at us.n (https://5555-crimson-gopher-2kvh3tb9.ws-eu25.gitpod.io/assets/vendor.js:41:6688)
    at us.update (https://5555-crimson-gopher-2kvh3tb9.ws-eu25.gitpod.io/assets/index.js:1:68467)
    at yc (https://5555-crimson-gopher-2kvh3tb9.ws-eu25.gitpod.io/assets/vendor.js:41:6994)
    at us.n (https://5555-crimson-gopher-2kvh3tb9.ws-eu25.gitpod.io/assets/vendor.js:41:6688)
    at https://5555-crimson-gopher-2kvh3tb9.ws-eu25.gitpod.io/assets/index.js:1:83672
    at Array.forEach (<anonymous>)

**Comment by madebysid** [comment]
Hey @jura4mal, could you provide some more details about what exactly you were trying to do when this happened? Then I can try to reproduce. I'll reopen when you do that!

**Comment by jura4mal** [comment]
thanks, new branch resolved problems
