### ISSUE TITLE
Prisma Studio Error: Invalid length

### ISSUE THREAD

**Issue by BraindeadHermit** [prisma/studio#831]
## Logs:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49045)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48902)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82105
    at Array.forEach (<anonymous>)
```
## Problem
I am using prisma for a server that will have to interact with various clients, made with [```react```](https://it.reactjs.org/) and [```electron```](https://www.electronjs.org/), the database is deployed inside a ```docker``` container.
After making changes in the ```prisma.schema``` file, I encounter this error, which I cannot resolve.
I tried to recreate the container, perform a migration, delete all data, but it still doesn't work

**Comment by janpio** [comment]
What changes did you make? Did you restart Prisma Studio afterwards?

**Comment by BraindeadHermit** [comment]
i just added the unique keyword to some attributes.
Yes, i restarted prisma, i completely deleted the repo from my pc, i reconvened and redone it all over again but i didn't solve anything

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895
