### ISSUE TITLE
Running Prisma Studio causes Fatal Error

### ISSUE THREAD

**Issue by DNYLA** [prisma/studio#841]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma                  : 3.8.1
@prisma/client          : 3.8.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at C:\Users\Dan\AppData\Roaming\nvm\v16.12.0\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node)   
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at C:\Users\Dan\AppData\Roaming\nvm\v16.12.0\node_modules\prisma\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at C:\Users\Dan\AppData\Roaming\nvm\v16.12.0\node_modules\prisma\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at C:\Users\Dan\AppData\Roaming\nvm\v16.12.0\node_modules\prisma\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
```

2. Logs from Developer Tools Console or Command line, if any:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at us.serialize (http://localhost:5555/assets/index.js:1:68556)
    at us.update (http://localhost:5555/assets/index.js:1:14113)
    at yc (http://localhost:5555/assets/vendor.js:41:6994)
    at us.n (http://localhost:5555/assets/vendor.js:41:6688)
    at us.update (http://localhost:5555/assets/index.js:1:68413)
    at yc (http://localhost:5555/assets/vendor.js:41:6994)
    at us.n (http://localhost:5555/assets/vendor.js:41:6688)
    at http://localhost:5555/assets/index.js:1:83629
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
Yes

4. Prisma schema (if relevant):
The Issue occurred when I tried adding @map("Assignments") to the type enum. I have since removed it but even adding it back doesn't fix the issue.
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum Role {
  USER
  TUTOR
  ADMIN
  BOT
}

enum Subjects {
  maths
  compSci
  english
  chem
  physics
  bio
  other
}

enum Type {
  homework
  exam
  assignment
  hw
  other
}

enum Education {
  uni
  college
  other
}

model User {
  id               String         @id
  username         String
  discriminator    String
  avatar           String?        @default("")
  accessToken      String
  refreshToken     String
  tokenVersion     Int            @default(0)
  role             Role?          @default(USER)
  nodes            RedditConfig[]
  verifiedSubjects Subjects[]
  studentTickets   Ticket[]       @relation("student")
  tutorTickets     Ticket[]       @relation("tutor")
}

model RedditConfig {
  id             Int      @id @default(autoincrement())
  clientId       String
  clientSecret   String
  username       String
  password       String
  userAgent      String
  title          String
  pmBody         String
  subreddits     String[]
  forbiddenWords String[]
  blockedUsers   String[]
  userId         String
  nodeEditors    String[]
  delay          Int      @default(60)
  creator        User     @relation(fields: [userId], references: [id])
  logs           Log[]
}

//Commented Out Relations as Payment Configs can be used across Multiple
//Discord Configs
model DiscordConfig {
  id              String   @id
  name            String?
  icon            String?
  prefix          String   @default("?")
  embedImageUrl   String   @default("https://i.imgur.com/rDzblHE.gif")
  autoSwicher     Boolean  @default(false)
  autoTicket      Boolean  @default(false)
  autoReact       Boolean  @default(false)
  // payment Payment[]
  paymentConfigId String
  // Ticket          Ticket[]
  Ticket          Ticket[]
}

model Payment {
  id       Int    @id @default(autoincrement())
  name     String
  value    String
  type     String // Type 'Unlisted' will exclude it from being displayed. Used for paypal option.
  // discordConfig DiscordConfig @relation(fields: [serverId], references: [id])
  serverId String
}

enum OrderStatus {
  // INITIALIZED // Order has been created in table to link tutor to it
  CREATED // Actual invoice has been created (ie paypal order created)
  PAID // Invoice has been paid
}

model Order {
  id            Int         @id @default(autoincrement())
  status        OrderStatus
  tutorId       String
  transactionId String      @unique
  ticket        Ticket?     @relation(fields: [ticketId], references: [id])
  ticketId      Int? // Ticket id NOT `ticketid` in ticket
}

//Update Client side to not Post ticket until
//It is Finished.
model Ticket {
  id             Int           @id @default(autoincrement())
  serverId       String
  channelId      String        @default("xxx")
  type           Type?
  subject        Subjects?
  education      Education?
  budget         Int
  additionalInfo String        @default("")
  creatorId      String
  tutorId        String?
  due            DateTime
  completed      Boolean       @default(false)
  paid           Boolean       @default(false)
  student        User          @relation("student", fields: [creatorId], references: [id])
  tutor          User?         @relation("tutor", fields: [tutorId], references: [id])
  discordConfig  DiscordConfig @relation(fields: [serverId], references: [id])
  transactions   Order[]
}

model Log {
  id           Int          @id @default(autoincrement())
  nodeId       Int
  message      String
  subId        String
  username     String
  subreddit    String
  pm           Boolean
  createdAt    DateTime     @default(now())
  redditConfig RedditConfig @relation(fields: [nodeId], references: [id])
}


```

**Comment by DNYLA** [comment]
Had to clear cookies to fix the issue.

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895
