### ISSUE TITLE
Invalid string length

### ISSUE THREAD

**Issue by mofan20** [prisma/studio#842]
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/dist/renderer/assets/index.js:1:49045)
    at _t.update (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/dist/renderer/assets/index.js:1:12197)
    at Cc (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/dist/renderer/assets/vendor.js:50:6994)
    at _t.n (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/dist/renderer/assets/vendor.js:50:6688)
    at _t.update (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/dist/renderer/assets/index.js:1:48902)
    at Cc (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/dist/renderer/assets/vendor.js:50:6994)
    at _t.n (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/dist/renderer/assets/vendor.js:50:6688)
    at file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/dist/renderer/assets/index.js:1:82105
    at Array.forEach (<anonymous>)

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895
