### ISSUE TITLE
Prisma studio fails with 'Fatal Error' message

### ISSUE THREAD

**Issue by ACregan** [prisma/studio#851]
1. Prisma version (`prisma -v` or `npx prisma -v`):

```
prisma                  : 3.10.0-dev.20
@prisma/client          : 3.10.0-dev.20
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 60b16207c02de858be08e861ddaf1739c77eb43e (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 60b16207c02de858be08e861ddaf1739c77eb43e (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 60b16207c02de858be08e861ddaf1739c77eb43e (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 60b16207c02de858be08e861ddaf1739c77eb43e (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 60b16207c02de858be08e861ddaf1739c77eb43e
Studio                  : 0.458.0
```

2. Logs from Developer Tools Console or Command line, if any:

CONSOLE LOG:
```
[BootstrapStore.init] Studio bootstrap failed
{
  "message": "Invalid string length",
  "stack": "RangeError: Invalid string length\n    at JSON.stringify (<anonymous>)\n    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)\n    at _t.update (http://localhost:5555/assets/index.js:1:12197)\n    at Cc (http://localhost:5555/assets/vendor.js:50:6994)\n    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)\n    at _t.update (http://localhost:5555/assets/index.js:1:48948)\n    at Cc (http://localhost:5555/assets/vendor.js:50:6994)\n    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)\n    at http://localhost:5555/assets/index.js:1:82151\n    at Array.forEach (<anonymous>)"
}

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (:5555/assets/index.js:1:49091)
    at _t.update (:5555/assets/index.js:1:12197)
    at Cc (:5555/assets/vendor.js:50:6994)
    at _t.n (:5555/assets/vendor.js:50:6688)
    at _t.update (:5555/assets/index.js:1:48948)
    at Cc (:5555/assets/vendor.js:50:6994)
    at _t.n (:5555/assets/vendor.js:50:6688)
    at :5555/assets/index.js:1:82151
    at Array.forEach (<anonymous>)
```

STUDIO UI ERROR REPORT:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82151
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
Yes, I had this issue yesterday but upgrading to dev release stream it seemed to resolve it.  However starting up my project again today, the error reoccurred, I tried upgrading again to latest DEV release but the problem persists.

4. Prisma schema (if relevant):
```
Not applicable, the issue is that Prisma Studio fails to start.
```

**Comment by ACregan** [comment]
WORTH NOTING FOR OTHER USERS (I see a lot of similar tickets):

Going to Application Tab, Clearing IndexedDB and Session In Application Tab in Chrome Dev Tools seems to have worked around the issue.

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895
