### ISSUE TITLE
Fatal Error Starting prisma

### ISSUE THREAD

**Issue by raphaelbmesquita123** [prisma/studio#863]
1. Prisma version (`prisma -v` or `npx prisma -v`):
  "prisma": "^3.10.0",
2. Logs from Developer Tools Console or Command line, if any:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82151
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by ioofy** [comment]
I have some bugs like this, and how about change your browser or open it into cognito mode? See what happens?

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895

**Comment by Joseamica** [comment]
> See #895

thanks
