### ISSUE TITLE
[Bug] RangeError: Invalid string length

### ISSUE THREAD

**Issue by ioofy** [prisma/studio#867]
1. Prisma version (`^3.8.0` ):

2. Logs from Developer Tools Console or Command line, if any:
```bash
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82151
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`^3.8.0`)

4. Prisma schema (if relevant):
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id          String     @id @default(cuid())
  username    String?    @unique
  name        String?
  email       String?    @unique
  avatarUrl   String?
  password    String?
  bio         String?
  googleId    String?    @unique
  slug        String?
  coverPhoto  String?
  token       String?    @unique
  isCreator   Boolean    @default(false)
  isVerified  Boolean    @default(false)
  createdAt   DateTime   @default(now()) @map(name: "created_at")
  updatedAt   DateTime   @default(now()) @map(name: "updated_at")
  following   User[]     @relation(name: "FollowRelation", references: [id])
  followers   User[]     @relation(name: "FollowRelation", references: [id])
  likes       LikedPost[]
  posts       Post[]
  comments    Comment[]
  profession  Profession[]

  @@map(name: "users")
}


model Post {
  id        String      @id @default(cuid())
  likes     LikedPost[]
  comments  Comment[]
  content   String
  published Boolean    @default(false)
  createdAt DateTime   @default(now()) @map(name: "created_at")
  updatedAt DateTime   @default(now()) @map(name: "updated_at")
  authorId  String        
  author    User       @relation(fields: [authorId], references: [id])

  @@map(name: "posts")
}

model LikedPost {
  id      Int      @id @default(autoincrement())
  post    Post     @relation(fields: [postId], references: [id])
  user    User     @relation(fields: [userId], references: [id])
  date    DateTime @default(now())
  postId  String
  userId  String

  @@map(name: "likedposts")
}

model Comment {
  id        Int      @id @default(autoincrement())
  text      String
  post      Post     @relation(fields: [postId], references: [id])
  user      User     @relation(fields: [userId], references: [id])
  userId    String
  postId    String
  date      DateTime @default(now())

  @@map(name: "comments")
}


model Profession{
  id          Int        @default(autoincrement()) @id
  role        String     @unique
  userId      String
  user        User       @relation(fields: [userId], references: [id])

  @@map(name: "profession")
}


```

**Comment by Matzu89** [comment]
Same here

```
Environment variables loaded from .env
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0
Preview Features        : mongoDb
```

**Comment by ioofy** [comment]
I solved this issue by opening prisma in another web like edge this issue running only on chrome and Firefox but if you open the prisma engine at incognito it's working fine too. Try it

**Comment by Matzu89** [comment]
Fixed this by removing and clearing site data. To be specific: clear IndexedDB.

![image](https://user-images.githubusercontent.com/4165252/157908318-434bc07c-cc75-47d4-a469-5a683f9dbd1d.png)

**Comment by ioofy** [comment]
> Fixed this by removing and clearing site data. To be specific: clear IndexedDB.
> 
> ![image](https://user-images.githubusercontent.com/4165252/157908318-434bc07c-cc75-47d4-a469-5a683f9dbd1d.png)

Yeah just knowing that. Thanks for information 😉

**Comment by ioofy** [comment]
Fix and the solutions in comment. 🙏

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895
