### ISSUE TITLE
Fatal Error when loading prisma studio

### ISSUE THREAD

**Issue by tiller92** [prisma/studio#884]
1. Prisma version (`prisma -v` or `npx prisma -v`
```
prisma                  : 3.12.0-dev.9
@prisma/client          : 3.9.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 3f4e645b4b21517662fa7940520ce0b50303cb11 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 3f4e645b4b21517662fa7940520ce0b50303cb11 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 3f4e645b4b21517662fa7940520ce0b50303cb11 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 3f4e645b4b21517662fa7940520ce0b50303cb11 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 3f4e645b4b21517662fa7940520ce0b50303cb11
Studio                  : 0.458.0

```
3. Logs from Developer Tools Console or Command line, if any:
```
no logs in console
```

4. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
```
yes
```
5. Prisma schema (if relevant):
```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}



model User {
  id         Int    @id @default(autoincrement())
  first_name String
  last_name  String
  email      String
  username   String @unique
  password   String
  stocks Userstocks[]
  crypto Usercrypto[]
  realestate Userrealestate[]
  debt Userdebt[]
}

model Userstocks {
  id  Int @id @default(autoincrement())
  ticker String
  shares Decimal
  owner User @relation(fields: [ownerName],references: [username])
  ownerName String
}

model Usercrypto {
   id  Int @id @default(autoincrement())
  name String
  shares Decimal
  owner User @relation(fields: [ownerName],references: [username])
  ownerName String
}

model Userrealestate {
  id  Int @id @default(autoincrement())
  name String
  value Decimal
  owner User @relation(fields: [ownerName],references: [username])
  ownerName String
}

model Userdebt {
  id  Int @id @default(autoincrement())
  type String
  interest Decimal
  debt Decimal
  owner User @relation(fields: [ownerName],references: [username])
  ownerName String
}


```

**Comment by tiller92** [comment]
Here is the error details that pop up in the browser.
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82151
    at Array.forEach (<anonymous>)
```

**Comment by NathanJeong** [comment]
Did you solve this problem? Suddenly I got the same problem too.

**Comment by ioofy** [comment]
Please check this issue and comment https://github.com/prisma/studio/issues/867

**Comment by tiller92** [comment]
Thanks

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895

**Comment by tiller92** [comment]
Thanks!

**Comment by tiller92** [comment]
No I haven’t found a solution.
