### ISSUE TITLE
Suddenly can't access to prisma studio

### ISSUE THREAD

**Issue by NathanJeong** [prisma/studio#889]
1. Prisma version (`prisma -v` or `npx prisma -v`):
"@prisma/client": "^3.11.0",

2. Logs from Developer Tools Console or Command line, if any:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82151
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
No, suddenly happened.

4. Prisma schema (if relevant):
```
model User {
  id           Int           @id @default(autoincrement())
  phone        String        @unique
  email        String        @unique
  username     String        @unique
  name         String
  password     String
  bio          String?
  avatar       String?
  nationality  String
  isAdmin      Boolean       @default(false)
  followers    User[]        @relation("FollowRelation", references: [id])
  following    User[]        @relation("FollowRelation", references: [id])
  photos       Photo[]
  feedlikes    Feedlike[]
  comments     Comment[]
  rooms        Room[]
  messages     Message[]
  createdAt    DateTime      @default(now())
  updatedAt    DateTime      @updatedAt
  products     Product[]
  productlikes Productlike[]
  communities  Community[]
  answers      Answer[]
  wonderings   Wondering[]
}

model Photo {
  id        Int        @id @default(autoincrement())
  user      User       @relation(fields: [userId], references: [id])
  userId    Int
  file      String
  caption   String?
  hashtags  Hashtag[]
  feedlikes Feedlike[]
  comments  Comment[]
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
}

model Hashtag {
  id        Int      @id @default(autoincrement())
  hashtag   String   @unique
  photos    Photo[]
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Feedlike {
  id        Int      @id @default(autoincrement())
  photo     Photo    @relation(fields: [photoId], references: [id])
  photoId   Int
  user      User     @relation(fields: [userId], references: [id])
  userId    Int
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@unique([photoId, userId])
}

model Comment {
  id        Int      @id @default(autoincrement())
  user      User     @relation(fields: [userId], references: [id])
  userId    Int
  photo     Photo    @relation(fields: [photoId], references: [id])
  photoId   Int
  payload   String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Room {
  id        Int       @id @default(autoincrement())
  users     User[]
  messages  Message[]
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
}

model Message {
  id        Int      @id @default(autoincrement())
  payload   String
  user      User     @relation(fields: [userId], references: [id])
  userId    Int
  room      Room     @relation(fields: [roomId], references: [id])
  roomId    Int
  read      Boolean  @default(false)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Product {
  id              Int              @id @default(autoincrement())
  user            User             @relation(fields: [userId], references: [id])
  userId          Int
  file            String
  caption         String?
  description     String
  price           Int
  producthashtags Producthashtag[]
  productlikes    Productlike[]
  createdAt       DateTime         @default(now())
  updatedAt       DateTime         @updatedAt
}

model Producthashtag {
  id        Int       @id @default(autoincrement())
  hashtag   String    @unique
  products  Product[]
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
}

model Productlike {
  id        Int      @id @default(autoincrement())
  product   Product  @relation(fields: [productId], references: [id])
  productId Int
  user      User     @relation(fields: [userId], references: [id])
  userId    Int
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@unique([productId, userId])
}

model Community {
  id        Int         @id @default(autoincrement())
  user      User        @relation(fields: [userId], references: [id])
  userId    Int
  question  String
  answers   Answer[]
  wondering Wondering[]
  latitude  Float?
  longitude Float?
  createdAt DateTime    @default(now())
  updatedAt DateTime    @updatedAt
}

model Answer {
  id          Int       @id @default(autoincrement())
  user        User      @relation(fields: [userId], references: [id])
  userId      Int
  community   Community @relation(fields: [communityId], references: [id])
  communityId Int
  answer      String
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
}

model Wondering {
  id          Int       @id @default(autoincrement())
  user        User      @relation(fields: [userId], references: [id])
  userId      Int
  community   Community @relation(fields: [communityId], references: [id])
  communityId Int
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
}
```

**Comment by NathanJeong** [comment]
Thanks. That worked!

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895
