### ISSUE TITLE
Unable to use the data platform for a number of days now

### ISSUE THREAD

**Issue by HarjaapSinghM** [prisma/studio#891]
1. Prisma version (3.0.2):

2. Logs from Developer Tools Console or Command line:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (https://cloud.prisma.io/studio/assets/index.js:1:49045)
    at _t.update (https://cloud.prisma.io/studio/assets/index.js:1:12197)
    at Cc (https://cloud.prisma.io/studio/assets/vendor.js:50:6994)
    at _t.n (https://cloud.prisma.io/studio/assets/vendor.js:50:6688)
    at _t.update (https://cloud.prisma.io/studio/assets/index.js:1:48902)
    at Cc (https://cloud.prisma.io/studio/assets/vendor.js:50:6994)
    at _t.n (https://cloud.prisma.io/studio/assets/vendor.js:50:6688)
    at https://cloud.prisma.io/studio/assets/index.js:1:82105
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
Not sure if this is relevant since it's the cloud platform

**Comment by janpio** [comment]
Clearing your browser cache might help. Check the other issues under https://github.com/prisma/studio/labels/topic%3A%20Invalid%20string%20length

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895
