### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by janpio** [prisma/studio#895]
1. Prisma version (`prisma -v` or `npx prisma -v`):

Checkout of Studio-Code repository

2. Logs from Developer Tools Console or Command line, if any:
```
[vite] connecting...
BootstrapStore.ts:31 Studio version 0.458.0
BootstrapStore.ts:185 RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Script.serialize (src/stores/script/Script.ts:173:20)
    at Script.update (src/stores/base/BaseListItem.ts:23:27)
    at executeAction (node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:752:15)
    at Script.update (node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:739:12)
    at Script.update (src/stores/script/Script.ts:164:13)
    at executeAction (node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:752:15)
    at Script.update (node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:739:12)
    at src/stores/bootstrap/BootstrapStore.ts:101:38
    at Array.forEach (<anonymous>)
init @ BootstrapStore.ts:185
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Modal
printWarning @ react-dom.development.js:88
createError.ts:50 [BootstrapStore.init] Studio bootstrap failed Object
createError @ createError.ts:50
createError.ts:51 RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Script.serialize (src/stores/script/Script.ts:173:20)
    at Script.update (src/stores/base/BaseListItem.ts:23:27)
    at executeAction (node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:752:15)
    at Script.update (node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:739:12)
    at Script.update (src/stores/script/Script.ts:164:13)
    at executeAction (node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:752:15)
    at Script.update (node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:739:12)
    at src/stores/bootstrap/BootstrapStore.ts:101:38
    at Array.forEach (<anonymous>)
createError @ createError.ts:51
BootstrapStore.ts:213 Uncaught (in promise) StudioError
```

<img width="365" alt="image" src="https://user-images.githubusercontent.com/183673/160829416-afce4e4a-6423-4b8c-b484-7806c191474d.png">

```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Script.serialize (https://3001-prisma-studiocode-oap8wu2yudj.ws-eu38.gitpod.io/src/stores/script/Script.ts:173:20)
    at Script.update (https://3001-prisma-studiocode-oap8wu2yudj.ws-eu38.gitpod.io/src/stores/base/BaseListItem.ts:23:27)
    at executeAction (https://3001-prisma-studiocode-oap8wu2yudj.ws-eu38.gitpod.io/node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:752:15)
    at Script.update (https://3001-prisma-studiocode-oap8wu2yudj.ws-eu38.gitpod.io/node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:739:12)
    at Script.update (https://3001-prisma-studiocode-oap8wu2yudj.ws-eu38.gitpod.io/src/stores/script/Script.ts:164:13)
    at executeAction (https://3001-prisma-studiocode-oap8wu2yudj.ws-eu38.gitpod.io/node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:752:15)
    at Script.update (https://3001-prisma-studiocode-oap8wu2yudj.ws-eu38.gitpod.io/node_modules/.vite/chunk-TBMQ2Y3I.js?v=04cb37f7:739:12)
    at https://3001-prisma-studiocode-oap8wu2yudj.ws-eu38.gitpod.io/src/stores/bootstrap/BootstrapStore.ts:101:38
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

Yes

4. Prisma schema (if relevant):
Not relevant

**Comment by janpio** [comment]
Workaround is to delete the IndexedDB database via your browser's developer tools:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/183673/160829683-e322da06-a907-4cd8-9d21-e656795acaf3.png">

**Comment by ioofy** [comment]
Kinda nicely sir.

**Comment by mzw4** [comment]
Workaround worked for me, thanks!

**Comment by hussamkhatib** [comment]
Tried clearing out the indexed db. Dint work.
I'm using another browser as a workaround temporarily

**Comment by abdipriyangga** [comment]
Nice sir, I follow your suggestion, and that works for me.

**Comment by jonschlinkert** [comment]
Had the same bug. Can confirm that this worked for me.

**Comment by dancosta-fed** [comment]
I've got the ERR_EMPTY_RESPONSE. 

My Prisma Studio was working just fine. Until I tried to migrate a change to a model I had used before. So, in my terminal I was advised to run ``yarn prisma migrate dev --create-only``. And so I did, thought I'd manually apply the changes to the things I've used.

But then I got an error. (Can remember what it said exactly).

Tried reloading the Prisma Studio, tried killing it and doing it again.. even tried repeating the process.  But now, no matter what prisma command I try to use.. they all send me to prisma studio and the page what open.

<img width="347" alt="Captura de Tela 2023-11-15 às 14 59 29" src="https://github.com/prisma/studio/assets/69706855/e7d1482e-30ed-4c1a-92f0-ab4b57d0625a">

any ideas?

**Comment by igalklebanov** [comment]
Hey 👋

Prisma ORM 7 introduces a brand new standalone [Studio](https://www.prisma.io/docs/orm/tools/prisma-studio), built from the ground up to work everywhere, with or without Prisma ORM. Consequently, all "old Studio" issues are being closed as there won't be any further work on it. 📣

The new Studio is also available in the Prisma VS Code extension and in the Prisma Console application. 🔌

Help shape, improve and fix the new Studio with us in this repository by submitting bug reports and feature requests. 👷
