### ISSUE TITLE
Prisma Studio Crashes with RangeError: Invalid string length

### ISSUE THREAD

**Issue by hallahan** [prisma/studio#908]
Hope this is enough to come up with a fix!

1. Prisma version (`prisma -v` or `npx prisma -v`):

3.12.0

3. Logs from Developer Tools Console or Command line, if any:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:1 RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (index.js:1:49091)
    at _t.update (index.js:1:12197)
    at Cc (vendor.js:50:6994)
    at _t.n (vendor.js:50:6688)
    at _t.update (index.js:1:48948)
    at Cc (vendor.js:50:6994)
    at _t.n (vendor.js:50:6688)
    at index.js:1:82272
    at Array.forEach (<anonymous>)
```

```
Uncaught (in promise) 
B
code: undefined
context: {message: 'Invalid string length', stack: 'RangeError: Invalid string length\n    at JSON.stri…dex.js:1:82272\n    at Array.forEach (<anonymous>)'}
message: "Studio bootstrap failed"
nativeError: RangeError: Invalid string length at JSON.stringify (<anonymous>) at _t.serialize (http://localhost:5555/assets/index.js:1:49091) at _t.update (http://localhost:5555/assets/index.js:1:12197) at Cc (http://localhost:5555/assets/vendor.js:50:6994) at _t.n (http://localhost:5555/assets/vendor.js:50:6688) at _t.update (http://localhost:5555/assets/index.js:1:48948) at Cc (http://localhost:5555/assets/vendor.js:50:6994) at _t.n (http://localhost:5555/assets/vendor.js:50:6688) at http://localhost:5555/assets/index.js:1:82272 at Array.forEach (<anonymous>)
path: "BootstrapStore.init"
stack: undefined
type: undefined
```

4. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

Still crashes

6. Prisma schema (if relevant):

Cannot publish this publicly. Happy to chat 1-1.

**Comment by hallahan** [comment]
I'm using PostgreSQL.

I tried disabling `previewFeatures = ["extendedIndexes", "fullTextSearch"]`, but it still crashes the same.

**Comment by hallahan** [comment]
Ah, this is a duplicate.

https://github.com/prisma/studio/issues/895
