### ISSUE TITLE
Prisma Studio Crash

### ISSUE THREAD

**Issue by lexkornyukhin** [prisma/studio#919]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma                  : 3.13.0-dev.29
@prisma/client          : 3.12.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 07815b335736eb128666b4a5a86e94e19656f4ff (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 07815b335736eb128666b4a5a86e94e19656f4ff (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 07815b335736eb128666b4a5a86e94e19656f4ff (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 07815b335736eb128666b4a5a86e94e19656f4ff (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 07815b335736eb128666b4a5a86e94e19656f4ff
Studio                  : 0.459.0
```

2. Logs from Developer Tools Console or Command line, if any:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)
```

![Screenshot 2022-04-22 at 14 41 36](https://user-images.githubusercontent.com/97899121/164726153-c096464c-6687-4265-a68f-08a5c0e90edf.png)

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
Yes

4. Prisma schema (if relevant):
```
```

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895
