### ISSUE TITLE
Unable to get DMMF from Prisma Client:  AggregateError

### ISSUE THREAD

**Issue by tingfeng-key** [prisma/studio#933]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma                : 3.12.0
@prisma/client        : Not found
Current platform      : windows
Query Engine (Binary) : query-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at C:\Users\ld_100\AppData\Local\prisma\binaries\cli\3.12.0\22b822189f46ef0dc5c5b503368d1bee01213980\prisma-query-engine-windows.exe, resolved by PRISMA_
QUERY_ENGINE_BINARY)
Migration Engine      : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at C:\Users\ld_100\AppData\Local\prisma\binaries\cli\3.12.0\22b822189f46ef0dc5c5b503368d1bee01213980\prisma-migration-engine-windows.exe, resolve
d by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine  : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at C:\Users\ld_100\AppData\Local\prisma\binaries\cli\3.12.0\22b822189f46ef0dc5c5b503368d1bee01213980\prisma-introspection-engine-windows.exe, resol
ved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary         : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at C:\Users\ld_100\AppData\Local\prisma\binaries\cli\3.12.0\22b822189f46ef0dc5c5b503368d1bee01213980\prisma-prisma-fmt-windows.exe, resolved by PRISMA_FMT_
BINARY)
Default Engines Hash  : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                : 0.459.0
```

2. Logs from Developer Tools Console or Command line, if any:
```
Unable to get DMMF from Prisma Client:  AggregateError:
    Error: Generator at C:/snapshot/node_modules/prisma/prisma-client/generator-build/index.js could not start:
    internal/modules/cjs/loader.js:1030
      throw err;
      ^
    Error: Cannot find module 'D:/bt/wwwroot/server/--max-old-space-size=8096'
        at Function._resolveFilename (pkg/prelude/bootstrap.js:1459:46)
        at Function.runMain (pkg/prelude/bootstrap.js:1488:12)
        at internal/main/run_main_module.js:17:47 {
      code: 'MODULE_NOT_FOUND',
      requireStack: []
    }
        at Timeout._onTimeout (C:/snapshot/node_modules/prisma/build/index.js:43167:25)
    at next (C:\snapshot\node_modules\prisma\build\index.js:17642:25)
    at C:\snapshot\node_modules\prisma\build\index.js:17663:17
```

4. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

5. Prisma schema (if relevant):
```
datasource db {
    provider = "sqlite"
    url      = "file:./dev.db"
}

generator client {
    provider = "cargo prisma"
    output   = "../src/prisma.rs"
}

model User {
  id    String  @id @default(uuid())
  email String  @unique
  name  String?
}
```

**Comment by richtermb** [comment]
Hey I saw you closed this issue. I'm getting the same error when using the rust client. Did you end up fixing it? If so, how?

**Comment by tingfeng-key** [comment]
At present, it has not been resolved. This issue seems to be a problem in the `Prisma client rust`, so I closed it
