### ISSUE TITLE
?

### ISSUE THREAD

**Issue by SmartFish4** [prisma/studio#943]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)

**Comment by petradonka** [comment]
Could you check if [this](https://github.com/prisma/studio/issues/895#issuecomment-1083051249) resolves the issue for you?

**Comment by SmartFish4** [comment]
Walter Paiva

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895

**Comment by SmartFish4** [comment]
Walter Paiva
