### ISSUE TITLE
Prisma Studio Crashed : A non recoverable error has occured.

### ISSUE THREAD

**Issue by spss20** [prisma/studio#947]
1. Prisma version (`3.14.0` or `3.14.0`):

```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)

```
2. Logs from Developer Tools Console or Command line, if any:
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "fcc" at "localhost:3306"

The migration `20220526183827_atg` failed.
✔ We need to reset the MySQL database "fcc" at "localhost:3306".
Do you want to continue? All data will be lost. … yes

Applying migration `20220524085105_init`
Applying migration `20220524085345_added_varchar_length`
Applying migration `20220524110830_password_field_added`
Applying migration `20220526030008_role`
Applying migration `20220526102404_product_fan_mode_and_eps_added`
Applying migration `20220526102714_product_fan_mode_and_eps_added`
Applying migration `20220526103007_product_fan_mode_and_eps_added`
Applying migration `20220526103033_product_fan_mode_and_eps_added`
Applying migration `20220526163819_eps_schema_updated`
Applying migration `20220526175801_tank_added`
Applying migration `20220526180950_tank_modified`
Applying migration `20220526183827_atg`

The following migration(s) have been applied:

migrations/
  └─ 20220524085105_init/
    └─ migration.sql
  └─ 20220524085345_added_varchar_length/
    └─ migration.sql
  └─ 20220524110830_password_field_added/
    └─ migration.sql
  └─ 20220526030008_role/
    └─ migration.sql
  └─ 20220526102404_product_fan_mode_and_eps_added/
    └─ migration.sql
  └─ 20220526102714_product_fan_mode_and_eps_added/
    └─ migration.sql
  └─ 20220526103007_product_fan_mode_and_eps_added/
    └─ migration.sql
  └─ 20220526103033_product_fan_mode_and_eps_added/
    └─ migration.sql
  └─ 20220526163819_eps_schema_updated/
    └─ migration.sql
  └─ 20220526175801_tank_added/
    └─ migration.sql
  └─ 20220526180950_tank_modified/
    └─ migration.sql
  └─ 20220526183827_atg/
    └─ migration.sql


Your database is now in sync with your schema.

✔ Generated Prisma Client (3.14.0 | library) to ./node_modules/@prisma/client in 78ms
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? YES, I'm already using latest version

4. Prisma schema (if relevant):
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

enum FanMode {
  ON
  OFF
  AUTO
}

enum CommunicationType {
  Ethernet
  Serial
}

model User {
  id         Int      @id @default(autoincrement())
  username   String   @unique @db.VarChar(64)
  name       String   @db.VarChar(255)
  password   String   @db.VarChar(255)
  role       Role     @relation(fields: [role_id], references: [id])
  role_id    Int
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt
}

model Role {
  id        Int    @id @default(autoincrement())
  role_name String @db.VarChar(64)
  User      User[]
}

model Eps {
  id         Int               @id @default(autoincrement())
  eps_id     Int
  eps_make   String
  com_id     Int
  com_type   CommunicationType @default(Serial)
  brightness Int
  fan_mode   FanMode           @default(AUTO)
  Product    Product[]
  created_at DateTime          @default(now())
  updated_at DateTime          @updatedAt

  @@unique([eps_id, com_id])
}

model Product {
  id            Int      @id @default(autoincrement())
  product_name  String
  product_price String?
  eps           Eps?     @relation(fields: [eps_id], references: [id])
  tank          Tank[]
  eps_id        Int?
  created_at    DateTime @default(now())
  updated_at    DateTime @updatedAt
}

model Tank {
  id           Int      @id @default(autoincrement())
  tank_id      Int      @unique
  product      Product  @relation(fields: [product_id], references: [id])
  product_id   Int
  volume       Float?   @db.Double
  tc_volume    Float?   @db.Double
  ullage       Float?   @db.Double
  height       Float?   @db.Double
  water        Float?   @db.Double
  temperature  Float?   @db.Double
  water_height Float?   @db.Double
  created_at   DateTime @default(now())
  updated_at   DateTime @updatedAt
}

model ATG {
  id         Int               @id @default(autoincrement())
  atg_make   String
  com_type   CommunicationType @default(Serial)
  com_id     Int
  ip_address String
  created_at DateTime          @default(now())
  updated_at DateTime          @updatedAt
}

```

**Comment by spss20** [comment]
OK so just figured out, that it got fixed after clearing cookies on browser.

**Comment by petradonka** [comment]
Glad to hear this got resolved 👌
