### ISSUE TITLE
Invalid string length

### ISSUE THREAD

**Issue by m4theuspereira-maker** [prisma/studio#955]
1. Prisma version (`prisma -v` or `npx prisma -v`): 3.14.0

2. Logs from Developer Tools Console or Command line, if any:
```
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
yes

**Comment by petradonka** [comment]
Take a look at https://github.com/prisma/studio/issues/895 for details on how to resolve this issue.
