### ISSUE TITLE
Error after open cloud.prisma.io

### ISSUE THREAD

**Issue by semgoSE** [prisma/studio#959]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (https://cloud.prisma.io/studio/assets/index.js:1:49091)
    at _t.update (https://cloud.prisma.io/studio/assets/index.js:1:12197)
    at Cc (https://cloud.prisma.io/studio/assets/vendor.js:50:6994)
    at _t.n (https://cloud.prisma.io/studio/assets/vendor.js:50:6688)
    at _t.update (https://cloud.prisma.io/studio/assets/index.js:1:48948)
    at Cc (https://cloud.prisma.io/studio/assets/vendor.js:50:6994)
    at _t.n (https://cloud.prisma.io/studio/assets/vendor.js:50:6688)
    at https://cloud.prisma.io/studio/assets/index.js:1:82272
    at Array.forEach (<anonymous>)
```

**Comment by petradonka** [comment]
Could you try the fix described in https://github.com/prisma/studio/issues/895 and see if you're still running into this issue?
