### ISSUE TITLE
 Can't connect to prisma studio --command `yarn prisma studio`

### ISSUE THREAD

**Issue by ikmzkro** [prisma/studio#977]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma : 4.1.0-dev.43
```

2. Logs from Developer Tools Console or Command line, if any:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82151
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
Yes it does.
```
npm i -D prisma@dev
```

<img width="459" alt="image" src="https://user-images.githubusercontent.com/74099733/177927117-cbea354e-05c7-46e2-88ae-30ab603d1b4e.png">

**Comment by d-ivashchuk** [comment]
Hey @ikmz0104! Do you mind sharing a little bit more detail on how you got to this error? Did you apply some filters, or switched tabs maybe?

Any additional information would help us figuring this out!

**Comment by moogmodular** [comment]
had the same issue: resolved it by removing all cookies, local storage, db entries in the applications tab for `localhost:5555`

**Comment by janpio** [comment]
Side note: the workaround for this is "documented" at https://github.com/prisma/studio/issues/895

But @d-ivashchuk is interested in figuring out _why_ this is happening so we can fix it. Can you maybe provide answers to the questions he posted above @moogmodular?
