### ISSUE TITLE
[SOLVE] Invalid String Length

### ISSUE THREAD

**Issue by thoberth** [prisma/studio#981]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma                  : 4.1.0-dev.74
@prisma/client          : 4.0.0
Current platform        : darwin
```
2. Logs from Developer Tools Console or Command line, if any:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)
```
<img width="566" alt="Capture d’écran 2022-07-16 à 11 11 38" src="https://user-images.githubusercontent.com/56259689/179348605-661c7c9a-52f7-4283-8b82-e4bc13365e11.png">

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by janpio** [comment]
Here is how to solve this: https://github.com/prisma/studio/issues/895#issuecomment-1083051249

Can you share what exactly you did before you got into this situation though?
Did you open new tabs, add filters, try to save changes?

**Comment by thoberth** [comment]
Hello, thank you I just see this issues

**Comment by petradonka** [comment]
Thanks for the extra info!

I see that you've updated the title to indicate that your issue is solved, so I'll close this one now. Let us know if your run into any further issues.
