### ISSUE TITLE
this happend after i added image String[]

### ISSUE THREAD

**Issue by sifat0666** [prisma/studio#988]
1. Prisma version (`prisma -v` or `npx prisma -v`):
4.1.0
2. Logs from Developer Tools Console or Command line, if any:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at xt.serialize (http://localhost:5555/assets/index.js:1:49091)
    at xt.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at xt.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
yes
4. Prisma schema (if relevant):
```
model Product {
  id        String     @default(cuid()) @id
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  String?
  image String[]
}
```

**Comment by insuusvenerati** [comment]
Is this happening in Prisma Studio? That's where I'm seeing this error. Issue occurred 4.0.0 as well.

**Comment by d-ivashchuk** [comment]
hey @sifat0666! was there anything in particular that you noticed doing that brought you to this error maybe? This would help us investigate it & provide the fix asap. Thanks!

**Comment by richpeachpan** [comment]
Hi! I had the same problem. Try to remove cookies or open Prisma studio in a private (incognito) window. It helped me.

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895
